/**
 * Source code generated by uk.ac.leeds.ccg.andyt.generic.data.us.process.US_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.andyt.generic.data.us.data.hhresp;
public class US_Wave2_hhresp_Record extends US_hhresp_Record {
protected double BASEPI;
protected double BHCIND;
protected double BHCINDA;
protected short CD1NEW;
protected short CD1USE;
protected short CD2NEW;
protected short CD2USE;
protected byte CD3NEW;
protected byte CD3USE;
protected short CD4NEW;
protected short CD4USE;
protected byte CD5NEW;
protected byte CD5USE;
protected short CD6NEW;
protected short CD6USE;
protected short CD7NEW;
protected short CD7USE;
protected short CD8NEW;
protected short CD8USE;
protected short CD9NEW;
protected short CD9USE;
protected short CDHAVE;
protected int CDNUXP;
protected short CDUSE10;
protected short CDUSE11;
protected byte CDUSE5;
protected byte CDUSE7;
protected double CONTR;
protected double DEDUC;
protected double EQ_MOECD;
protected double FIEQFCA;
protected double FIEQFCB;
protected double FIHHMB;
protected short FIHHMBI;
protected double FIHHMI;
protected short FIHHMII;
protected double FIHHML;
protected short FIHHMLI;
protected short FIHHMNI;
protected double FIHHMNL;
protected double FIHHMP;
protected short FIHHMPI;
protected double FIHHMT;
protected byte FIHHMTI;
protected double FIHHYB;
protected short FIHHYBI;
protected double FIHHYI;
protected short FIHHYII;
protected double FIHHYL;
protected short FIHHYLI;
protected short FIHHYNI;
protected double FIHHYNL;
protected double FIHHYP;
protected short FIHHYPI;
protected double FIHHYR;
protected short FIHHYRI;
protected double FIHHYT;
protected byte FIHHYTI;
protected short FIHMNLI;
protected byte GASUSE;
protected byte GASWAY;
protected double GRPAY;
protected double HCOST;
protected double HDEMP;
protected double HDSE;
protected short HEATYP;
protected double HHB;
protected short HHDC;
protected double HHI;
protected short HHMOVE;
protected double HHNETDE;
protected double HHNETDE2;
protected double HHNETI;
protected double HHNYRDE;
protected double HHNYRDE2;
protected double HHP;
protected double HHT;
protected short HHTYPE;
protected double HHYNETI;
protected double HHYRB;
protected short HHYRBI;
protected double HHYRI;
protected short HHYRII;
protected double HHYRLG;
protected double HHYRLN;
protected short HHYRLNI;
protected double HHYRP;
protected short HHYRPI;
protected double HHYRT;
protected short HHYRTI;
protected int HID;
protected double HMAINT;
protected byte HSIP;
protected int HSIPXP;
protected byte HSIVW1;
protected short HSOWND_BH;
protected short HSOWR111;
protected short HSOWR1_BH;
protected short HSOWR2_BH;
protected short HSOWRP;
protected short HSROOM;
protected short HSTYPE;
protected short HSYR0;
protected short HSYR04_BH;
protected short INTDATEY;
protected short IVFHO;
protected short IVFHO_BH;
protected short IVH0;
protected short IVH11;
protected short IVH1_BH;
protected short IVH2_BH;
protected short IVH3_BH;
protected byte LECWAY;
protected double LOCTAX;
protected short MGEXTRA;
protected short MGHAVE;
protected int MGNEW;
protected short MGNEWI;
protected int MGOLD;
protected byte MGSTAT;
protected short MGTYPE_BH;
protected short MGXTY1;
protected short MGXTY1_BH;
protected short MGXTY2;
protected short MGXTY2_BH;
protected short MGXTY3;
protected short MGXTY3_BH;
protected short MGXTY4;
protected short MGXTY4_BH;
protected short MGXTY5_BH;
protected short MGYNOT_BH;
protected short MGYR0;
protected short MGYR04;
protected int MONUM;
protected byte NA75PL;
protected short NCARS_BH;
protected short NCH1618;
protected short NCOUPLE_DV;
protected double NETLAB;
protected double NI;
protected short NWAGE_DV;
protected byte NWED;
protected double OTHLAB;
protected short REGION;
protected short RENT1;
protected short RENT2;
protected short RENT3;
protected short RENT4;
protected short RENT5;
protected short RENT6;
protected short RENTGI;
protected double RENTGW;
protected short RENTG_BH;
protected short RENTHB_BH;
protected short RENTI;
protected short RENTP11;
protected short RENTP1_BH;
protected short RENTP2_BH;
protected double RENTW;
protected double SPEMP;
protected double SPSE;
protected double TAXCR;
protected double TAXGR;
protected double TAXNET;
protected short TENURE_DV;
protected double XHWGHT;
protected short XPFOOD;
protected double XPFUEL;
protected double XPGAS;
protected short XPGASL;
protected byte XPGASLW;
protected double XPGASW;
protected short XPHSD1;
protected short XPHSD2;
protected short XPHSDB_BH;
protected short XPHSDF;
protected double XPHSG;
protected short XPHSGI;
protected double XPHSN;
protected short XPHSNI;
protected double XPLEC;
protected short XPLECL;
protected byte XPLECLW;
protected double XPLECW;
protected short XPMG1;
protected short XPMG2;
protected short XPMG3;
protected short XPMG4;
protected short XPMGI;
protected double XPOIL;
protected short XPOILY;
protected short XPOILY_BH;
protected double YRCONTR;
protected double YRDEDUC;
protected double YRNI;
protected double YRTAXCR;
protected double YRTAXGR;
protected double YRTAXNT;
protected final void initBASEPI(String s) {
if (!s.trim().isEmpty()) {
BASEPI = Double.parseDouble(s);
} else {
BASEPI = Double.NaN;
}
}

protected final void initBHCIND(String s) {
if (!s.trim().isEmpty()) {
BHCIND = Double.parseDouble(s);
} else {
BHCIND = Double.NaN;
}
}

protected final void initBHCINDA(String s) {
if (!s.trim().isEmpty()) {
BHCINDA = Double.parseDouble(s);
} else {
BHCINDA = Double.NaN;
}
}

protected final void initCD1NEW(String s) {
if (!s.trim().isEmpty()) {
CD1NEW = Short.parseShort(s);
} else {
CD1NEW = Short.MIN_VALUE;
}
}

protected final void initCD1USE(String s) {
if (!s.trim().isEmpty()) {
CD1USE = Short.parseShort(s);
} else {
CD1USE = Short.MIN_VALUE;
}
}

protected final void initCD2NEW(String s) {
if (!s.trim().isEmpty()) {
CD2NEW = Short.parseShort(s);
} else {
CD2NEW = Short.MIN_VALUE;
}
}

protected final void initCD2USE(String s) {
if (!s.trim().isEmpty()) {
CD2USE = Short.parseShort(s);
} else {
CD2USE = Short.MIN_VALUE;
}
}

protected final void initCD3NEW(String s) {
if (!s.trim().isEmpty()) {
CD3NEW = Byte.parseByte(s);
} else {
CD3NEW = Byte.MIN_VALUE;
}
}

protected final void initCD3USE(String s) {
if (!s.trim().isEmpty()) {
CD3USE = Byte.parseByte(s);
} else {
CD3USE = Byte.MIN_VALUE;
}
}

protected final void initCD4NEW(String s) {
if (!s.trim().isEmpty()) {
CD4NEW = Short.parseShort(s);
} else {
CD4NEW = Short.MIN_VALUE;
}
}

protected final void initCD4USE(String s) {
if (!s.trim().isEmpty()) {
CD4USE = Short.parseShort(s);
} else {
CD4USE = Short.MIN_VALUE;
}
}

protected final void initCD5NEW(String s) {
if (!s.trim().isEmpty()) {
CD5NEW = Byte.parseByte(s);
} else {
CD5NEW = Byte.MIN_VALUE;
}
}

protected final void initCD5USE(String s) {
if (!s.trim().isEmpty()) {
CD5USE = Byte.parseByte(s);
} else {
CD5USE = Byte.MIN_VALUE;
}
}

protected final void initCD6NEW(String s) {
if (!s.trim().isEmpty()) {
CD6NEW = Short.parseShort(s);
} else {
CD6NEW = Short.MIN_VALUE;
}
}

protected final void initCD6USE(String s) {
if (!s.trim().isEmpty()) {
CD6USE = Short.parseShort(s);
} else {
CD6USE = Short.MIN_VALUE;
}
}

protected final void initCD7NEW(String s) {
if (!s.trim().isEmpty()) {
CD7NEW = Short.parseShort(s);
} else {
CD7NEW = Short.MIN_VALUE;
}
}

protected final void initCD7USE(String s) {
if (!s.trim().isEmpty()) {
CD7USE = Short.parseShort(s);
} else {
CD7USE = Short.MIN_VALUE;
}
}

protected final void initCD8NEW(String s) {
if (!s.trim().isEmpty()) {
CD8NEW = Short.parseShort(s);
} else {
CD8NEW = Short.MIN_VALUE;
}
}

protected final void initCD8USE(String s) {
if (!s.trim().isEmpty()) {
CD8USE = Short.parseShort(s);
} else {
CD8USE = Short.MIN_VALUE;
}
}

protected final void initCD9NEW(String s) {
if (!s.trim().isEmpty()) {
CD9NEW = Short.parseShort(s);
} else {
CD9NEW = Short.MIN_VALUE;
}
}

protected final void initCD9USE(String s) {
if (!s.trim().isEmpty()) {
CD9USE = Short.parseShort(s);
} else {
CD9USE = Short.MIN_VALUE;
}
}

protected final void initCDHAVE(String s) {
if (!s.trim().isEmpty()) {
CDHAVE = Short.parseShort(s);
} else {
CDHAVE = Short.MIN_VALUE;
}
}

protected final void initCDNUXP(String s) {
if (!s.trim().isEmpty()) {
CDNUXP = Integer.parseInt(s);
} else {
CDNUXP = Integer.MIN_VALUE;
}
}

protected final void initCDUSE10(String s) {
if (!s.trim().isEmpty()) {
CDUSE10 = Short.parseShort(s);
} else {
CDUSE10 = Short.MIN_VALUE;
}
}

protected final void initCDUSE11(String s) {
if (!s.trim().isEmpty()) {
CDUSE11 = Short.parseShort(s);
} else {
CDUSE11 = Short.MIN_VALUE;
}
}

protected final void initCDUSE5(String s) {
if (!s.trim().isEmpty()) {
CDUSE5 = Byte.parseByte(s);
} else {
CDUSE5 = Byte.MIN_VALUE;
}
}

protected final void initCDUSE7(String s) {
if (!s.trim().isEmpty()) {
CDUSE7 = Byte.parseByte(s);
} else {
CDUSE7 = Byte.MIN_VALUE;
}
}

protected final void initCONTR(String s) {
if (!s.trim().isEmpty()) {
CONTR = Double.parseDouble(s);
} else {
CONTR = Double.NaN;
}
}

protected final void initDEDUC(String s) {
if (!s.trim().isEmpty()) {
DEDUC = Double.parseDouble(s);
} else {
DEDUC = Double.NaN;
}
}

protected final void initEQ_MOECD(String s) {
if (!s.trim().isEmpty()) {
EQ_MOECD = Double.parseDouble(s);
} else {
EQ_MOECD = Double.NaN;
}
}

protected final void initFIEQFCA(String s) {
if (!s.trim().isEmpty()) {
FIEQFCA = Double.parseDouble(s);
} else {
FIEQFCA = Double.NaN;
}
}

protected final void initFIEQFCB(String s) {
if (!s.trim().isEmpty()) {
FIEQFCB = Double.parseDouble(s);
} else {
FIEQFCB = Double.NaN;
}
}

protected final void initFIHHMB(String s) {
if (!s.trim().isEmpty()) {
FIHHMB = Double.parseDouble(s);
} else {
FIHHMB = Double.NaN;
}
}

protected final void initFIHHMBI(String s) {
if (!s.trim().isEmpty()) {
FIHHMBI = Short.parseShort(s);
} else {
FIHHMBI = Short.MIN_VALUE;
}
}

protected final void initFIHHMI(String s) {
if (!s.trim().isEmpty()) {
FIHHMI = Double.parseDouble(s);
} else {
FIHHMI = Double.NaN;
}
}

protected final void initFIHHMII(String s) {
if (!s.trim().isEmpty()) {
FIHHMII = Short.parseShort(s);
} else {
FIHHMII = Short.MIN_VALUE;
}
}

protected final void initFIHHML(String s) {
if (!s.trim().isEmpty()) {
FIHHML = Double.parseDouble(s);
} else {
FIHHML = Double.NaN;
}
}

protected final void initFIHHMLI(String s) {
if (!s.trim().isEmpty()) {
FIHHMLI = Short.parseShort(s);
} else {
FIHHMLI = Short.MIN_VALUE;
}
}

protected final void initFIHHMNI(String s) {
if (!s.trim().isEmpty()) {
FIHHMNI = Short.parseShort(s);
} else {
FIHHMNI = Short.MIN_VALUE;
}
}

protected final void initFIHHMNL(String s) {
if (!s.trim().isEmpty()) {
FIHHMNL = Double.parseDouble(s);
} else {
FIHHMNL = Double.NaN;
}
}

protected final void initFIHHMP(String s) {
if (!s.trim().isEmpty()) {
FIHHMP = Double.parseDouble(s);
} else {
FIHHMP = Double.NaN;
}
}

protected final void initFIHHMPI(String s) {
if (!s.trim().isEmpty()) {
FIHHMPI = Short.parseShort(s);
} else {
FIHHMPI = Short.MIN_VALUE;
}
}

protected final void initFIHHMT(String s) {
if (!s.trim().isEmpty()) {
FIHHMT = Double.parseDouble(s);
} else {
FIHHMT = Double.NaN;
}
}

protected final void initFIHHMTI(String s) {
if (!s.trim().isEmpty()) {
FIHHMTI = Byte.parseByte(s);
} else {
FIHHMTI = Byte.MIN_VALUE;
}
}

protected final void initFIHHYB(String s) {
if (!s.trim().isEmpty()) {
FIHHYB = Double.parseDouble(s);
} else {
FIHHYB = Double.NaN;
}
}

protected final void initFIHHYBI(String s) {
if (!s.trim().isEmpty()) {
FIHHYBI = Short.parseShort(s);
} else {
FIHHYBI = Short.MIN_VALUE;
}
}

protected final void initFIHHYI(String s) {
if (!s.trim().isEmpty()) {
FIHHYI = Double.parseDouble(s);
} else {
FIHHYI = Double.NaN;
}
}

protected final void initFIHHYII(String s) {
if (!s.trim().isEmpty()) {
FIHHYII = Short.parseShort(s);
} else {
FIHHYII = Short.MIN_VALUE;
}
}

protected final void initFIHHYL(String s) {
if (!s.trim().isEmpty()) {
FIHHYL = Double.parseDouble(s);
} else {
FIHHYL = Double.NaN;
}
}

protected final void initFIHHYLI(String s) {
if (!s.trim().isEmpty()) {
FIHHYLI = Short.parseShort(s);
} else {
FIHHYLI = Short.MIN_VALUE;
}
}

protected final void initFIHHYNI(String s) {
if (!s.trim().isEmpty()) {
FIHHYNI = Short.parseShort(s);
} else {
FIHHYNI = Short.MIN_VALUE;
}
}

protected final void initFIHHYNL(String s) {
if (!s.trim().isEmpty()) {
FIHHYNL = Double.parseDouble(s);
} else {
FIHHYNL = Double.NaN;
}
}

protected final void initFIHHYP(String s) {
if (!s.trim().isEmpty()) {
FIHHYP = Double.parseDouble(s);
} else {
FIHHYP = Double.NaN;
}
}

protected final void initFIHHYPI(String s) {
if (!s.trim().isEmpty()) {
FIHHYPI = Short.parseShort(s);
} else {
FIHHYPI = Short.MIN_VALUE;
}
}

protected final void initFIHHYR(String s) {
if (!s.trim().isEmpty()) {
FIHHYR = Double.parseDouble(s);
} else {
FIHHYR = Double.NaN;
}
}

protected final void initFIHHYRI(String s) {
if (!s.trim().isEmpty()) {
FIHHYRI = Short.parseShort(s);
} else {
FIHHYRI = Short.MIN_VALUE;
}
}

protected final void initFIHHYT(String s) {
if (!s.trim().isEmpty()) {
FIHHYT = Double.parseDouble(s);
} else {
FIHHYT = Double.NaN;
}
}

protected final void initFIHHYTI(String s) {
if (!s.trim().isEmpty()) {
FIHHYTI = Byte.parseByte(s);
} else {
FIHHYTI = Byte.MIN_VALUE;
}
}

protected final void initFIHMNLI(String s) {
if (!s.trim().isEmpty()) {
FIHMNLI = Short.parseShort(s);
} else {
FIHMNLI = Short.MIN_VALUE;
}
}

protected final void initGASUSE(String s) {
if (!s.trim().isEmpty()) {
GASUSE = Byte.parseByte(s);
} else {
GASUSE = Byte.MIN_VALUE;
}
}

protected final void initGASWAY(String s) {
if (!s.trim().isEmpty()) {
GASWAY = Byte.parseByte(s);
} else {
GASWAY = Byte.MIN_VALUE;
}
}

protected final void initGRPAY(String s) {
if (!s.trim().isEmpty()) {
GRPAY = Double.parseDouble(s);
} else {
GRPAY = Double.NaN;
}
}

protected final void initHCOST(String s) {
if (!s.trim().isEmpty()) {
HCOST = Double.parseDouble(s);
} else {
HCOST = Double.NaN;
}
}

protected final void initHDEMP(String s) {
if (!s.trim().isEmpty()) {
HDEMP = Double.parseDouble(s);
} else {
HDEMP = Double.NaN;
}
}

protected final void initHDSE(String s) {
if (!s.trim().isEmpty()) {
HDSE = Double.parseDouble(s);
} else {
HDSE = Double.NaN;
}
}

protected final void initHEATYP(String s) {
if (!s.trim().isEmpty()) {
HEATYP = Short.parseShort(s);
} else {
HEATYP = Short.MIN_VALUE;
}
}

protected final void initHHB(String s) {
if (!s.trim().isEmpty()) {
HHB = Double.parseDouble(s);
} else {
HHB = Double.NaN;
}
}

protected final void initHHDC(String s) {
if (!s.trim().isEmpty()) {
HHDC = Short.parseShort(s);
} else {
HHDC = Short.MIN_VALUE;
}
}

protected final void initHHI(String s) {
if (!s.trim().isEmpty()) {
HHI = Double.parseDouble(s);
} else {
HHI = Double.NaN;
}
}

protected final void initHHMOVE(String s) {
if (!s.trim().isEmpty()) {
HHMOVE = Short.parseShort(s);
} else {
HHMOVE = Short.MIN_VALUE;
}
}

protected final void initHHNETDE(String s) {
if (!s.trim().isEmpty()) {
HHNETDE = Double.parseDouble(s);
} else {
HHNETDE = Double.NaN;
}
}

protected final void initHHNETDE2(String s) {
if (!s.trim().isEmpty()) {
HHNETDE2 = Double.parseDouble(s);
} else {
HHNETDE2 = Double.NaN;
}
}

protected final void initHHNETI(String s) {
if (!s.trim().isEmpty()) {
HHNETI = Double.parseDouble(s);
} else {
HHNETI = Double.NaN;
}
}

protected final void initHHNYRDE(String s) {
if (!s.trim().isEmpty()) {
HHNYRDE = Double.parseDouble(s);
} else {
HHNYRDE = Double.NaN;
}
}

protected final void initHHNYRDE2(String s) {
if (!s.trim().isEmpty()) {
HHNYRDE2 = Double.parseDouble(s);
} else {
HHNYRDE2 = Double.NaN;
}
}

protected final void initHHP(String s) {
if (!s.trim().isEmpty()) {
HHP = Double.parseDouble(s);
} else {
HHP = Double.NaN;
}
}

protected final void initHHT(String s) {
if (!s.trim().isEmpty()) {
HHT = Double.parseDouble(s);
} else {
HHT = Double.NaN;
}
}

protected final void initHHTYPE(String s) {
if (!s.trim().isEmpty()) {
HHTYPE = Short.parseShort(s);
} else {
HHTYPE = Short.MIN_VALUE;
}
}

protected final void initHHYNETI(String s) {
if (!s.trim().isEmpty()) {
HHYNETI = Double.parseDouble(s);
} else {
HHYNETI = Double.NaN;
}
}

protected final void initHHYRB(String s) {
if (!s.trim().isEmpty()) {
HHYRB = Double.parseDouble(s);
} else {
HHYRB = Double.NaN;
}
}

protected final void initHHYRBI(String s) {
if (!s.trim().isEmpty()) {
HHYRBI = Short.parseShort(s);
} else {
HHYRBI = Short.MIN_VALUE;
}
}

protected final void initHHYRI(String s) {
if (!s.trim().isEmpty()) {
HHYRI = Double.parseDouble(s);
} else {
HHYRI = Double.NaN;
}
}

protected final void initHHYRII(String s) {
if (!s.trim().isEmpty()) {
HHYRII = Short.parseShort(s);
} else {
HHYRII = Short.MIN_VALUE;
}
}

protected final void initHHYRLG(String s) {
if (!s.trim().isEmpty()) {
HHYRLG = Double.parseDouble(s);
} else {
HHYRLG = Double.NaN;
}
}

protected final void initHHYRLN(String s) {
if (!s.trim().isEmpty()) {
HHYRLN = Double.parseDouble(s);
} else {
HHYRLN = Double.NaN;
}
}

protected final void initHHYRLNI(String s) {
if (!s.trim().isEmpty()) {
HHYRLNI = Short.parseShort(s);
} else {
HHYRLNI = Short.MIN_VALUE;
}
}

protected final void initHHYRP(String s) {
if (!s.trim().isEmpty()) {
HHYRP = Double.parseDouble(s);
} else {
HHYRP = Double.NaN;
}
}

protected final void initHHYRPI(String s) {
if (!s.trim().isEmpty()) {
HHYRPI = Short.parseShort(s);
} else {
HHYRPI = Short.MIN_VALUE;
}
}

protected final void initHHYRT(String s) {
if (!s.trim().isEmpty()) {
HHYRT = Double.parseDouble(s);
} else {
HHYRT = Double.NaN;
}
}

protected final void initHHYRTI(String s) {
if (!s.trim().isEmpty()) {
HHYRTI = Short.parseShort(s);
} else {
HHYRTI = Short.MIN_VALUE;
}
}

protected final void initHID(String s) {
if (!s.trim().isEmpty()) {
HID = Integer.parseInt(s);
} else {
HID = Integer.MIN_VALUE;
}
}

protected final void initHMAINT(String s) {
if (!s.trim().isEmpty()) {
HMAINT = Double.parseDouble(s);
} else {
HMAINT = Double.NaN;
}
}

protected final void initHSIP(String s) {
if (!s.trim().isEmpty()) {
HSIP = Byte.parseByte(s);
} else {
HSIP = Byte.MIN_VALUE;
}
}

protected final void initHSIPXP(String s) {
if (!s.trim().isEmpty()) {
HSIPXP = Integer.parseInt(s);
} else {
HSIPXP = Integer.MIN_VALUE;
}
}

protected final void initHSIVW1(String s) {
if (!s.trim().isEmpty()) {
HSIVW1 = Byte.parseByte(s);
} else {
HSIVW1 = Byte.MIN_VALUE;
}
}

protected final void initHSOWND_BH(String s) {
if (!s.trim().isEmpty()) {
HSOWND_BH = Short.parseShort(s);
} else {
HSOWND_BH = Short.MIN_VALUE;
}
}

protected final void initHSOWR111(String s) {
if (!s.trim().isEmpty()) {
HSOWR111 = Short.parseShort(s);
} else {
HSOWR111 = Short.MIN_VALUE;
}
}

protected final void initHSOWR1_BH(String s) {
if (!s.trim().isEmpty()) {
HSOWR1_BH = Short.parseShort(s);
} else {
HSOWR1_BH = Short.MIN_VALUE;
}
}

protected final void initHSOWR2_BH(String s) {
if (!s.trim().isEmpty()) {
HSOWR2_BH = Short.parseShort(s);
} else {
HSOWR2_BH = Short.MIN_VALUE;
}
}

protected final void initHSOWRP(String s) {
if (!s.trim().isEmpty()) {
HSOWRP = Short.parseShort(s);
} else {
HSOWRP = Short.MIN_VALUE;
}
}

protected final void initHSROOM(String s) {
if (!s.trim().isEmpty()) {
HSROOM = Short.parseShort(s);
} else {
HSROOM = Short.MIN_VALUE;
}
}

protected final void initHSTYPE(String s) {
if (!s.trim().isEmpty()) {
HSTYPE = Short.parseShort(s);
} else {
HSTYPE = Short.MIN_VALUE;
}
}

protected final void initHSYR0(String s) {
if (!s.trim().isEmpty()) {
HSYR0 = Short.parseShort(s);
} else {
HSYR0 = Short.MIN_VALUE;
}
}

protected final void initHSYR04_BH(String s) {
if (!s.trim().isEmpty()) {
HSYR04_BH = Short.parseShort(s);
} else {
HSYR04_BH = Short.MIN_VALUE;
}
}

protected final void initINTDATEY(String s) {
if (!s.trim().isEmpty()) {
INTDATEY = Short.parseShort(s);
} else {
INTDATEY = Short.MIN_VALUE;
}
}

protected final void initIVFHO(String s) {
if (!s.trim().isEmpty()) {
IVFHO = Short.parseShort(s);
} else {
IVFHO = Short.MIN_VALUE;
}
}

protected final void initIVFHO_BH(String s) {
if (!s.trim().isEmpty()) {
IVFHO_BH = Short.parseShort(s);
} else {
IVFHO_BH = Short.MIN_VALUE;
}
}

protected final void initIVH0(String s) {
if (!s.trim().isEmpty()) {
IVH0 = Short.parseShort(s);
} else {
IVH0 = Short.MIN_VALUE;
}
}

protected final void initIVH11(String s) {
if (!s.trim().isEmpty()) {
IVH11 = Short.parseShort(s);
} else {
IVH11 = Short.MIN_VALUE;
}
}

protected final void initIVH1_BH(String s) {
if (!s.trim().isEmpty()) {
IVH1_BH = Short.parseShort(s);
} else {
IVH1_BH = Short.MIN_VALUE;
}
}

protected final void initIVH2_BH(String s) {
if (!s.trim().isEmpty()) {
IVH2_BH = Short.parseShort(s);
} else {
IVH2_BH = Short.MIN_VALUE;
}
}

protected final void initIVH3_BH(String s) {
if (!s.trim().isEmpty()) {
IVH3_BH = Short.parseShort(s);
} else {
IVH3_BH = Short.MIN_VALUE;
}
}

protected final void initLECWAY(String s) {
if (!s.trim().isEmpty()) {
LECWAY = Byte.parseByte(s);
} else {
LECWAY = Byte.MIN_VALUE;
}
}

protected final void initLOCTAX(String s) {
if (!s.trim().isEmpty()) {
LOCTAX = Double.parseDouble(s);
} else {
LOCTAX = Double.NaN;
}
}

protected final void initMGEXTRA(String s) {
if (!s.trim().isEmpty()) {
MGEXTRA = Short.parseShort(s);
} else {
MGEXTRA = Short.MIN_VALUE;
}
}

protected final void initMGHAVE(String s) {
if (!s.trim().isEmpty()) {
MGHAVE = Short.parseShort(s);
} else {
MGHAVE = Short.MIN_VALUE;
}
}

protected final void initMGNEW(String s) {
if (!s.trim().isEmpty()) {
MGNEW = Integer.parseInt(s);
} else {
MGNEW = Integer.MIN_VALUE;
}
}

protected final void initMGNEWI(String s) {
if (!s.trim().isEmpty()) {
MGNEWI = Short.parseShort(s);
} else {
MGNEWI = Short.MIN_VALUE;
}
}

protected final void initMGOLD(String s) {
if (!s.trim().isEmpty()) {
MGOLD = Integer.parseInt(s);
} else {
MGOLD = Integer.MIN_VALUE;
}
}

protected final void initMGSTAT(String s) {
if (!s.trim().isEmpty()) {
MGSTAT = Byte.parseByte(s);
} else {
MGSTAT = Byte.MIN_VALUE;
}
}

protected final void initMGTYPE_BH(String s) {
if (!s.trim().isEmpty()) {
MGTYPE_BH = Short.parseShort(s);
} else {
MGTYPE_BH = Short.MIN_VALUE;
}
}

protected final void initMGXTY1(String s) {
if (!s.trim().isEmpty()) {
MGXTY1 = Short.parseShort(s);
} else {
MGXTY1 = Short.MIN_VALUE;
}
}

protected final void initMGXTY1_BH(String s) {
if (!s.trim().isEmpty()) {
MGXTY1_BH = Short.parseShort(s);
} else {
MGXTY1_BH = Short.MIN_VALUE;
}
}

protected final void initMGXTY2(String s) {
if (!s.trim().isEmpty()) {
MGXTY2 = Short.parseShort(s);
} else {
MGXTY2 = Short.MIN_VALUE;
}
}

protected final void initMGXTY2_BH(String s) {
if (!s.trim().isEmpty()) {
MGXTY2_BH = Short.parseShort(s);
} else {
MGXTY2_BH = Short.MIN_VALUE;
}
}

protected final void initMGXTY3(String s) {
if (!s.trim().isEmpty()) {
MGXTY3 = Short.parseShort(s);
} else {
MGXTY3 = Short.MIN_VALUE;
}
}

protected final void initMGXTY3_BH(String s) {
if (!s.trim().isEmpty()) {
MGXTY3_BH = Short.parseShort(s);
} else {
MGXTY3_BH = Short.MIN_VALUE;
}
}

protected final void initMGXTY4(String s) {
if (!s.trim().isEmpty()) {
MGXTY4 = Short.parseShort(s);
} else {
MGXTY4 = Short.MIN_VALUE;
}
}

protected final void initMGXTY4_BH(String s) {
if (!s.trim().isEmpty()) {
MGXTY4_BH = Short.parseShort(s);
} else {
MGXTY4_BH = Short.MIN_VALUE;
}
}

protected final void initMGXTY5_BH(String s) {
if (!s.trim().isEmpty()) {
MGXTY5_BH = Short.parseShort(s);
} else {
MGXTY5_BH = Short.MIN_VALUE;
}
}

protected final void initMGYNOT_BH(String s) {
if (!s.trim().isEmpty()) {
MGYNOT_BH = Short.parseShort(s);
} else {
MGYNOT_BH = Short.MIN_VALUE;
}
}

protected final void initMGYR0(String s) {
if (!s.trim().isEmpty()) {
MGYR0 = Short.parseShort(s);
} else {
MGYR0 = Short.MIN_VALUE;
}
}

protected final void initMGYR04(String s) {
if (!s.trim().isEmpty()) {
MGYR04 = Short.parseShort(s);
} else {
MGYR04 = Short.MIN_VALUE;
}
}

protected final void initMONUM(String s) {
if (!s.trim().isEmpty()) {
MONUM = Integer.parseInt(s);
} else {
MONUM = Integer.MIN_VALUE;
}
}

protected final void initNA75PL(String s) {
if (!s.trim().isEmpty()) {
NA75PL = Byte.parseByte(s);
} else {
NA75PL = Byte.MIN_VALUE;
}
}

protected final void initNCARS_BH(String s) {
if (!s.trim().isEmpty()) {
NCARS_BH = Short.parseShort(s);
} else {
NCARS_BH = Short.MIN_VALUE;
}
}

protected final void initNCH1618(String s) {
if (!s.trim().isEmpty()) {
NCH1618 = Short.parseShort(s);
} else {
NCH1618 = Short.MIN_VALUE;
}
}

protected final void initNCOUPLE_DV(String s) {
if (!s.trim().isEmpty()) {
NCOUPLE_DV = Short.parseShort(s);
} else {
NCOUPLE_DV = Short.MIN_VALUE;
}
}

protected final void initNETLAB(String s) {
if (!s.trim().isEmpty()) {
NETLAB = Double.parseDouble(s);
} else {
NETLAB = Double.NaN;
}
}

protected final void initNI(String s) {
if (!s.trim().isEmpty()) {
NI = Double.parseDouble(s);
} else {
NI = Double.NaN;
}
}

protected final void initNWAGE_DV(String s) {
if (!s.trim().isEmpty()) {
NWAGE_DV = Short.parseShort(s);
} else {
NWAGE_DV = Short.MIN_VALUE;
}
}

protected final void initNWED(String s) {
if (!s.trim().isEmpty()) {
NWED = Byte.parseByte(s);
} else {
NWED = Byte.MIN_VALUE;
}
}

protected final void initOTHLAB(String s) {
if (!s.trim().isEmpty()) {
OTHLAB = Double.parseDouble(s);
} else {
OTHLAB = Double.NaN;
}
}

protected final void initREGION(String s) {
if (!s.trim().isEmpty()) {
REGION = Short.parseShort(s);
} else {
REGION = Short.MIN_VALUE;
}
}

protected final void initRENT1(String s) {
if (!s.trim().isEmpty()) {
RENT1 = Short.parseShort(s);
} else {
RENT1 = Short.MIN_VALUE;
}
}

protected final void initRENT2(String s) {
if (!s.trim().isEmpty()) {
RENT2 = Short.parseShort(s);
} else {
RENT2 = Short.MIN_VALUE;
}
}

protected final void initRENT3(String s) {
if (!s.trim().isEmpty()) {
RENT3 = Short.parseShort(s);
} else {
RENT3 = Short.MIN_VALUE;
}
}

protected final void initRENT4(String s) {
if (!s.trim().isEmpty()) {
RENT4 = Short.parseShort(s);
} else {
RENT4 = Short.MIN_VALUE;
}
}

protected final void initRENT5(String s) {
if (!s.trim().isEmpty()) {
RENT5 = Short.parseShort(s);
} else {
RENT5 = Short.MIN_VALUE;
}
}

protected final void initRENT6(String s) {
if (!s.trim().isEmpty()) {
RENT6 = Short.parseShort(s);
} else {
RENT6 = Short.MIN_VALUE;
}
}

protected final void initRENTGI(String s) {
if (!s.trim().isEmpty()) {
RENTGI = Short.parseShort(s);
} else {
RENTGI = Short.MIN_VALUE;
}
}

protected final void initRENTGW(String s) {
if (!s.trim().isEmpty()) {
RENTGW = Double.parseDouble(s);
} else {
RENTGW = Double.NaN;
}
}

protected final void initRENTG_BH(String s) {
if (!s.trim().isEmpty()) {
RENTG_BH = Short.parseShort(s);
} else {
RENTG_BH = Short.MIN_VALUE;
}
}

protected final void initRENTHB_BH(String s) {
if (!s.trim().isEmpty()) {
RENTHB_BH = Short.parseShort(s);
} else {
RENTHB_BH = Short.MIN_VALUE;
}
}

protected final void initRENTI(String s) {
if (!s.trim().isEmpty()) {
RENTI = Short.parseShort(s);
} else {
RENTI = Short.MIN_VALUE;
}
}

protected final void initRENTP11(String s) {
if (!s.trim().isEmpty()) {
RENTP11 = Short.parseShort(s);
} else {
RENTP11 = Short.MIN_VALUE;
}
}

protected final void initRENTP1_BH(String s) {
if (!s.trim().isEmpty()) {
RENTP1_BH = Short.parseShort(s);
} else {
RENTP1_BH = Short.MIN_VALUE;
}
}

protected final void initRENTP2_BH(String s) {
if (!s.trim().isEmpty()) {
RENTP2_BH = Short.parseShort(s);
} else {
RENTP2_BH = Short.MIN_VALUE;
}
}

protected final void initRENTW(String s) {
if (!s.trim().isEmpty()) {
RENTW = Double.parseDouble(s);
} else {
RENTW = Double.NaN;
}
}

protected final void initSPEMP(String s) {
if (!s.trim().isEmpty()) {
SPEMP = Double.parseDouble(s);
} else {
SPEMP = Double.NaN;
}
}

protected final void initSPSE(String s) {
if (!s.trim().isEmpty()) {
SPSE = Double.parseDouble(s);
} else {
SPSE = Double.NaN;
}
}

protected final void initTAXCR(String s) {
if (!s.trim().isEmpty()) {
TAXCR = Double.parseDouble(s);
} else {
TAXCR = Double.NaN;
}
}

protected final void initTAXGR(String s) {
if (!s.trim().isEmpty()) {
TAXGR = Double.parseDouble(s);
} else {
TAXGR = Double.NaN;
}
}

protected final void initTAXNET(String s) {
if (!s.trim().isEmpty()) {
TAXNET = Double.parseDouble(s);
} else {
TAXNET = Double.NaN;
}
}

protected final void initTENURE_DV(String s) {
if (!s.trim().isEmpty()) {
TENURE_DV = Short.parseShort(s);
} else {
TENURE_DV = Short.MIN_VALUE;
}
}

protected final void initXHWGHT(String s) {
if (!s.trim().isEmpty()) {
XHWGHT = Double.parseDouble(s);
} else {
XHWGHT = Double.NaN;
}
}

protected final void initXPFOOD(String s) {
if (!s.trim().isEmpty()) {
XPFOOD = Short.parseShort(s);
} else {
XPFOOD = Short.MIN_VALUE;
}
}

protected final void initXPFUEL(String s) {
if (!s.trim().isEmpty()) {
XPFUEL = Double.parseDouble(s);
} else {
XPFUEL = Double.NaN;
}
}

protected final void initXPGAS(String s) {
if (!s.trim().isEmpty()) {
XPGAS = Double.parseDouble(s);
} else {
XPGAS = Double.NaN;
}
}

protected final void initXPGASL(String s) {
if (!s.trim().isEmpty()) {
XPGASL = Short.parseShort(s);
} else {
XPGASL = Short.MIN_VALUE;
}
}

protected final void initXPGASLW(String s) {
if (!s.trim().isEmpty()) {
XPGASLW = Byte.parseByte(s);
} else {
XPGASLW = Byte.MIN_VALUE;
}
}

protected final void initXPGASW(String s) {
if (!s.trim().isEmpty()) {
XPGASW = Double.parseDouble(s);
} else {
XPGASW = Double.NaN;
}
}

protected final void initXPHSD1(String s) {
if (!s.trim().isEmpty()) {
XPHSD1 = Short.parseShort(s);
} else {
XPHSD1 = Short.MIN_VALUE;
}
}

protected final void initXPHSD2(String s) {
if (!s.trim().isEmpty()) {
XPHSD2 = Short.parseShort(s);
} else {
XPHSD2 = Short.MIN_VALUE;
}
}

protected final void initXPHSDB_BH(String s) {
if (!s.trim().isEmpty()) {
XPHSDB_BH = Short.parseShort(s);
} else {
XPHSDB_BH = Short.MIN_VALUE;
}
}

protected final void initXPHSDF(String s) {
if (!s.trim().isEmpty()) {
XPHSDF = Short.parseShort(s);
} else {
XPHSDF = Short.MIN_VALUE;
}
}

protected final void initXPHSG(String s) {
if (!s.trim().isEmpty()) {
XPHSG = Double.parseDouble(s);
} else {
XPHSG = Double.NaN;
}
}

protected final void initXPHSGI(String s) {
if (!s.trim().isEmpty()) {
XPHSGI = Short.parseShort(s);
} else {
XPHSGI = Short.MIN_VALUE;
}
}

protected final void initXPHSN(String s) {
if (!s.trim().isEmpty()) {
XPHSN = Double.parseDouble(s);
} else {
XPHSN = Double.NaN;
}
}

protected final void initXPHSNI(String s) {
if (!s.trim().isEmpty()) {
XPHSNI = Short.parseShort(s);
} else {
XPHSNI = Short.MIN_VALUE;
}
}

protected final void initXPLEC(String s) {
if (!s.trim().isEmpty()) {
XPLEC = Double.parseDouble(s);
} else {
XPLEC = Double.NaN;
}
}

protected final void initXPLECL(String s) {
if (!s.trim().isEmpty()) {
XPLECL = Short.parseShort(s);
} else {
XPLECL = Short.MIN_VALUE;
}
}

protected final void initXPLECLW(String s) {
if (!s.trim().isEmpty()) {
XPLECLW = Byte.parseByte(s);
} else {
XPLECLW = Byte.MIN_VALUE;
}
}

protected final void initXPLECW(String s) {
if (!s.trim().isEmpty()) {
XPLECW = Double.parseDouble(s);
} else {
XPLECW = Double.NaN;
}
}

protected final void initXPMG1(String s) {
if (!s.trim().isEmpty()) {
XPMG1 = Short.parseShort(s);
} else {
XPMG1 = Short.MIN_VALUE;
}
}

protected final void initXPMG2(String s) {
if (!s.trim().isEmpty()) {
XPMG2 = Short.parseShort(s);
} else {
XPMG2 = Short.MIN_VALUE;
}
}

protected final void initXPMG3(String s) {
if (!s.trim().isEmpty()) {
XPMG3 = Short.parseShort(s);
} else {
XPMG3 = Short.MIN_VALUE;
}
}

protected final void initXPMG4(String s) {
if (!s.trim().isEmpty()) {
XPMG4 = Short.parseShort(s);
} else {
XPMG4 = Short.MIN_VALUE;
}
}

protected final void initXPMGI(String s) {
if (!s.trim().isEmpty()) {
XPMGI = Short.parseShort(s);
} else {
XPMGI = Short.MIN_VALUE;
}
}

protected final void initXPOIL(String s) {
if (!s.trim().isEmpty()) {
XPOIL = Double.parseDouble(s);
} else {
XPOIL = Double.NaN;
}
}

protected final void initXPOILY(String s) {
if (!s.trim().isEmpty()) {
XPOILY = Short.parseShort(s);
} else {
XPOILY = Short.MIN_VALUE;
}
}

protected final void initXPOILY_BH(String s) {
if (!s.trim().isEmpty()) {
XPOILY_BH = Short.parseShort(s);
} else {
XPOILY_BH = Short.MIN_VALUE;
}
}

protected final void initYRCONTR(String s) {
if (!s.trim().isEmpty()) {
YRCONTR = Double.parseDouble(s);
} else {
YRCONTR = Double.NaN;
}
}

protected final void initYRDEDUC(String s) {
if (!s.trim().isEmpty()) {
YRDEDUC = Double.parseDouble(s);
} else {
YRDEDUC = Double.NaN;
}
}

protected final void initYRNI(String s) {
if (!s.trim().isEmpty()) {
YRNI = Double.parseDouble(s);
} else {
YRNI = Double.NaN;
}
}

protected final void initYRTAXCR(String s) {
if (!s.trim().isEmpty()) {
YRTAXCR = Double.parseDouble(s);
} else {
YRTAXCR = Double.NaN;
}
}

protected final void initYRTAXGR(String s) {
if (!s.trim().isEmpty()) {
YRTAXGR = Double.parseDouble(s);
} else {
YRTAXGR = Double.NaN;
}
}

protected final void initYRTAXNT(String s) {
if (!s.trim().isEmpty()) {
YRTAXNT = Double.parseDouble(s);
} else {
YRTAXNT = Double.NaN;
}
}

protected double BASEPI() {
return BASEPI;
}

protected double BHCIND() {
return BHCIND;
}

protected double BHCINDA() {
return BHCINDA;
}

public short getCD1NEW() {
return CD1NEW;
}

public short getCD1USE() {
return CD1USE;
}

public short getCD2NEW() {
return CD2NEW;
}

public short getCD2USE() {
return CD2USE;
}

public byte getCD3NEW() {
return CD3NEW;
}

public byte getCD3USE() {
return CD3USE;
}

public short getCD4NEW() {
return CD4NEW;
}

public short getCD4USE() {
return CD4USE;
}

public byte getCD5NEW() {
return CD5NEW;
}

public byte getCD5USE() {
return CD5USE;
}

public short getCD6NEW() {
return CD6NEW;
}

public short getCD6USE() {
return CD6USE;
}

public short getCD7NEW() {
return CD7NEW;
}

public short getCD7USE() {
return CD7USE;
}

public short getCD8NEW() {
return CD8NEW;
}

public short getCD8USE() {
return CD8USE;
}

public short getCD9NEW() {
return CD9NEW;
}

public short getCD9USE() {
return CD9USE;
}

public short getCDHAVE() {
return CDHAVE;
}

public int getCDNUXP() {
return CDNUXP;
}

public short getCDUSE10() {
return CDUSE10;
}

public short getCDUSE11() {
return CDUSE11;
}

public byte getCDUSE5() {
return CDUSE5;
}

public byte getCDUSE7() {
return CDUSE7;
}

protected double CONTR() {
return CONTR;
}

protected double DEDUC() {
return DEDUC;
}

protected double EQ_MOECD() {
return EQ_MOECD;
}

protected double FIEQFCA() {
return FIEQFCA;
}

protected double FIEQFCB() {
return FIEQFCB;
}

protected double FIHHMB() {
return FIHHMB;
}

public short getFIHHMBI() {
return FIHHMBI;
}

protected double FIHHMI() {
return FIHHMI;
}

public short getFIHHMII() {
return FIHHMII;
}

protected double FIHHML() {
return FIHHML;
}

public short getFIHHMLI() {
return FIHHMLI;
}

public short getFIHHMNI() {
return FIHHMNI;
}

protected double FIHHMNL() {
return FIHHMNL;
}

protected double FIHHMP() {
return FIHHMP;
}

public short getFIHHMPI() {
return FIHHMPI;
}

protected double FIHHMT() {
return FIHHMT;
}

public byte getFIHHMTI() {
return FIHHMTI;
}

protected double FIHHYB() {
return FIHHYB;
}

public short getFIHHYBI() {
return FIHHYBI;
}

protected double FIHHYI() {
return FIHHYI;
}

public short getFIHHYII() {
return FIHHYII;
}

protected double FIHHYL() {
return FIHHYL;
}

public short getFIHHYLI() {
return FIHHYLI;
}

public short getFIHHYNI() {
return FIHHYNI;
}

protected double FIHHYNL() {
return FIHHYNL;
}

protected double FIHHYP() {
return FIHHYP;
}

public short getFIHHYPI() {
return FIHHYPI;
}

protected double FIHHYR() {
return FIHHYR;
}

public short getFIHHYRI() {
return FIHHYRI;
}

protected double FIHHYT() {
return FIHHYT;
}

public byte getFIHHYTI() {
return FIHHYTI;
}

public short getFIHMNLI() {
return FIHMNLI;
}

public byte getGASUSE() {
return GASUSE;
}

public byte getGASWAY() {
return GASWAY;
}

protected double GRPAY() {
return GRPAY;
}

protected double HCOST() {
return HCOST;
}

protected double HDEMP() {
return HDEMP;
}

protected double HDSE() {
return HDSE;
}

public short getHEATYP() {
return HEATYP;
}

protected double HHB() {
return HHB;
}

public short getHHDC() {
return HHDC;
}

protected double HHI() {
return HHI;
}

public short getHHMOVE() {
return HHMOVE;
}

protected double HHNETDE() {
return HHNETDE;
}

protected double HHNETDE2() {
return HHNETDE2;
}

protected double HHNETI() {
return HHNETI;
}

protected double HHNYRDE() {
return HHNYRDE;
}

protected double HHNYRDE2() {
return HHNYRDE2;
}

protected double HHP() {
return HHP;
}

protected double HHT() {
return HHT;
}

public short getHHTYPE() {
return HHTYPE;
}

protected double HHYNETI() {
return HHYNETI;
}

protected double HHYRB() {
return HHYRB;
}

public short getHHYRBI() {
return HHYRBI;
}

protected double HHYRI() {
return HHYRI;
}

public short getHHYRII() {
return HHYRII;
}

protected double HHYRLG() {
return HHYRLG;
}

protected double HHYRLN() {
return HHYRLN;
}

public short getHHYRLNI() {
return HHYRLNI;
}

protected double HHYRP() {
return HHYRP;
}

public short getHHYRPI() {
return HHYRPI;
}

protected double HHYRT() {
return HHYRT;
}

public short getHHYRTI() {
return HHYRTI;
}

public int getHID() {
return HID;
}

protected double HMAINT() {
return HMAINT;
}

public byte getHSIP() {
return HSIP;
}

public int getHSIPXP() {
return HSIPXP;
}

public byte getHSIVW1() {
return HSIVW1;
}

public short getHSOWND_BH() {
return HSOWND_BH;
}

public short getHSOWR111() {
return HSOWR111;
}

public short getHSOWR1_BH() {
return HSOWR1_BH;
}

public short getHSOWR2_BH() {
return HSOWR2_BH;
}

public short getHSOWRP() {
return HSOWRP;
}

public short getHSROOM() {
return HSROOM;
}

public short getHSTYPE() {
return HSTYPE;
}

public short getHSYR0() {
return HSYR0;
}

public short getHSYR04_BH() {
return HSYR04_BH;
}

public short getINTDATEY() {
return INTDATEY;
}

public short getIVFHO() {
return IVFHO;
}

public short getIVFHO_BH() {
return IVFHO_BH;
}

public short getIVH0() {
return IVH0;
}

public short getIVH11() {
return IVH11;
}

public short getIVH1_BH() {
return IVH1_BH;
}

public short getIVH2_BH() {
return IVH2_BH;
}

public short getIVH3_BH() {
return IVH3_BH;
}

public byte getLECWAY() {
return LECWAY;
}

protected double LOCTAX() {
return LOCTAX;
}

public short getMGEXTRA() {
return MGEXTRA;
}

public short getMGHAVE() {
return MGHAVE;
}

public int getMGNEW() {
return MGNEW;
}

public short getMGNEWI() {
return MGNEWI;
}

public int getMGOLD() {
return MGOLD;
}

public byte getMGSTAT() {
return MGSTAT;
}

public short getMGTYPE_BH() {
return MGTYPE_BH;
}

public short getMGXTY1() {
return MGXTY1;
}

public short getMGXTY1_BH() {
return MGXTY1_BH;
}

public short getMGXTY2() {
return MGXTY2;
}

public short getMGXTY2_BH() {
return MGXTY2_BH;
}

public short getMGXTY3() {
return MGXTY3;
}

public short getMGXTY3_BH() {
return MGXTY3_BH;
}

public short getMGXTY4() {
return MGXTY4;
}

public short getMGXTY4_BH() {
return MGXTY4_BH;
}

public short getMGXTY5_BH() {
return MGXTY5_BH;
}

public short getMGYNOT_BH() {
return MGYNOT_BH;
}

public short getMGYR0() {
return MGYR0;
}

public short getMGYR04() {
return MGYR04;
}

public int getMONUM() {
return MONUM;
}

public byte getNA75PL() {
return NA75PL;
}

public short getNCARS_BH() {
return NCARS_BH;
}

public short getNCH1618() {
return NCH1618;
}

public short getNCOUPLE_DV() {
return NCOUPLE_DV;
}

protected double NETLAB() {
return NETLAB;
}

protected double NI() {
return NI;
}

public short getNWAGE_DV() {
return NWAGE_DV;
}

public byte getNWED() {
return NWED;
}

protected double OTHLAB() {
return OTHLAB;
}

public short getREGION() {
return REGION;
}

public short getRENT1() {
return RENT1;
}

public short getRENT2() {
return RENT2;
}

public short getRENT3() {
return RENT3;
}

public short getRENT4() {
return RENT4;
}

public short getRENT5() {
return RENT5;
}

public short getRENT6() {
return RENT6;
}

public short getRENTGI() {
return RENTGI;
}

protected double RENTGW() {
return RENTGW;
}

public short getRENTG_BH() {
return RENTG_BH;
}

public short getRENTHB_BH() {
return RENTHB_BH;
}

public short getRENTI() {
return RENTI;
}

public short getRENTP11() {
return RENTP11;
}

public short getRENTP1_BH() {
return RENTP1_BH;
}

public short getRENTP2_BH() {
return RENTP2_BH;
}

protected double RENTW() {
return RENTW;
}

protected double SPEMP() {
return SPEMP;
}

protected double SPSE() {
return SPSE;
}

protected double TAXCR() {
return TAXCR;
}

protected double TAXGR() {
return TAXGR;
}

protected double TAXNET() {
return TAXNET;
}

public short getTENURE_DV() {
return TENURE_DV;
}

protected double XHWGHT() {
return XHWGHT;
}

public short getXPFOOD() {
return XPFOOD;
}

protected double XPFUEL() {
return XPFUEL;
}

protected double XPGAS() {
return XPGAS;
}

public short getXPGASL() {
return XPGASL;
}

public byte getXPGASLW() {
return XPGASLW;
}

protected double XPGASW() {
return XPGASW;
}

public short getXPHSD1() {
return XPHSD1;
}

public short getXPHSD2() {
return XPHSD2;
}

public short getXPHSDB_BH() {
return XPHSDB_BH;
}

public short getXPHSDF() {
return XPHSDF;
}

protected double XPHSG() {
return XPHSG;
}

public short getXPHSGI() {
return XPHSGI;
}

protected double XPHSN() {
return XPHSN;
}

public short getXPHSNI() {
return XPHSNI;
}

protected double XPLEC() {
return XPLEC;
}

public short getXPLECL() {
return XPLECL;
}

public byte getXPLECLW() {
return XPLECLW;
}

protected double XPLECW() {
return XPLECW;
}

public short getXPMG1() {
return XPMG1;
}

public short getXPMG2() {
return XPMG2;
}

public short getXPMG3() {
return XPMG3;
}

public short getXPMG4() {
return XPMG4;
}

public short getXPMGI() {
return XPMGI;
}

protected double XPOIL() {
return XPOIL;
}

public short getXPOILY() {
return XPOILY;
}

public short getXPOILY_BH() {
return XPOILY_BH;
}

protected double YRCONTR() {
return YRCONTR;
}

protected double YRDEDUC() {
return YRDEDUC;
}

protected double YRNI() {
return YRNI;
}

protected double YRTAXCR() {
return YRTAXCR;
}

protected double YRTAXGR() {
return YRTAXGR;
}

protected double YRTAXNT() {
return YRTAXNT;
}

public US_Wave2_hhresp_Record(String line) {
s = line.split("\t");
initHID(s[0]);
initHIDP(s[1]);
initINTDATED(s[2]);
initINTDATEM(s[3]);
initHSIVW1(s[4]);
initHSTYPE(s[5]);
initHSROOM(s[6]);
initHSOWND_BH(s[7]);
initHSOWR1_BH(s[8]);
initHSOWR2_BH(s[9]);
initMGHAVE(s[10]);
initHSOWRP(s[11]);
initMGYNOT_BH(s[12]);
initHSCOST(s[13]);
initMGSTAT(s[14]);
initMGEXTRA(s[15]);
initMGNEW(s[16]);
initMGXTY1_BH(s[17]);
initMGXTY2_BH(s[18]);
initMGXTY3_BH(s[19]);
initMGXTY4_BH(s[20]);
initMGXTY5_BH(s[21]);
initMGOLD(s[22]);
initMGLIFE(s[23]);
initMGTYPE_BH(s[24]);
initXPMG(s[25]);
initXPMG1(s[26]);
initXPMG2(s[27]);
initXPMG3(s[28]);
initXPMG4(s[29]);
initMGYR0(s[30]);
initHSYR0(s[31]);
initHSVAL(s[32]);
initHSJB(s[33]);
initRENTP1_BH(s[34]);
initRENTP2_BH(s[35]);
initRENTLL(s[36]);
initRENTF(s[37]);
initRENT(s[38]);
initRENTW(s[39]);
initRENT1(s[40]);
initRENT2(s[41]);
initRENT3(s[42]);
initRENT4(s[43]);
initRENT5(s[44]);
initRENT6(s[45]);
initRENTHB_BH(s[46]);
initRENTG_BH(s[47]);
initRENTGW(s[48]);
initXPHSDF(s[49]);
initXPHSD1(s[50]);
initXPHSD2(s[51]);
initXPHSDB_BH(s[52]);
initCDHAVE(s[53]);
initCD1USE(s[54]);
initCD1NEW(s[55]);
initCD2USE(s[56]);
initCD2NEW(s[57]);
initCD3USE(s[58]);
initCD3NEW(s[59]);
initCD4USE(s[60]);
initCD4NEW(s[61]);
initCD5USE(s[62]);
initCD5NEW(s[63]);
initCD6USE(s[64]);
initCD6NEW(s[65]);
initCD7USE(s[66]);
initCD7NEW(s[67]);
initCD8USE(s[68]);
initCD8NEW(s[69]);
initCD9USE(s[70]);
initCD9NEW(s[71]);
initCDNUXP(s[72]);
initHSIP(s[73]);
initHSIPXP(s[74]);
initHEATCH(s[75]);
initHEATYP(s[76]);
initXPOILY_BH(s[77]);
initGASUSE(s[78]);
initGASWAY(s[79]);
initXPGASL(s[80]);
initXPGASW(s[81]);
initXPGASLW(s[82]);
initLECWAY(s[83]);
initXPLECL(s[84]);
initXPLECW(s[85]);
initXPLECLW(s[86]);
initXPFOOD(s[87]);
initNCARS_BH(s[88]);
initIVH1_BH(s[89]);
initIVH2_BH(s[90]);
initIVH3_BH(s[91]);
initIVFHO_BH(s[92]);
initHHDC(s[93]);
initXHWGHT(s[94]);
initHHSIZE(s[95]);
initHHTYPE(s[96]);
initREGION(s[97]);
initNCH02_DV(s[98]);
initNCH34_DV(s[99]);
initNCH511_DV(s[100]);
initNCH1215_DV(s[101]);
initNCH1618(s[102]);
initNKIDS_DV(s[103]);
initNWED(s[104]);
initNPENS_DV(s[105]);
initNA75PL(s[106]);
initAGECHY_DV(s[107]);
initNCOUPLE_DV(s[108]);
initNONEPAR_DV(s[109]);
initNEMP_DV(s[110]);
initNWAGE_DV(s[111]);
initTENURE_DV(s[112]);
initXPHSN(s[113]);
initXPHSG(s[114]);
initXPOIL(s[115]);
initXPGAS(s[116]);
initXPLEC(s[117]);
initXPFUEL(s[118]);
initFIEQFCB(s[119]);
initFIEQFCA(s[120]);
initFIHHYR(s[121]);
initFIHHMNGRS_DV(s[122]);
initFIHHYL(s[123]);
initFIHHYNL(s[124]);
initFIHHYP(s[125]);
initFIHHYB(s[126]);
initFIHHYT(s[127]);
initFIHHYI(s[128]);
initFIHHML(s[129]);
initFIHHMNL(s[130]);
initFIHHMP(s[131]);
initFIHHMB(s[132]);
initFIHHMT(s[133]);
initFIHHMI(s[134]);
initHHMOVE(s[135]);
initMGNEWI(s[136]);
initXPMGI(s[137]);
initRENTI(s[138]);
initRENTGI(s[139]);
initXPHSNI(s[140]);
initXPHSGI(s[141]);
initFIHHMNI(s[142]);
initFIHHMLI(s[143]);
initFIHMNLI(s[144]);
initFIHHMPI(s[145]);
initFIHHMBI(s[146]);
initFIHHMTI(s[147]);
initFIHHMII(s[148]);
initFIHHYRI(s[149]);
initFIHHYLI(s[150]);
initFIHHYNI(s[151]);
initFIHHYPI(s[152]);
initFIHHYBI(s[153]);
initFIHHYTI(s[154]);
initFIHHYII(s[155]);
initINTDATEY(s[156]);
initMGYR04(s[157]);
initHSYR04_BH(s[158]);
initGOR_DV(s[159]);
initLOCTAX(s[160]);
initHDEMP(s[161]);
initSPEMP(s[162]);
initHDSE(s[163]);
initSPSE(s[164]);
initOTHLAB(s[165]);
initDEDUC(s[166]);
initNETLAB(s[167]);
initNI(s[168]);
initCONTR(s[169]);
initTAXNET(s[170]);
initTAXGR(s[171]);
initTAXCR(s[172]);
initGRPAY(s[173]);
initHCOST(s[174]);
initHHI(s[175]);
initHHB(s[176]);
initHHP(s[177]);
initHHT(s[178]);
initHHNETI(s[179]);
initHHNETDE(s[180]);
initHMAINT(s[181]);
initBHCIND(s[182]);
initMONUM(s[183]);
initHHNETDE2(s[184]);
initEQ_MOECD(s[185]);
initHHYRLN(s[186]);
initYRNI(s[187]);
initYRCONTR(s[188]);
initHHYRLG(s[189]);
initYRTAXNT(s[190]);
initYRTAXGR(s[191]);
initYRTAXCR(s[192]);
initYRDEDUC(s[193]);
initHHYRI(s[194]);
initHHYRB(s[195]);
initHHYRP(s[196]);
initHHYRT(s[197]);
initHHYNETI(s[198]);
initHHNYRDE(s[199]);
initBHCINDA(s[200]);
initBASEPI(s[201]);
initHHYRPI(s[202]);
initHHYRBI(s[203]);
initHHYRTI(s[204]);
initHHYRII(s[205]);
initHHYRLNI(s[206]);
initHHNYRDE2(s[207]);
initIVH0(s[208]);
initIVH1(s[209]);
initIVH2(s[210]);
initIVH3(s[211]);
initIVH4(s[212]);
initIVH5(s[213]);
initIVH6(s[214]);
initIVH7(s[215]);
initIVH8(s[216]);
initIVH9(s[217]);
initIVH10(s[218]);
initIVH11(s[219]);
initRENTP0(s[220]);
initRENTP1(s[221]);
initRENTP2(s[222]);
initRENTP3(s[223]);
initRENTP4(s[224]);
initRENTP5(s[225]);
initRENTP6(s[226]);
initRENTP7(s[227]);
initRENTP8(s[228]);
initRENTP9(s[229]);
initRENTP10(s[230]);
initRENTP11(s[231]);
initHSOWR10(s[232]);
initHSOWR11(s[233]);
initHSOWR12(s[234]);
initHSOWR13(s[235]);
initHSOWR14(s[236]);
initHSOWR15(s[237]);
initHSOWR16(s[238]);
initHSOWR17(s[239]);
initHSOWR18(s[240]);
initHSOWR19(s[241]);
initHSOWR110(s[242]);
initHSOWR111(s[243]);
initIVFHO(s[244]);
initHSYR04(s[245]);
initHSYRBUY(s[246]);
initXPHSDB(s[247]);
initXPOILY(s[248]);
initMGXTY1(s[249]);
initMGXTY2(s[250]);
initMGXTY3(s[251]);
initMGXTY4(s[252]);
initCDUSE1(s[253]);
initCDUSE2(s[254]);
initCDUSE5(s[255]);
initCDUSE6(s[256]);
initCDUSE7(s[257]);
initCDUSE8(s[258]);
initCDUSE9(s[259]);
initCDUSE10(s[260]);
initCDUSE11(s[261]);
initCDUSE96(s[262]);
}
}
