/**
 * Source code generated by uk.ac.leeds.ccg.andyt.generic.data.us.process.US_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.andyt.generic.data.us.data.hhresp;
public class US_Wave19_hhresp_Record extends US_hhresp_Record {
protected boolean ABSENT;
protected boolean CARNUM1;
protected boolean CARNUM2;
protected boolean CARNUM3;
protected boolean CARNUM4;
protected boolean CARNUM5;
protected byte CDELPLY;
protected byte CDEPDO1;
protected byte CDEPDO2;
protected byte CDEPDO3;
protected byte CDEPHAVE1;
protected byte CDEPHAVE2;
protected byte CDEPHAVE3;
protected byte CDEPHAVE4;
protected byte CDEPTRP;
protected short CDUSE10;
protected short CDUSE11;
protected short CDUSE12;
protected byte CDUSE13;
protected short CDUSE3;
protected short CDUSE4;
protected byte CDUSE5;
protected byte CDUSE7;
protected byte COUNTRY;
protected byte CPLAY;
protected boolean EMBOOST;
protected byte ENSIZE1;
protected byte ENSIZE2;
protected byte ENSIZE3;
protected byte ENSIZE4;
protected byte ENSIZE5;
protected byte ETARIFF;
protected double FIHHMNGRS1_DV;
protected double FIHHMNGRS_IF;
protected byte FIHHMNGRS_TC;
protected double FIHHMNINV_DV;
protected double FIHHMNLABGRS_DV;
protected byte FIHHMNLABGRS_TC;
protected double FIHHMNLABNET_DV;
protected double FIHHMNMISC_DV;
protected double FIHHMNNET1_DV;
protected double FIHHMNPEN_DV;
protected double FIHHMNPRBEN_DV;
protected double FIHHMNSBEN_DV;
protected byte FIHHNEGSEI_IF;
protected byte FUELDUEL;
protected byte FUELHAVE1;
protected byte FUELHAVE2;
protected byte FUELHAVE3;
protected byte FUELHAVE4;
protected byte FUELHAVE96;
protected boolean GPCOMP;
protected double HBADJUST_DV;
protected double HHDENUS_XW;
protected byte HHEAT;
protected byte HHINTLANG;
protected byte HHLANG;
protected byte HHORIG;
protected byte HHRESP_DV;
protected byte HHTYPE_DV;
protected byte HHWHOINT;
protected double HOUSCOST1_DV;
protected double HOUSCOST2_DV;
protected int HRPID;
protected byte HRPNO;
protected byte HSBEDS;
protected short HSCTAX;
protected byte HSOWND;
protected short HSOWR111;
protected short HSOWR112;
protected byte HSOWR113;
protected byte HSOWR114;
protected byte HSOWR115;
protected byte HSOWR116;
protected byte HSROOMS;
protected int HSTOTMG;
protected double IEQMOECD_DV;
protected short INTDATEY;
protected int INTNUM;
protected short IVFHO;
protected short IVH11;
protected short IVH12;
protected byte IVH13;
protected byte IVH14;
protected byte IVH15;
protected byte IVH16;
protected boolean LDA;
protected double LENHHINTV;
protected byte MATDEPA;
protected byte MATDEPB;
protected byte MATDEPC;
protected byte MATDEPD;
protected byte MATDEPE;
protected byte MATDEPF;
protected byte MATDEPG;
protected byte MATDEPH;
protected byte MGTYPE;
protected byte MONTH;
protected byte N10TO15;
protected byte NADOECD_DV;
protected byte NCARS;
protected byte NCHOECD_DV;
protected short NCOUPLE_DV;
protected byte NPENSIONER_DV;
protected byte NUE_DV;
protected byte NUMADULT;
protected byte NUMCHILD;
protected byte NUNDER10;
protected byte NUNDER15;
protected short NWAGE_DV;
protected byte OTHREC1;
protected byte OTHREC2;
protected byte OTHREC3;
protected byte OTHREC4;
protected byte PCBROAD;
protected short PCNET;
protected int PSU;
protected short RENTG;
protected double RENTGRS_DV;
protected byte RENTGRS_IF;
protected byte RENTHB;
protected byte RENTINC1;
protected byte RENTINC2;
protected byte RENTINC3;
protected byte RENTINC96;
protected short RENTP11;
protected short RENTP12;
protected byte RENTP13;
protected byte RENTP14;
protected byte RENTP15;
protected byte RENTP16;
protected byte RENTWC;
protected double RENT_DV;
protected byte RUBREC;
protected byte SOLAR1;
protected byte SOLAR2;
protected byte SOLAR3;
protected byte STARTDATD;
protected byte STARTDATM;
protected short STARTDATY;
protected short STRATA;
protected short TENURE_DV;
protected byte URBAN_DV;
protected byte WHODRIVE1;
protected byte WHODRIVE2;
protected byte WHODRIVE3;
protected byte WHODRIVE4;
protected byte WHODRIVE5;
protected short XPALTOB_G3;
protected short XPDUELY;
protected short XPELECY;
protected short XPFDOUT_G3;
protected short XPFOOD1_G3;
protected short XPGASY;
protected byte XPHSDBA;
protected byte XPHSDCT;
protected double XPMGINT_DV;
protected double XPMG_DV;
protected byte XPMG_IF;
protected short XPOILY;
protected short XPSFLY;
protected final void initABSENT(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == 1) {
ABSENT = false;
} else {
ABSENT = true;
}
}
}

protected final void initCARNUM1(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == -8) {
CARNUM1 = false;
} else {
CARNUM1 = true;
}
}
}

protected final void initCARNUM2(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == -8) {
CARNUM2 = false;
} else {
CARNUM2 = true;
}
}
}

protected final void initCARNUM3(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == -8) {
CARNUM3 = false;
} else {
CARNUM3 = true;
}
}
}

protected final void initCARNUM4(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == -8) {
CARNUM4 = false;
} else {
CARNUM4 = true;
}
}
}

protected final void initCARNUM5(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == -8) {
CARNUM5 = false;
} else {
CARNUM5 = true;
}
}
}

protected final void initCDELPLY(String s) {
if (!s.trim().isEmpty()) {
CDELPLY = Byte.parseByte(s);
} else {
CDELPLY = Byte.MIN_VALUE;
}
}

protected final void initCDEPDO1(String s) {
if (!s.trim().isEmpty()) {
CDEPDO1 = Byte.parseByte(s);
} else {
CDEPDO1 = Byte.MIN_VALUE;
}
}

protected final void initCDEPDO2(String s) {
if (!s.trim().isEmpty()) {
CDEPDO2 = Byte.parseByte(s);
} else {
CDEPDO2 = Byte.MIN_VALUE;
}
}

protected final void initCDEPDO3(String s) {
if (!s.trim().isEmpty()) {
CDEPDO3 = Byte.parseByte(s);
} else {
CDEPDO3 = Byte.MIN_VALUE;
}
}

protected final void initCDEPHAVE1(String s) {
if (!s.trim().isEmpty()) {
CDEPHAVE1 = Byte.parseByte(s);
} else {
CDEPHAVE1 = Byte.MIN_VALUE;
}
}

protected final void initCDEPHAVE2(String s) {
if (!s.trim().isEmpty()) {
CDEPHAVE2 = Byte.parseByte(s);
} else {
CDEPHAVE2 = Byte.MIN_VALUE;
}
}

protected final void initCDEPHAVE3(String s) {
if (!s.trim().isEmpty()) {
CDEPHAVE3 = Byte.parseByte(s);
} else {
CDEPHAVE3 = Byte.MIN_VALUE;
}
}

protected final void initCDEPHAVE4(String s) {
if (!s.trim().isEmpty()) {
CDEPHAVE4 = Byte.parseByte(s);
} else {
CDEPHAVE4 = Byte.MIN_VALUE;
}
}

protected final void initCDEPTRP(String s) {
if (!s.trim().isEmpty()) {
CDEPTRP = Byte.parseByte(s);
} else {
CDEPTRP = Byte.MIN_VALUE;
}
}

protected final void initCDUSE10(String s) {
if (!s.trim().isEmpty()) {
CDUSE10 = Short.parseShort(s);
} else {
CDUSE10 = Short.MIN_VALUE;
}
}

protected final void initCDUSE11(String s) {
if (!s.trim().isEmpty()) {
CDUSE11 = Short.parseShort(s);
} else {
CDUSE11 = Short.MIN_VALUE;
}
}

protected final void initCDUSE12(String s) {
if (!s.trim().isEmpty()) {
CDUSE12 = Short.parseShort(s);
} else {
CDUSE12 = Short.MIN_VALUE;
}
}

protected final void initCDUSE13(String s) {
if (!s.trim().isEmpty()) {
CDUSE13 = Byte.parseByte(s);
} else {
CDUSE13 = Byte.MIN_VALUE;
}
}

protected final void initCDUSE3(String s) {
if (!s.trim().isEmpty()) {
CDUSE3 = Short.parseShort(s);
} else {
CDUSE3 = Short.MIN_VALUE;
}
}

protected final void initCDUSE4(String s) {
if (!s.trim().isEmpty()) {
CDUSE4 = Short.parseShort(s);
} else {
CDUSE4 = Short.MIN_VALUE;
}
}

protected final void initCDUSE5(String s) {
if (!s.trim().isEmpty()) {
CDUSE5 = Byte.parseByte(s);
} else {
CDUSE5 = Byte.MIN_VALUE;
}
}

protected final void initCDUSE7(String s) {
if (!s.trim().isEmpty()) {
CDUSE7 = Byte.parseByte(s);
} else {
CDUSE7 = Byte.MIN_VALUE;
}
}

protected final void initCOUNTRY(String s) {
if (!s.trim().isEmpty()) {
COUNTRY = Byte.parseByte(s);
} else {
COUNTRY = Byte.MIN_VALUE;
}
}

protected final void initCPLAY(String s) {
if (!s.trim().isEmpty()) {
CPLAY = Byte.parseByte(s);
} else {
CPLAY = Byte.MIN_VALUE;
}
}

protected final void initEMBOOST(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == 0) {
EMBOOST = false;
} else {
EMBOOST = true;
}
}
}

protected final void initENSIZE1(String s) {
if (!s.trim().isEmpty()) {
ENSIZE1 = Byte.parseByte(s);
} else {
ENSIZE1 = Byte.MIN_VALUE;
}
}

protected final void initENSIZE2(String s) {
if (!s.trim().isEmpty()) {
ENSIZE2 = Byte.parseByte(s);
} else {
ENSIZE2 = Byte.MIN_VALUE;
}
}

protected final void initENSIZE3(String s) {
if (!s.trim().isEmpty()) {
ENSIZE3 = Byte.parseByte(s);
} else {
ENSIZE3 = Byte.MIN_VALUE;
}
}

protected final void initENSIZE4(String s) {
if (!s.trim().isEmpty()) {
ENSIZE4 = Byte.parseByte(s);
} else {
ENSIZE4 = Byte.MIN_VALUE;
}
}

protected final void initENSIZE5(String s) {
if (!s.trim().isEmpty()) {
ENSIZE5 = Byte.parseByte(s);
} else {
ENSIZE5 = Byte.MIN_VALUE;
}
}

protected final void initETARIFF(String s) {
if (!s.trim().isEmpty()) {
ETARIFF = Byte.parseByte(s);
} else {
ETARIFF = Byte.MIN_VALUE;
}
}

protected final void initFIHHMNGRS1_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNGRS1_DV = Double.parseDouble(s);
} else {
FIHHMNGRS1_DV = Double.NaN;
}
}

protected final void initFIHHMNGRS_IF(String s) {
if (!s.trim().isEmpty()) {
FIHHMNGRS_IF = Double.parseDouble(s);
} else {
FIHHMNGRS_IF = Double.NaN;
}
}

protected final void initFIHHMNGRS_TC(String s) {
if (!s.trim().isEmpty()) {
FIHHMNGRS_TC = Byte.parseByte(s);
} else {
FIHHMNGRS_TC = Byte.MIN_VALUE;
}
}

protected final void initFIHHMNINV_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNINV_DV = Double.parseDouble(s);
} else {
FIHHMNINV_DV = Double.NaN;
}
}

protected final void initFIHHMNLABGRS_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNLABGRS_DV = Double.parseDouble(s);
} else {
FIHHMNLABGRS_DV = Double.NaN;
}
}

protected final void initFIHHMNLABGRS_TC(String s) {
if (!s.trim().isEmpty()) {
FIHHMNLABGRS_TC = Byte.parseByte(s);
} else {
FIHHMNLABGRS_TC = Byte.MIN_VALUE;
}
}

protected final void initFIHHMNLABNET_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNLABNET_DV = Double.parseDouble(s);
} else {
FIHHMNLABNET_DV = Double.NaN;
}
}

protected final void initFIHHMNMISC_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNMISC_DV = Double.parseDouble(s);
} else {
FIHHMNMISC_DV = Double.NaN;
}
}

protected final void initFIHHMNNET1_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNNET1_DV = Double.parseDouble(s);
} else {
FIHHMNNET1_DV = Double.NaN;
}
}

protected final void initFIHHMNPEN_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNPEN_DV = Double.parseDouble(s);
} else {
FIHHMNPEN_DV = Double.NaN;
}
}

protected final void initFIHHMNPRBEN_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNPRBEN_DV = Double.parseDouble(s);
} else {
FIHHMNPRBEN_DV = Double.NaN;
}
}

protected final void initFIHHMNSBEN_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNSBEN_DV = Double.parseDouble(s);
} else {
FIHHMNSBEN_DV = Double.NaN;
}
}

protected final void initFIHHNEGSEI_IF(String s) {
if (!s.trim().isEmpty()) {
FIHHNEGSEI_IF = Byte.parseByte(s);
} else {
FIHHNEGSEI_IF = Byte.MIN_VALUE;
}
}

protected final void initFUELDUEL(String s) {
if (!s.trim().isEmpty()) {
FUELDUEL = Byte.parseByte(s);
} else {
FUELDUEL = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE1(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE1 = Byte.parseByte(s);
} else {
FUELHAVE1 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE2(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE2 = Byte.parseByte(s);
} else {
FUELHAVE2 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE3(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE3 = Byte.parseByte(s);
} else {
FUELHAVE3 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE4(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE4 = Byte.parseByte(s);
} else {
FUELHAVE4 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE96(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE96 = Byte.parseByte(s);
} else {
FUELHAVE96 = Byte.MIN_VALUE;
}
}

protected final void initGPCOMP(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == 0) {
GPCOMP = false;
} else {
GPCOMP = true;
}
}
}

protected final void initHBADJUST_DV(String s) {
if (!s.trim().isEmpty()) {
HBADJUST_DV = Double.parseDouble(s);
} else {
HBADJUST_DV = Double.NaN;
}
}

protected final void initHHDENUS_XW(String s) {
if (!s.trim().isEmpty()) {
HHDENUS_XW = Double.parseDouble(s);
} else {
HHDENUS_XW = Double.NaN;
}
}

protected final void initHHEAT(String s) {
if (!s.trim().isEmpty()) {
HHEAT = Byte.parseByte(s);
} else {
HHEAT = Byte.MIN_VALUE;
}
}

protected final void initHHINTLANG(String s) {
if (!s.trim().isEmpty()) {
HHINTLANG = Byte.parseByte(s);
} else {
HHINTLANG = Byte.MIN_VALUE;
}
}

protected final void initHHLANG(String s) {
if (!s.trim().isEmpty()) {
HHLANG = Byte.parseByte(s);
} else {
HHLANG = Byte.MIN_VALUE;
}
}

protected final void initHHORIG(String s) {
if (!s.trim().isEmpty()) {
HHORIG = Byte.parseByte(s);
} else {
HHORIG = Byte.MIN_VALUE;
}
}

protected final void initHHRESP_DV(String s) {
if (!s.trim().isEmpty()) {
HHRESP_DV = Byte.parseByte(s);
} else {
HHRESP_DV = Byte.MIN_VALUE;
}
}

protected final void initHHTYPE_DV(String s) {
if (!s.trim().isEmpty()) {
HHTYPE_DV = Byte.parseByte(s);
} else {
HHTYPE_DV = Byte.MIN_VALUE;
}
}

protected final void initHHWHOINT(String s) {
if (!s.trim().isEmpty()) {
HHWHOINT = Byte.parseByte(s);
} else {
HHWHOINT = Byte.MIN_VALUE;
}
}

protected final void initHOUSCOST1_DV(String s) {
if (!s.trim().isEmpty()) {
HOUSCOST1_DV = Double.parseDouble(s);
} else {
HOUSCOST1_DV = Double.NaN;
}
}

protected final void initHOUSCOST2_DV(String s) {
if (!s.trim().isEmpty()) {
HOUSCOST2_DV = Double.parseDouble(s);
} else {
HOUSCOST2_DV = Double.NaN;
}
}

protected final void initHRPID(String s) {
if (!s.trim().isEmpty()) {
HRPID = Integer.parseInt(s);
} else {
HRPID = Integer.MIN_VALUE;
}
}

protected final void initHRPNO(String s) {
if (!s.trim().isEmpty()) {
HRPNO = Byte.parseByte(s);
} else {
HRPNO = Byte.MIN_VALUE;
}
}

protected final void initHSBEDS(String s) {
if (!s.trim().isEmpty()) {
HSBEDS = Byte.parseByte(s);
} else {
HSBEDS = Byte.MIN_VALUE;
}
}

protected final void initHSCTAX(String s) {
if (!s.trim().isEmpty()) {
HSCTAX = Short.parseShort(s);
} else {
HSCTAX = Short.MIN_VALUE;
}
}

protected final void initHSOWND(String s) {
if (!s.trim().isEmpty()) {
HSOWND = Byte.parseByte(s);
} else {
HSOWND = Byte.MIN_VALUE;
}
}

protected final void initHSOWR111(String s) {
if (!s.trim().isEmpty()) {
HSOWR111 = Short.parseShort(s);
} else {
HSOWR111 = Short.MIN_VALUE;
}
}

protected final void initHSOWR112(String s) {
if (!s.trim().isEmpty()) {
HSOWR112 = Short.parseShort(s);
} else {
HSOWR112 = Short.MIN_VALUE;
}
}

protected final void initHSOWR113(String s) {
if (!s.trim().isEmpty()) {
HSOWR113 = Byte.parseByte(s);
} else {
HSOWR113 = Byte.MIN_VALUE;
}
}

protected final void initHSOWR114(String s) {
if (!s.trim().isEmpty()) {
HSOWR114 = Byte.parseByte(s);
} else {
HSOWR114 = Byte.MIN_VALUE;
}
}

protected final void initHSOWR115(String s) {
if (!s.trim().isEmpty()) {
HSOWR115 = Byte.parseByte(s);
} else {
HSOWR115 = Byte.MIN_VALUE;
}
}

protected final void initHSOWR116(String s) {
if (!s.trim().isEmpty()) {
HSOWR116 = Byte.parseByte(s);
} else {
HSOWR116 = Byte.MIN_VALUE;
}
}

protected final void initHSROOMS(String s) {
if (!s.trim().isEmpty()) {
HSROOMS = Byte.parseByte(s);
} else {
HSROOMS = Byte.MIN_VALUE;
}
}

protected final void initHSTOTMG(String s) {
if (!s.trim().isEmpty()) {
HSTOTMG = Integer.parseInt(s);
} else {
HSTOTMG = Integer.MIN_VALUE;
}
}

protected final void initIEQMOECD_DV(String s) {
if (!s.trim().isEmpty()) {
IEQMOECD_DV = Double.parseDouble(s);
} else {
IEQMOECD_DV = Double.NaN;
}
}

protected final void initINTDATEY(String s) {
if (!s.trim().isEmpty()) {
INTDATEY = Short.parseShort(s);
} else {
INTDATEY = Short.MIN_VALUE;
}
}

protected final void initINTNUM(String s) {
if (!s.trim().isEmpty()) {
INTNUM = Integer.parseInt(s);
} else {
INTNUM = Integer.MIN_VALUE;
}
}

protected final void initIVFHO(String s) {
if (!s.trim().isEmpty()) {
IVFHO = Short.parseShort(s);
} else {
IVFHO = Short.MIN_VALUE;
}
}

protected final void initIVH11(String s) {
if (!s.trim().isEmpty()) {
IVH11 = Short.parseShort(s);
} else {
IVH11 = Short.MIN_VALUE;
}
}

protected final void initIVH12(String s) {
if (!s.trim().isEmpty()) {
IVH12 = Short.parseShort(s);
} else {
IVH12 = Short.MIN_VALUE;
}
}

protected final void initIVH13(String s) {
if (!s.trim().isEmpty()) {
IVH13 = Byte.parseByte(s);
} else {
IVH13 = Byte.MIN_VALUE;
}
}

protected final void initIVH14(String s) {
if (!s.trim().isEmpty()) {
IVH14 = Byte.parseByte(s);
} else {
IVH14 = Byte.MIN_VALUE;
}
}

protected final void initIVH15(String s) {
if (!s.trim().isEmpty()) {
IVH15 = Byte.parseByte(s);
} else {
IVH15 = Byte.MIN_VALUE;
}
}

protected final void initIVH16(String s) {
if (!s.trim().isEmpty()) {
IVH16 = Byte.parseByte(s);
} else {
IVH16 = Byte.MIN_VALUE;
}
}

protected final void initLDA(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == 0) {
LDA = false;
} else {
LDA = true;
}
}
}

protected final void initLENHHINTV(String s) {
if (!s.trim().isEmpty()) {
LENHHINTV = Double.parseDouble(s);
} else {
LENHHINTV = Double.NaN;
}
}

protected final void initMATDEPA(String s) {
if (!s.trim().isEmpty()) {
MATDEPA = Byte.parseByte(s);
} else {
MATDEPA = Byte.MIN_VALUE;
}
}

protected final void initMATDEPB(String s) {
if (!s.trim().isEmpty()) {
MATDEPB = Byte.parseByte(s);
} else {
MATDEPB = Byte.MIN_VALUE;
}
}

protected final void initMATDEPC(String s) {
if (!s.trim().isEmpty()) {
MATDEPC = Byte.parseByte(s);
} else {
MATDEPC = Byte.MIN_VALUE;
}
}

protected final void initMATDEPD(String s) {
if (!s.trim().isEmpty()) {
MATDEPD = Byte.parseByte(s);
} else {
MATDEPD = Byte.MIN_VALUE;
}
}

protected final void initMATDEPE(String s) {
if (!s.trim().isEmpty()) {
MATDEPE = Byte.parseByte(s);
} else {
MATDEPE = Byte.MIN_VALUE;
}
}

protected final void initMATDEPF(String s) {
if (!s.trim().isEmpty()) {
MATDEPF = Byte.parseByte(s);
} else {
MATDEPF = Byte.MIN_VALUE;
}
}

protected final void initMATDEPG(String s) {
if (!s.trim().isEmpty()) {
MATDEPG = Byte.parseByte(s);
} else {
MATDEPG = Byte.MIN_VALUE;
}
}

protected final void initMATDEPH(String s) {
if (!s.trim().isEmpty()) {
MATDEPH = Byte.parseByte(s);
} else {
MATDEPH = Byte.MIN_VALUE;
}
}

protected final void initMGTYPE(String s) {
if (!s.trim().isEmpty()) {
MGTYPE = Byte.parseByte(s);
} else {
MGTYPE = Byte.MIN_VALUE;
}
}

protected final void initMONTH(String s) {
if (!s.trim().isEmpty()) {
MONTH = Byte.parseByte(s);
} else {
MONTH = Byte.MIN_VALUE;
}
}

protected final void initN10TO15(String s) {
if (!s.trim().isEmpty()) {
N10TO15 = Byte.parseByte(s);
} else {
N10TO15 = Byte.MIN_VALUE;
}
}

protected final void initNADOECD_DV(String s) {
if (!s.trim().isEmpty()) {
NADOECD_DV = Byte.parseByte(s);
} else {
NADOECD_DV = Byte.MIN_VALUE;
}
}

protected final void initNCARS(String s) {
if (!s.trim().isEmpty()) {
NCARS = Byte.parseByte(s);
} else {
NCARS = Byte.MIN_VALUE;
}
}

protected final void initNCHOECD_DV(String s) {
if (!s.trim().isEmpty()) {
NCHOECD_DV = Byte.parseByte(s);
} else {
NCHOECD_DV = Byte.MIN_VALUE;
}
}

protected final void initNCOUPLE_DV(String s) {
if (!s.trim().isEmpty()) {
NCOUPLE_DV = Short.parseShort(s);
} else {
NCOUPLE_DV = Short.MIN_VALUE;
}
}

protected final void initNPENSIONER_DV(String s) {
if (!s.trim().isEmpty()) {
NPENSIONER_DV = Byte.parseByte(s);
} else {
NPENSIONER_DV = Byte.MIN_VALUE;
}
}

protected final void initNUE_DV(String s) {
if (!s.trim().isEmpty()) {
NUE_DV = Byte.parseByte(s);
} else {
NUE_DV = Byte.MIN_VALUE;
}
}

protected final void initNUMADULT(String s) {
if (!s.trim().isEmpty()) {
NUMADULT = Byte.parseByte(s);
} else {
NUMADULT = Byte.MIN_VALUE;
}
}

protected final void initNUMCHILD(String s) {
if (!s.trim().isEmpty()) {
NUMCHILD = Byte.parseByte(s);
} else {
NUMCHILD = Byte.MIN_VALUE;
}
}

protected final void initNUNDER10(String s) {
if (!s.trim().isEmpty()) {
NUNDER10 = Byte.parseByte(s);
} else {
NUNDER10 = Byte.MIN_VALUE;
}
}

protected final void initNUNDER15(String s) {
if (!s.trim().isEmpty()) {
NUNDER15 = Byte.parseByte(s);
} else {
NUNDER15 = Byte.MIN_VALUE;
}
}

protected final void initNWAGE_DV(String s) {
if (!s.trim().isEmpty()) {
NWAGE_DV = Short.parseShort(s);
} else {
NWAGE_DV = Short.MIN_VALUE;
}
}

protected final void initOTHREC1(String s) {
if (!s.trim().isEmpty()) {
OTHREC1 = Byte.parseByte(s);
} else {
OTHREC1 = Byte.MIN_VALUE;
}
}

protected final void initOTHREC2(String s) {
if (!s.trim().isEmpty()) {
OTHREC2 = Byte.parseByte(s);
} else {
OTHREC2 = Byte.MIN_VALUE;
}
}

protected final void initOTHREC3(String s) {
if (!s.trim().isEmpty()) {
OTHREC3 = Byte.parseByte(s);
} else {
OTHREC3 = Byte.MIN_VALUE;
}
}

protected final void initOTHREC4(String s) {
if (!s.trim().isEmpty()) {
OTHREC4 = Byte.parseByte(s);
} else {
OTHREC4 = Byte.MIN_VALUE;
}
}

protected final void initPCBROAD(String s) {
if (!s.trim().isEmpty()) {
PCBROAD = Byte.parseByte(s);
} else {
PCBROAD = Byte.MIN_VALUE;
}
}

protected final void initPCNET(String s) {
if (!s.trim().isEmpty()) {
PCNET = Short.parseShort(s);
} else {
PCNET = Short.MIN_VALUE;
}
}

protected final void initPSU(String s) {
if (!s.trim().isEmpty()) {
PSU = Integer.parseInt(s);
} else {
PSU = Integer.MIN_VALUE;
}
}

protected final void initRENTG(String s) {
if (!s.trim().isEmpty()) {
RENTG = Short.parseShort(s);
} else {
RENTG = Short.MIN_VALUE;
}
}

protected final void initRENTGRS_DV(String s) {
if (!s.trim().isEmpty()) {
RENTGRS_DV = Double.parseDouble(s);
} else {
RENTGRS_DV = Double.NaN;
}
}

protected final void initRENTGRS_IF(String s) {
if (!s.trim().isEmpty()) {
RENTGRS_IF = Byte.parseByte(s);
} else {
RENTGRS_IF = Byte.MIN_VALUE;
}
}

protected final void initRENTHB(String s) {
if (!s.trim().isEmpty()) {
RENTHB = Byte.parseByte(s);
} else {
RENTHB = Byte.MIN_VALUE;
}
}

protected final void initRENTINC1(String s) {
if (!s.trim().isEmpty()) {
RENTINC1 = Byte.parseByte(s);
} else {
RENTINC1 = Byte.MIN_VALUE;
}
}

protected final void initRENTINC2(String s) {
if (!s.trim().isEmpty()) {
RENTINC2 = Byte.parseByte(s);
} else {
RENTINC2 = Byte.MIN_VALUE;
}
}

protected final void initRENTINC3(String s) {
if (!s.trim().isEmpty()) {
RENTINC3 = Byte.parseByte(s);
} else {
RENTINC3 = Byte.MIN_VALUE;
}
}

protected final void initRENTINC96(String s) {
if (!s.trim().isEmpty()) {
RENTINC96 = Byte.parseByte(s);
} else {
RENTINC96 = Byte.MIN_VALUE;
}
}

protected final void initRENTP11(String s) {
if (!s.trim().isEmpty()) {
RENTP11 = Short.parseShort(s);
} else {
RENTP11 = Short.MIN_VALUE;
}
}

protected final void initRENTP12(String s) {
if (!s.trim().isEmpty()) {
RENTP12 = Short.parseShort(s);
} else {
RENTP12 = Short.MIN_VALUE;
}
}

protected final void initRENTP13(String s) {
if (!s.trim().isEmpty()) {
RENTP13 = Byte.parseByte(s);
} else {
RENTP13 = Byte.MIN_VALUE;
}
}

protected final void initRENTP14(String s) {
if (!s.trim().isEmpty()) {
RENTP14 = Byte.parseByte(s);
} else {
RENTP14 = Byte.MIN_VALUE;
}
}

protected final void initRENTP15(String s) {
if (!s.trim().isEmpty()) {
RENTP15 = Byte.parseByte(s);
} else {
RENTP15 = Byte.MIN_VALUE;
}
}

protected final void initRENTP16(String s) {
if (!s.trim().isEmpty()) {
RENTP16 = Byte.parseByte(s);
} else {
RENTP16 = Byte.MIN_VALUE;
}
}

protected final void initRENTWC(String s) {
if (!s.trim().isEmpty()) {
RENTWC = Byte.parseByte(s);
} else {
RENTWC = Byte.MIN_VALUE;
}
}

protected final void initRENT_DV(String s) {
if (!s.trim().isEmpty()) {
RENT_DV = Double.parseDouble(s);
} else {
RENT_DV = Double.NaN;
}
}

protected final void initRUBREC(String s) {
if (!s.trim().isEmpty()) {
RUBREC = Byte.parseByte(s);
} else {
RUBREC = Byte.MIN_VALUE;
}
}

protected final void initSOLAR1(String s) {
if (!s.trim().isEmpty()) {
SOLAR1 = Byte.parseByte(s);
} else {
SOLAR1 = Byte.MIN_VALUE;
}
}

protected final void initSOLAR2(String s) {
if (!s.trim().isEmpty()) {
SOLAR2 = Byte.parseByte(s);
} else {
SOLAR2 = Byte.MIN_VALUE;
}
}

protected final void initSOLAR3(String s) {
if (!s.trim().isEmpty()) {
SOLAR3 = Byte.parseByte(s);
} else {
SOLAR3 = Byte.MIN_VALUE;
}
}

protected final void initSTARTDATD(String s) {
if (!s.trim().isEmpty()) {
STARTDATD = Byte.parseByte(s);
} else {
STARTDATD = Byte.MIN_VALUE;
}
}

protected final void initSTARTDATM(String s) {
if (!s.trim().isEmpty()) {
STARTDATM = Byte.parseByte(s);
} else {
STARTDATM = Byte.MIN_VALUE;
}
}

protected final void initSTARTDATY(String s) {
if (!s.trim().isEmpty()) {
STARTDATY = Short.parseShort(s);
} else {
STARTDATY = Short.MIN_VALUE;
}
}

protected final void initSTRATA(String s) {
if (!s.trim().isEmpty()) {
STRATA = Short.parseShort(s);
} else {
STRATA = Short.MIN_VALUE;
}
}

protected final void initTENURE_DV(String s) {
if (!s.trim().isEmpty()) {
TENURE_DV = Short.parseShort(s);
} else {
TENURE_DV = Short.MIN_VALUE;
}
}

protected final void initURBAN_DV(String s) {
if (!s.trim().isEmpty()) {
URBAN_DV = Byte.parseByte(s);
} else {
URBAN_DV = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE1(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE1 = Byte.parseByte(s);
} else {
WHODRIVE1 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE2(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE2 = Byte.parseByte(s);
} else {
WHODRIVE2 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE3(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE3 = Byte.parseByte(s);
} else {
WHODRIVE3 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE4(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE4 = Byte.parseByte(s);
} else {
WHODRIVE4 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE5(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE5 = Byte.parseByte(s);
} else {
WHODRIVE5 = Byte.MIN_VALUE;
}
}

protected final void initXPALTOB_G3(String s) {
if (!s.trim().isEmpty()) {
XPALTOB_G3 = Short.parseShort(s);
} else {
XPALTOB_G3 = Short.MIN_VALUE;
}
}

protected final void initXPDUELY(String s) {
if (!s.trim().isEmpty()) {
XPDUELY = Short.parseShort(s);
} else {
XPDUELY = Short.MIN_VALUE;
}
}

protected final void initXPELECY(String s) {
if (!s.trim().isEmpty()) {
XPELECY = Short.parseShort(s);
} else {
XPELECY = Short.MIN_VALUE;
}
}

protected final void initXPFDOUT_G3(String s) {
if (!s.trim().isEmpty()) {
XPFDOUT_G3 = Short.parseShort(s);
} else {
XPFDOUT_G3 = Short.MIN_VALUE;
}
}

protected final void initXPFOOD1_G3(String s) {
if (!s.trim().isEmpty()) {
XPFOOD1_G3 = Short.parseShort(s);
} else {
XPFOOD1_G3 = Short.MIN_VALUE;
}
}

protected final void initXPGASY(String s) {
if (!s.trim().isEmpty()) {
XPGASY = Short.parseShort(s);
} else {
XPGASY = Short.MIN_VALUE;
}
}

protected final void initXPHSDBA(String s) {
if (!s.trim().isEmpty()) {
XPHSDBA = Byte.parseByte(s);
} else {
XPHSDBA = Byte.MIN_VALUE;
}
}

protected final void initXPHSDCT(String s) {
if (!s.trim().isEmpty()) {
XPHSDCT = Byte.parseByte(s);
} else {
XPHSDCT = Byte.MIN_VALUE;
}
}

protected final void initXPMGINT_DV(String s) {
if (!s.trim().isEmpty()) {
XPMGINT_DV = Double.parseDouble(s);
} else {
XPMGINT_DV = Double.NaN;
}
}

protected final void initXPMG_DV(String s) {
if (!s.trim().isEmpty()) {
XPMG_DV = Double.parseDouble(s);
} else {
XPMG_DV = Double.NaN;
}
}

protected final void initXPMG_IF(String s) {
if (!s.trim().isEmpty()) {
XPMG_IF = Byte.parseByte(s);
} else {
XPMG_IF = Byte.MIN_VALUE;
}
}

protected final void initXPOILY(String s) {
if (!s.trim().isEmpty()) {
XPOILY = Short.parseShort(s);
} else {
XPOILY = Short.MIN_VALUE;
}
}

protected final void initXPSFLY(String s) {
if (!s.trim().isEmpty()) {
XPSFLY = Short.parseShort(s);
} else {
XPSFLY = Short.MIN_VALUE;
}
}

public boolean getABSENT() {
return ABSENT;
}

public boolean getCARNUM1() {
return CARNUM1;
}

public boolean getCARNUM2() {
return CARNUM2;
}

public boolean getCARNUM3() {
return CARNUM3;
}

public boolean getCARNUM4() {
return CARNUM4;
}

public boolean getCARNUM5() {
return CARNUM5;
}

public byte getCDELPLY() {
return CDELPLY;
}

public byte getCDEPDO1() {
return CDEPDO1;
}

public byte getCDEPDO2() {
return CDEPDO2;
}

public byte getCDEPDO3() {
return CDEPDO3;
}

public byte getCDEPHAVE1() {
return CDEPHAVE1;
}

public byte getCDEPHAVE2() {
return CDEPHAVE2;
}

public byte getCDEPHAVE3() {
return CDEPHAVE3;
}

public byte getCDEPHAVE4() {
return CDEPHAVE4;
}

public byte getCDEPTRP() {
return CDEPTRP;
}

public short getCDUSE10() {
return CDUSE10;
}

public short getCDUSE11() {
return CDUSE11;
}

public short getCDUSE12() {
return CDUSE12;
}

public byte getCDUSE13() {
return CDUSE13;
}

public short getCDUSE3() {
return CDUSE3;
}

public short getCDUSE4() {
return CDUSE4;
}

public byte getCDUSE5() {
return CDUSE5;
}

public byte getCDUSE7() {
return CDUSE7;
}

public byte getCOUNTRY() {
return COUNTRY;
}

public byte getCPLAY() {
return CPLAY;
}

public boolean getEMBOOST() {
return EMBOOST;
}

public byte getENSIZE1() {
return ENSIZE1;
}

public byte getENSIZE2() {
return ENSIZE2;
}

public byte getENSIZE3() {
return ENSIZE3;
}

public byte getENSIZE4() {
return ENSIZE4;
}

public byte getENSIZE5() {
return ENSIZE5;
}

public byte getETARIFF() {
return ETARIFF;
}

protected double FIHHMNGRS1_DV() {
return FIHHMNGRS1_DV;
}

protected double FIHHMNGRS_IF() {
return FIHHMNGRS_IF;
}

public byte getFIHHMNGRS_TC() {
return FIHHMNGRS_TC;
}

protected double FIHHMNINV_DV() {
return FIHHMNINV_DV;
}

protected double FIHHMNLABGRS_DV() {
return FIHHMNLABGRS_DV;
}

public byte getFIHHMNLABGRS_TC() {
return FIHHMNLABGRS_TC;
}

protected double FIHHMNLABNET_DV() {
return FIHHMNLABNET_DV;
}

protected double FIHHMNMISC_DV() {
return FIHHMNMISC_DV;
}

protected double FIHHMNNET1_DV() {
return FIHHMNNET1_DV;
}

protected double FIHHMNPEN_DV() {
return FIHHMNPEN_DV;
}

protected double FIHHMNPRBEN_DV() {
return FIHHMNPRBEN_DV;
}

protected double FIHHMNSBEN_DV() {
return FIHHMNSBEN_DV;
}

public byte getFIHHNEGSEI_IF() {
return FIHHNEGSEI_IF;
}

public byte getFUELDUEL() {
return FUELDUEL;
}

public byte getFUELHAVE1() {
return FUELHAVE1;
}

public byte getFUELHAVE2() {
return FUELHAVE2;
}

public byte getFUELHAVE3() {
return FUELHAVE3;
}

public byte getFUELHAVE4() {
return FUELHAVE4;
}

public byte getFUELHAVE96() {
return FUELHAVE96;
}

public boolean getGPCOMP() {
return GPCOMP;
}

protected double HBADJUST_DV() {
return HBADJUST_DV;
}

protected double HHDENUS_XW() {
return HHDENUS_XW;
}

public byte getHHEAT() {
return HHEAT;
}

public byte getHHINTLANG() {
return HHINTLANG;
}

public byte getHHLANG() {
return HHLANG;
}

public byte getHHORIG() {
return HHORIG;
}

public byte getHHRESP_DV() {
return HHRESP_DV;
}

public byte getHHTYPE_DV() {
return HHTYPE_DV;
}

public byte getHHWHOINT() {
return HHWHOINT;
}

protected double HOUSCOST1_DV() {
return HOUSCOST1_DV;
}

protected double HOUSCOST2_DV() {
return HOUSCOST2_DV;
}

public int getHRPID() {
return HRPID;
}

public byte getHRPNO() {
return HRPNO;
}

public byte getHSBEDS() {
return HSBEDS;
}

public short getHSCTAX() {
return HSCTAX;
}

public byte getHSOWND() {
return HSOWND;
}

public short getHSOWR111() {
return HSOWR111;
}

public short getHSOWR112() {
return HSOWR112;
}

public byte getHSOWR113() {
return HSOWR113;
}

public byte getHSOWR114() {
return HSOWR114;
}

public byte getHSOWR115() {
return HSOWR115;
}

public byte getHSOWR116() {
return HSOWR116;
}

public byte getHSROOMS() {
return HSROOMS;
}

public int getHSTOTMG() {
return HSTOTMG;
}

protected double IEQMOECD_DV() {
return IEQMOECD_DV;
}

public short getINTDATEY() {
return INTDATEY;
}

public int getINTNUM() {
return INTNUM;
}

public short getIVFHO() {
return IVFHO;
}

public short getIVH11() {
return IVH11;
}

public short getIVH12() {
return IVH12;
}

public byte getIVH13() {
return IVH13;
}

public byte getIVH14() {
return IVH14;
}

public byte getIVH15() {
return IVH15;
}

public byte getIVH16() {
return IVH16;
}

public boolean getLDA() {
return LDA;
}

protected double LENHHINTV() {
return LENHHINTV;
}

public byte getMATDEPA() {
return MATDEPA;
}

public byte getMATDEPB() {
return MATDEPB;
}

public byte getMATDEPC() {
return MATDEPC;
}

public byte getMATDEPD() {
return MATDEPD;
}

public byte getMATDEPE() {
return MATDEPE;
}

public byte getMATDEPF() {
return MATDEPF;
}

public byte getMATDEPG() {
return MATDEPG;
}

public byte getMATDEPH() {
return MATDEPH;
}

public byte getMGTYPE() {
return MGTYPE;
}

public byte getMONTH() {
return MONTH;
}

public byte getN10TO15() {
return N10TO15;
}

public byte getNADOECD_DV() {
return NADOECD_DV;
}

public byte getNCARS() {
return NCARS;
}

public byte getNCHOECD_DV() {
return NCHOECD_DV;
}

public short getNCOUPLE_DV() {
return NCOUPLE_DV;
}

public byte getNPENSIONER_DV() {
return NPENSIONER_DV;
}

public byte getNUE_DV() {
return NUE_DV;
}

public byte getNUMADULT() {
return NUMADULT;
}

public byte getNUMCHILD() {
return NUMCHILD;
}

public byte getNUNDER10() {
return NUNDER10;
}

public byte getNUNDER15() {
return NUNDER15;
}

public short getNWAGE_DV() {
return NWAGE_DV;
}

public byte getOTHREC1() {
return OTHREC1;
}

public byte getOTHREC2() {
return OTHREC2;
}

public byte getOTHREC3() {
return OTHREC3;
}

public byte getOTHREC4() {
return OTHREC4;
}

public byte getPCBROAD() {
return PCBROAD;
}

public short getPCNET() {
return PCNET;
}

public int getPSU() {
return PSU;
}

public short getRENTG() {
return RENTG;
}

protected double RENTGRS_DV() {
return RENTGRS_DV;
}

public byte getRENTGRS_IF() {
return RENTGRS_IF;
}

public byte getRENTHB() {
return RENTHB;
}

public byte getRENTINC1() {
return RENTINC1;
}

public byte getRENTINC2() {
return RENTINC2;
}

public byte getRENTINC3() {
return RENTINC3;
}

public byte getRENTINC96() {
return RENTINC96;
}

public short getRENTP11() {
return RENTP11;
}

public short getRENTP12() {
return RENTP12;
}

public byte getRENTP13() {
return RENTP13;
}

public byte getRENTP14() {
return RENTP14;
}

public byte getRENTP15() {
return RENTP15;
}

public byte getRENTP16() {
return RENTP16;
}

public byte getRENTWC() {
return RENTWC;
}

protected double RENT_DV() {
return RENT_DV;
}

public byte getRUBREC() {
return RUBREC;
}

public byte getSOLAR1() {
return SOLAR1;
}

public byte getSOLAR2() {
return SOLAR2;
}

public byte getSOLAR3() {
return SOLAR3;
}

public byte getSTARTDATD() {
return STARTDATD;
}

public byte getSTARTDATM() {
return STARTDATM;
}

public short getSTARTDATY() {
return STARTDATY;
}

public short getSTRATA() {
return STRATA;
}

public short getTENURE_DV() {
return TENURE_DV;
}

public byte getURBAN_DV() {
return URBAN_DV;
}

public byte getWHODRIVE1() {
return WHODRIVE1;
}

public byte getWHODRIVE2() {
return WHODRIVE2;
}

public byte getWHODRIVE3() {
return WHODRIVE3;
}

public byte getWHODRIVE4() {
return WHODRIVE4;
}

public byte getWHODRIVE5() {
return WHODRIVE5;
}

public short getXPALTOB_G3() {
return XPALTOB_G3;
}

public short getXPDUELY() {
return XPDUELY;
}

public short getXPELECY() {
return XPELECY;
}

public short getXPFDOUT_G3() {
return XPFDOUT_G3;
}

public short getXPFOOD1_G3() {
return XPFOOD1_G3;
}

public short getXPGASY() {
return XPGASY;
}

public byte getXPHSDBA() {
return XPHSDBA;
}

public byte getXPHSDCT() {
return XPHSDCT;
}

protected double XPMGINT_DV() {
return XPMGINT_DV;
}

protected double XPMG_DV() {
return XPMG_DV;
}

public byte getXPMG_IF() {
return XPMG_IF;
}

public short getXPOILY() {
return XPOILY;
}

public short getXPSFLY() {
return XPSFLY;
}

public US_Wave19_hhresp_Record(String line) {
s = line.split("\t");
initHIDP(s[0]);
initINTNUM(s[1]);
initHHORIG(s[2]);
initPSU(s[3]);
initSTRATA(s[4]);
initMONTH(s[5]);
initIVFHO(s[6]);
initSTARTDATD(s[7]);
initSTARTDATM(s[8]);
initSTARTDATY(s[9]);
initINTDATED(s[10]);
initINTDATEM(s[11]);
initINTDATEY(s[12]);
initIVH1(s[13]);
initIVH2(s[14]);
initIVH3(s[15]);
initIVH4(s[16]);
initIVH5(s[17]);
initIVH6(s[18]);
initIVH7(s[19]);
initIVH8(s[20]);
initIVH9(s[21]);
initIVH10(s[22]);
initIVH11(s[23]);
initIVH12(s[24]);
initIVH13(s[25]);
initIVH14(s[26]);
initIVH15(s[27]);
initIVH16(s[28]);
initHSBEDS(s[29]);
initHSROOMS(s[30]);
initHSOWND(s[31]);
initHSOWR10(s[32]);
initHSOWR11(s[33]);
initHSOWR12(s[34]);
initHSOWR13(s[35]);
initHSOWR14(s[36]);
initHSOWR15(s[37]);
initHSOWR16(s[38]);
initHSOWR17(s[39]);
initHSOWR18(s[40]);
initHSOWR19(s[41]);
initHSOWR110(s[42]);
initHSOWR111(s[43]);
initHSOWR112(s[44]);
initHSOWR113(s[45]);
initHSOWR114(s[46]);
initHSOWR115(s[47]);
initHSOWR116(s[48]);
initHSVAL(s[49]);
initHSYRBUY(s[50]);
initHSCOST(s[51]);
initHSYR04(s[52]);
initHSTOTMG(s[53]);
initMGLIFE(s[54]);
initMGTYPE(s[55]);
initXPMG(s[56]);
initHSJB(s[57]);
initRENTP0(s[58]);
initRENTP1(s[59]);
initRENTP2(s[60]);
initRENTP3(s[61]);
initRENTP4(s[62]);
initRENTP5(s[63]);
initRENTP6(s[64]);
initRENTP7(s[65]);
initRENTP8(s[66]);
initRENTP9(s[67]);
initRENTP10(s[68]);
initRENTP11(s[69]);
initRENTP12(s[70]);
initRENTP13(s[71]);
initRENTP14(s[72]);
initRENTP15(s[73]);
initRENTP16(s[74]);
initRENTLL(s[75]);
initRENTF(s[76]);
initRENT(s[77]);
initRENTWC(s[78]);
initRENTINC1(s[79]);
initRENTINC2(s[80]);
initRENTINC3(s[81]);
initRENTINC96(s[82]);
initRENTHB(s[83]);
initRENTG(s[84]);
initFUELHAVE1(s[85]);
initFUELHAVE2(s[86]);
initFUELHAVE3(s[87]);
initFUELHAVE4(s[88]);
initFUELHAVE96(s[89]);
initFUELDUEL(s[90]);
initXPDUELY(s[91]);
initXPELECY(s[92]);
initXPGASY(s[93]);
initXPOILY(s[94]);
initXPSFLY(s[95]);
initHEATCH(s[96]);
initSOLAR1(s[97]);
initSOLAR2(s[98]);
initSOLAR3(s[99]);
initETARIFF(s[100]);
initRUBREC(s[101]);
initOTHREC1(s[102]);
initOTHREC2(s[103]);
initOTHREC3(s[104]);
initOTHREC4(s[105]);
initHSCTAX(s[106]);
initXPHSDB(s[107]);
initXPHSDCT(s[108]);
initXPHSDBA(s[109]);
initCDUSE1(s[110]);
initCDUSE2(s[111]);
initCDUSE3(s[112]);
initCDUSE4(s[113]);
initCDUSE5(s[114]);
initCDUSE6(s[115]);
initCDUSE7(s[116]);
initCDUSE8(s[117]);
initCDUSE9(s[118]);
initCDUSE10(s[119]);
initCDUSE11(s[120]);
initCDUSE12(s[121]);
initCDUSE13(s[122]);
initCDUSE96(s[123]);
initPCNET(s[124]);
initPCBROAD(s[125]);
initXPFOOD1_G3(s[126]);
initXPFDOUT_G3(s[127]);
initXPALTOB_G3(s[128]);
initMATDEPA(s[129]);
initMATDEPB(s[130]);
initMATDEPC(s[131]);
initMATDEPD(s[132]);
initMATDEPE(s[133]);
initMATDEPF(s[134]);
initMATDEPG(s[135]);
initMATDEPH(s[136]);
initHHEAT(s[137]);
initCDEPHAVE1(s[138]);
initCDEPHAVE2(s[139]);
initCDEPHAVE3(s[140]);
initCDEPHAVE4(s[141]);
initCDEPDO1(s[142]);
initCDEPDO2(s[143]);
initCDEPDO3(s[144]);
initCPLAY(s[145]);
initCDEPTRP(s[146]);
initCDELPLY(s[147]);
initNCARS(s[148]);
initCARNUM1(s[149]);
initENSIZE1(s[150]);
initWHODRIVE1(s[151]);
initCARNUM2(s[152]);
initENSIZE2(s[153]);
initWHODRIVE2(s[154]);
initCARNUM3(s[155]);
initENSIZE3(s[156]);
initWHODRIVE3(s[157]);
initCARNUM4(s[158]);
initENSIZE4(s[159]);
initWHODRIVE4(s[160]);
initCARNUM5(s[161]);
initENSIZE5(s[162]);
initWHODRIVE5(s[163]);
initLENHHINTV(s[164]);
initHHLANG(s[165]);
initHHINTLANG(s[166]);
initHHWHOINT(s[167]);
initEMBOOST(s[168]);
initGPCOMP(s[169]);
initLDA(s[170]);
initHHSIZE(s[171]);
initABSENT(s[172]);
initNUMADULT(s[173]);
initNUMCHILD(s[174]);
initNUNDER15(s[175]);
initN10TO15(s[176]);
initNUNDER10(s[177]);
initFIHHMNGRS_DV(s[178]);
initFIHHMNGRS_TC(s[179]);
initFIHHMNLABGRS_DV(s[180]);
initFIHHMNLABGRS_TC(s[181]);
initRENTGRS_IF(s[182]);
initXPMG_IF(s[183]);
initNPENSIONER_DV(s[184]);
initFIHHMNNET1_DV(s[185]);
initFIHHMNLABNET_DV(s[186]);
initFIHHMNMISC_DV(s[187]);
initFIHHMNPRBEN_DV(s[188]);
initFIHHMNINV_DV(s[189]);
initFIHHMNPEN_DV(s[190]);
initFIHHMNSBEN_DV(s[191]);
initRENT_DV(s[192]);
initRENTGRS_DV(s[193]);
initHBADJUST_DV(s[194]);
initXPMG_DV(s[195]);
initXPMGINT_DV(s[196]);
initHOUSCOST1_DV(s[197]);
initHOUSCOST2_DV(s[198]);
initFIHHMNGRS1_DV(s[199]);
initCOUNTRY(s[200]);
initGOR_DV(s[201]);
initURBAN_DV(s[202]);
initHHRESP_DV(s[203]);
initHHTYPE_DV(s[204]);
initHRPID(s[205]);
initHRPNO(s[206]);
initNCOUPLE_DV(s[207]);
initNONEPAR_DV(s[208]);
initNKIDS_DV(s[209]);
initNCH02_DV(s[210]);
initNCH34_DV(s[211]);
initNCH511_DV(s[212]);
initNCH1215_DV(s[213]);
initAGECHY_DV(s[214]);
initNPENS_DV(s[215]);
initNEMP_DV(s[216]);
initNUE_DV(s[217]);
initNWAGE_DV(s[218]);
initNCHOECD_DV(s[219]);
initNADOECD_DV(s[220]);
initIEQMOECD_DV(s[221]);
initTENURE_DV(s[222]);
initFIHHNEGSEI_IF(s[223]);
initFIHHMNGRS_IF(s[224]);
initHHDENUS_XW(s[225]);
}
}
