/**
 * Source code generated by uk.ac.leeds.ccg.andyt.generic.data.us.process.US_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.data.us.data.hhresp;
public class US_Wave25_hhresp_Record extends US_hhresp_Record {
protected byte ADDRCHCK;
protected byte CARAGE1;
protected byte CARAGE2;
protected byte CARAGE3;
protected byte CARAGE4;
protected byte CARAGE5;
protected byte CARFUEL1;
protected byte CARFUEL2;
protected byte CARFUEL3;
protected byte CARFUEL4;
protected byte CARFUEL5;
protected byte CARN2H1;
protected byte CARN2H2;
protected byte CARN2H3;
protected byte CARN2H4;
protected byte CARN2H5;
protected int CARVAL;
protected short CDUSE10;
protected short CDUSE11;
protected short CDUSE12;
protected byte CDUSE13;
protected short CDUSE3;
protected short CDUSE4;
protected byte CDUSE5;
protected byte CDUSE7;
protected byte CORDET1;
protected byte CORDET10;
protected byte CORDET11;
protected byte CORDET12;
protected byte CORDET13;
protected byte CORDET14;
protected byte CORDET15;
protected byte CORDET16;
protected byte CORDET17;
protected byte CORDET18;
protected byte CORDET19;
protected byte CORDET2;
protected byte CORDET20;
protected byte CORDET21;
protected byte CORDET22;
protected byte CORDET23;
protected byte CORDET24;
protected byte CORDET25;
protected byte CORDET26;
protected byte CORDET27;
protected byte CORDET28;
protected byte CORDET29;
protected byte CORDET3;
protected byte CORDET30;
protected byte CORDET31;
protected byte CORDET32;
protected byte CORDET4;
protected byte CORDET5;
protected byte CORDET6;
protected byte CORDET7;
protected byte CORDET8;
protected byte CORDET9;
protected byte CORDET96;
protected byte CORESWHO1;
protected byte CORESWHO10;
protected byte CORESWHO11;
protected byte CORESWHO12;
protected byte CORESWHO13;
protected byte CORESWHO14;
protected byte CORESWHO15;
protected byte CORESWHO16;
protected byte CORESWHO2;
protected byte CORESWHO3;
protected byte CORESWHO4;
protected byte CORESWHO5;
protected byte CORESWHO6;
protected byte CORESWHO7;
protected byte CORESWHO8;
protected byte CORESWHO9;
protected byte CORESWHO96;
protected byte COUNTRY;
protected byte DUELPAY;
protected byte ELECPAY;
protected byte ENSZE1;
protected byte ENSZE2;
protected byte ENSZE3;
protected byte ENSZE4;
protected byte ENSZE5;
protected boolean FBORN;
protected byte FF_HSBEDS;
protected byte FF_HSOWND;
protected byte FF_HSROOMS;
protected double FIHHMNGRS1_DV;
protected double FIHHMNGRS_IF;
protected byte FIHHMNGRS_TC;
protected double FIHHMNINV_DV;
protected double FIHHMNLABGRS_DV;
protected byte FIHHMNLABGRS_TC;
protected double FIHHMNLABNET_DV;
protected double FIHHMNMISC_DV;
protected double FIHHMNNET1_DV;
protected double FIHHMNPEN_DV;
protected double FIHHMNPRBEN_DV;
protected double FIHHMNSBEN_DV;
protected byte FIHHNEGSEI_IF;
protected byte FUELDUEL;
protected byte FUELHAVE1;
protected byte FUELHAVE2;
protected byte FUELHAVE3;
protected byte FUELHAVE4;
protected byte FUELHAVE96;
protected byte GASPAY;
protected double HBADJUST_DV;
protected byte HGENDDATD;
protected byte HGENDDATHH;
protected byte HGENDDATM;
protected byte HGENDDATMM;
protected byte HGENDDATSS;
protected short HGENDDATY;
protected byte HGLIENG;
protected byte HGLITRANS;
protected byte HGSTRTDATD;
protected byte HGSTRTDATHH;
protected byte HGSTRTDATM;
protected byte HGSTRTDATMM;
protected byte HGSTRTDATSS;
protected short HGSTRTDATY;
protected double HHDENUB_XW;
protected double HHDENUI_XW;
protected byte HHINTLANG;
protected byte HHLANG;
protected byte HHOLDMODEDV;
protected byte HHORIG;
protected byte HHQREF1;
protected byte HHQREF10;
protected byte HHQREF11;
protected byte HHQREF12;
protected byte HHQREF13;
protected byte HHQREF14;
protected byte HHQREF15;
protected byte HHQREF16;
protected byte HHQREF17;
protected byte HHQREF18;
protected byte HHQREF19;
protected byte HHQREF2;
protected byte HHQREF20;
protected byte HHQREF21;
protected byte HHQREF22;
protected byte HHQREF23;
protected byte HHQREF24;
protected byte HHQREF25;
protected byte HHQREF26;
protected byte HHQREF27;
protected byte HHQREF28;
protected byte HHQREF29;
protected byte HHQREF3;
protected byte HHQREF30;
protected byte HHQREF31;
protected byte HHQREF32;
protected byte HHQREF4;
protected byte HHQREF5;
protected byte HHQREF6;
protected byte HHQREF7;
protected byte HHQREF8;
protected byte HHQREF9;
protected byte HHQURECOMPLETE;
protected byte HHRESP_DV;
protected byte HHTYPE_DV;
protected byte HIENDDATD;
protected byte HIENDDATHH;
protected byte HIENDDATM;
protected byte HIENDDATMM;
protected byte HIENDDATSS;
protected short HIENDDATY;
protected byte HISTRTDATD;
protected byte HISTRTDATHH;
protected byte HISTRTDATM;
protected byte HISTRTDATMM;
protected short HISTRTDATY;
protected byte HLIENG;
protected byte HLITRANS;
protected byte HLIWHO;
protected double HOUSCOST1_DV;
protected double HOUSCOST2_DV;
protected int HRPID;
protected byte HRPNO;
protected byte HSBEDS;
protected short HSCTAX;
protected byte HSOWND;
protected byte HSOWNDCHK;
protected short HSOWR111;
protected short HSOWR112;
protected byte HSOWR113;
protected byte HSOWR114;
protected byte HSOWR115;
protected byte HSOWR116;
protected byte HSROOMCHK;
protected byte HSROOMS;
protected int HSTOTMG;
protected byte IEMB;
protected double IEQMOECD_DV;
protected short INTDATEY;
protected int INTNUM;
protected short IVFHO;
protected short IVH0;
protected short IVH11;
protected short IVH12;
protected byte IVH13;
protected byte IVH14;
protected byte IVH15;
protected byte IVH16;
protected short MGEXTRA;
protected int MGNEW;
protected int MGOLD;
protected byte MGTYPE;
protected short MGXTY1;
protected short MGXTY2;
protected short MGXTY3;
protected short MGXTY4;
protected byte MGXTY5;
protected byte MGXTY6;
protected byte MGXTY97;
protected byte MGYNOT;
protected byte MONTH;
protected byte MORES;
protected byte N10TO15;
protected byte NADOECD_DV;
protected byte NCARS;
protected byte NCHOECD_DV;
protected short NCOUPLE_DV;
protected byte NKIDS015;
protected byte NKIDS05;
protected byte NKIDS615;
protected byte NPENSIONER;
protected byte NPENSIONER_DV;
protected byte NUE_DV;
protected short NWAGE_DV;
protected byte ORIGADD;
protected short OUTCOME;
protected byte PCBROAD;
protected byte PCHAS;
protected short PCNET;
protected int PSU;
protected byte QUARTER;
protected short RENTG;
protected double RENTGRS_DV;
protected byte RENTGRS_IF;
protected byte RENTHB;
protected byte RENTINC1;
protected byte RENTINC2;
protected byte RENTINC3;
protected byte RENTINC96;
protected short RENTP11;
protected short RENTP12;
protected byte RENTP13;
protected byte RENTP14;
protected byte RENTP15;
protected byte RENTP16;
protected byte RENTWC;
protected double RENT_DV;
protected boolean RINGFENCE;
protected short STRATA;
protected short TENURE_DV;
protected byte URBAN_DV;
protected byte WHODRIVE1;
protected byte WHODRIVE2;
protected byte WHODRIVE3;
protected byte WHODRIVE4;
protected byte WHODRIVE5;
protected short XPALTOB_G3;
protected short XPDUELY;
protected short XPELECY;
protected short XPFDOUT_G3;
protected short XPFOOD1_G3;
protected short XPGASY;
protected byte XPHSDBA;
protected byte XPHSDCT;
protected double XPMDV;
protected double XPMGINT_DV;
protected byte XPMIF;
protected short XPOILY;
protected short XPSFLY;
protected final void initADDRCHCK(String s) {
if (!s.trim().isEmpty()) {
ADDRCHCK = Byte.parseByte(s);
} else {
ADDRCHCK = Byte.MIN_VALUE;
}
}

protected final void initCARAGE1(String s) {
if (!s.trim().isEmpty()) {
CARAGE1 = Byte.parseByte(s);
} else {
CARAGE1 = Byte.MIN_VALUE;
}
}

protected final void initCARAGE2(String s) {
if (!s.trim().isEmpty()) {
CARAGE2 = Byte.parseByte(s);
} else {
CARAGE2 = Byte.MIN_VALUE;
}
}

protected final void initCARAGE3(String s) {
if (!s.trim().isEmpty()) {
CARAGE3 = Byte.parseByte(s);
} else {
CARAGE3 = Byte.MIN_VALUE;
}
}

protected final void initCARAGE4(String s) {
if (!s.trim().isEmpty()) {
CARAGE4 = Byte.parseByte(s);
} else {
CARAGE4 = Byte.MIN_VALUE;
}
}

protected final void initCARAGE5(String s) {
if (!s.trim().isEmpty()) {
CARAGE5 = Byte.parseByte(s);
} else {
CARAGE5 = Byte.MIN_VALUE;
}
}

protected final void initCARFUEL1(String s) {
if (!s.trim().isEmpty()) {
CARFUEL1 = Byte.parseByte(s);
} else {
CARFUEL1 = Byte.MIN_VALUE;
}
}

protected final void initCARFUEL2(String s) {
if (!s.trim().isEmpty()) {
CARFUEL2 = Byte.parseByte(s);
} else {
CARFUEL2 = Byte.MIN_VALUE;
}
}

protected final void initCARFUEL3(String s) {
if (!s.trim().isEmpty()) {
CARFUEL3 = Byte.parseByte(s);
} else {
CARFUEL3 = Byte.MIN_VALUE;
}
}

protected final void initCARFUEL4(String s) {
if (!s.trim().isEmpty()) {
CARFUEL4 = Byte.parseByte(s);
} else {
CARFUEL4 = Byte.MIN_VALUE;
}
}

protected final void initCARFUEL5(String s) {
if (!s.trim().isEmpty()) {
CARFUEL5 = Byte.parseByte(s);
} else {
CARFUEL5 = Byte.MIN_VALUE;
}
}

protected final void initCARN2H1(String s) {
if (!s.trim().isEmpty()) {
CARN2H1 = Byte.parseByte(s);
} else {
CARN2H1 = Byte.MIN_VALUE;
}
}

protected final void initCARN2H2(String s) {
if (!s.trim().isEmpty()) {
CARN2H2 = Byte.parseByte(s);
} else {
CARN2H2 = Byte.MIN_VALUE;
}
}

protected final void initCARN2H3(String s) {
if (!s.trim().isEmpty()) {
CARN2H3 = Byte.parseByte(s);
} else {
CARN2H3 = Byte.MIN_VALUE;
}
}

protected final void initCARN2H4(String s) {
if (!s.trim().isEmpty()) {
CARN2H4 = Byte.parseByte(s);
} else {
CARN2H4 = Byte.MIN_VALUE;
}
}

protected final void initCARN2H5(String s) {
if (!s.trim().isEmpty()) {
CARN2H5 = Byte.parseByte(s);
} else {
CARN2H5 = Byte.MIN_VALUE;
}
}

protected final void initCARVAL(String s) {
if (!s.trim().isEmpty()) {
CARVAL = Integer.parseInt(s);
} else {
CARVAL = Integer.MIN_VALUE;
}
}

protected final void initCDUSE10(String s) {
if (!s.trim().isEmpty()) {
CDUSE10 = Short.parseShort(s);
} else {
CDUSE10 = Short.MIN_VALUE;
}
}

protected final void initCDUSE11(String s) {
if (!s.trim().isEmpty()) {
CDUSE11 = Short.parseShort(s);
} else {
CDUSE11 = Short.MIN_VALUE;
}
}

protected final void initCDUSE12(String s) {
if (!s.trim().isEmpty()) {
CDUSE12 = Short.parseShort(s);
} else {
CDUSE12 = Short.MIN_VALUE;
}
}

protected final void initCDUSE13(String s) {
if (!s.trim().isEmpty()) {
CDUSE13 = Byte.parseByte(s);
} else {
CDUSE13 = Byte.MIN_VALUE;
}
}

protected final void initCDUSE3(String s) {
if (!s.trim().isEmpty()) {
CDUSE3 = Short.parseShort(s);
} else {
CDUSE3 = Short.MIN_VALUE;
}
}

protected final void initCDUSE4(String s) {
if (!s.trim().isEmpty()) {
CDUSE4 = Short.parseShort(s);
} else {
CDUSE4 = Short.MIN_VALUE;
}
}

protected final void initCDUSE5(String s) {
if (!s.trim().isEmpty()) {
CDUSE5 = Byte.parseByte(s);
} else {
CDUSE5 = Byte.MIN_VALUE;
}
}

protected final void initCDUSE7(String s) {
if (!s.trim().isEmpty()) {
CDUSE7 = Byte.parseByte(s);
} else {
CDUSE7 = Byte.MIN_VALUE;
}
}

protected final void initCORDET1(String s) {
if (!s.trim().isEmpty()) {
CORDET1 = Byte.parseByte(s);
} else {
CORDET1 = Byte.MIN_VALUE;
}
}

protected final void initCORDET10(String s) {
if (!s.trim().isEmpty()) {
CORDET10 = Byte.parseByte(s);
} else {
CORDET10 = Byte.MIN_VALUE;
}
}

protected final void initCORDET11(String s) {
if (!s.trim().isEmpty()) {
CORDET11 = Byte.parseByte(s);
} else {
CORDET11 = Byte.MIN_VALUE;
}
}

protected final void initCORDET12(String s) {
if (!s.trim().isEmpty()) {
CORDET12 = Byte.parseByte(s);
} else {
CORDET12 = Byte.MIN_VALUE;
}
}

protected final void initCORDET13(String s) {
if (!s.trim().isEmpty()) {
CORDET13 = Byte.parseByte(s);
} else {
CORDET13 = Byte.MIN_VALUE;
}
}

protected final void initCORDET14(String s) {
if (!s.trim().isEmpty()) {
CORDET14 = Byte.parseByte(s);
} else {
CORDET14 = Byte.MIN_VALUE;
}
}

protected final void initCORDET15(String s) {
if (!s.trim().isEmpty()) {
CORDET15 = Byte.parseByte(s);
} else {
CORDET15 = Byte.MIN_VALUE;
}
}

protected final void initCORDET16(String s) {
if (!s.trim().isEmpty()) {
CORDET16 = Byte.parseByte(s);
} else {
CORDET16 = Byte.MIN_VALUE;
}
}

protected final void initCORDET17(String s) {
if (!s.trim().isEmpty()) {
CORDET17 = Byte.parseByte(s);
} else {
CORDET17 = Byte.MIN_VALUE;
}
}

protected final void initCORDET18(String s) {
if (!s.trim().isEmpty()) {
CORDET18 = Byte.parseByte(s);
} else {
CORDET18 = Byte.MIN_VALUE;
}
}

protected final void initCORDET19(String s) {
if (!s.trim().isEmpty()) {
CORDET19 = Byte.parseByte(s);
} else {
CORDET19 = Byte.MIN_VALUE;
}
}

protected final void initCORDET2(String s) {
if (!s.trim().isEmpty()) {
CORDET2 = Byte.parseByte(s);
} else {
CORDET2 = Byte.MIN_VALUE;
}
}

protected final void initCORDET20(String s) {
if (!s.trim().isEmpty()) {
CORDET20 = Byte.parseByte(s);
} else {
CORDET20 = Byte.MIN_VALUE;
}
}

protected final void initCORDET21(String s) {
if (!s.trim().isEmpty()) {
CORDET21 = Byte.parseByte(s);
} else {
CORDET21 = Byte.MIN_VALUE;
}
}

protected final void initCORDET22(String s) {
if (!s.trim().isEmpty()) {
CORDET22 = Byte.parseByte(s);
} else {
CORDET22 = Byte.MIN_VALUE;
}
}

protected final void initCORDET23(String s) {
if (!s.trim().isEmpty()) {
CORDET23 = Byte.parseByte(s);
} else {
CORDET23 = Byte.MIN_VALUE;
}
}

protected final void initCORDET24(String s) {
if (!s.trim().isEmpty()) {
CORDET24 = Byte.parseByte(s);
} else {
CORDET24 = Byte.MIN_VALUE;
}
}

protected final void initCORDET25(String s) {
if (!s.trim().isEmpty()) {
CORDET25 = Byte.parseByte(s);
} else {
CORDET25 = Byte.MIN_VALUE;
}
}

protected final void initCORDET26(String s) {
if (!s.trim().isEmpty()) {
CORDET26 = Byte.parseByte(s);
} else {
CORDET26 = Byte.MIN_VALUE;
}
}

protected final void initCORDET27(String s) {
if (!s.trim().isEmpty()) {
CORDET27 = Byte.parseByte(s);
} else {
CORDET27 = Byte.MIN_VALUE;
}
}

protected final void initCORDET28(String s) {
if (!s.trim().isEmpty()) {
CORDET28 = Byte.parseByte(s);
} else {
CORDET28 = Byte.MIN_VALUE;
}
}

protected final void initCORDET29(String s) {
if (!s.trim().isEmpty()) {
CORDET29 = Byte.parseByte(s);
} else {
CORDET29 = Byte.MIN_VALUE;
}
}

protected final void initCORDET3(String s) {
if (!s.trim().isEmpty()) {
CORDET3 = Byte.parseByte(s);
} else {
CORDET3 = Byte.MIN_VALUE;
}
}

protected final void initCORDET30(String s) {
if (!s.trim().isEmpty()) {
CORDET30 = Byte.parseByte(s);
} else {
CORDET30 = Byte.MIN_VALUE;
}
}

protected final void initCORDET31(String s) {
if (!s.trim().isEmpty()) {
CORDET31 = Byte.parseByte(s);
} else {
CORDET31 = Byte.MIN_VALUE;
}
}

protected final void initCORDET32(String s) {
if (!s.trim().isEmpty()) {
CORDET32 = Byte.parseByte(s);
} else {
CORDET32 = Byte.MIN_VALUE;
}
}

protected final void initCORDET4(String s) {
if (!s.trim().isEmpty()) {
CORDET4 = Byte.parseByte(s);
} else {
CORDET4 = Byte.MIN_VALUE;
}
}

protected final void initCORDET5(String s) {
if (!s.trim().isEmpty()) {
CORDET5 = Byte.parseByte(s);
} else {
CORDET5 = Byte.MIN_VALUE;
}
}

protected final void initCORDET6(String s) {
if (!s.trim().isEmpty()) {
CORDET6 = Byte.parseByte(s);
} else {
CORDET6 = Byte.MIN_VALUE;
}
}

protected final void initCORDET7(String s) {
if (!s.trim().isEmpty()) {
CORDET7 = Byte.parseByte(s);
} else {
CORDET7 = Byte.MIN_VALUE;
}
}

protected final void initCORDET8(String s) {
if (!s.trim().isEmpty()) {
CORDET8 = Byte.parseByte(s);
} else {
CORDET8 = Byte.MIN_VALUE;
}
}

protected final void initCORDET9(String s) {
if (!s.trim().isEmpty()) {
CORDET9 = Byte.parseByte(s);
} else {
CORDET9 = Byte.MIN_VALUE;
}
}

protected final void initCORDET96(String s) {
if (!s.trim().isEmpty()) {
CORDET96 = Byte.parseByte(s);
} else {
CORDET96 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO1(String s) {
if (!s.trim().isEmpty()) {
CORESWHO1 = Byte.parseByte(s);
} else {
CORESWHO1 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO10(String s) {
if (!s.trim().isEmpty()) {
CORESWHO10 = Byte.parseByte(s);
} else {
CORESWHO10 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO11(String s) {
if (!s.trim().isEmpty()) {
CORESWHO11 = Byte.parseByte(s);
} else {
CORESWHO11 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO12(String s) {
if (!s.trim().isEmpty()) {
CORESWHO12 = Byte.parseByte(s);
} else {
CORESWHO12 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO13(String s) {
if (!s.trim().isEmpty()) {
CORESWHO13 = Byte.parseByte(s);
} else {
CORESWHO13 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO14(String s) {
if (!s.trim().isEmpty()) {
CORESWHO14 = Byte.parseByte(s);
} else {
CORESWHO14 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO15(String s) {
if (!s.trim().isEmpty()) {
CORESWHO15 = Byte.parseByte(s);
} else {
CORESWHO15 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO16(String s) {
if (!s.trim().isEmpty()) {
CORESWHO16 = Byte.parseByte(s);
} else {
CORESWHO16 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO2(String s) {
if (!s.trim().isEmpty()) {
CORESWHO2 = Byte.parseByte(s);
} else {
CORESWHO2 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO3(String s) {
if (!s.trim().isEmpty()) {
CORESWHO3 = Byte.parseByte(s);
} else {
CORESWHO3 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO4(String s) {
if (!s.trim().isEmpty()) {
CORESWHO4 = Byte.parseByte(s);
} else {
CORESWHO4 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO5(String s) {
if (!s.trim().isEmpty()) {
CORESWHO5 = Byte.parseByte(s);
} else {
CORESWHO5 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO6(String s) {
if (!s.trim().isEmpty()) {
CORESWHO6 = Byte.parseByte(s);
} else {
CORESWHO6 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO7(String s) {
if (!s.trim().isEmpty()) {
CORESWHO7 = Byte.parseByte(s);
} else {
CORESWHO7 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO8(String s) {
if (!s.trim().isEmpty()) {
CORESWHO8 = Byte.parseByte(s);
} else {
CORESWHO8 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO9(String s) {
if (!s.trim().isEmpty()) {
CORESWHO9 = Byte.parseByte(s);
} else {
CORESWHO9 = Byte.MIN_VALUE;
}
}

protected final void initCORESWHO96(String s) {
if (!s.trim().isEmpty()) {
CORESWHO96 = Byte.parseByte(s);
} else {
CORESWHO96 = Byte.MIN_VALUE;
}
}

protected final void initCOUNTRY(String s) {
if (!s.trim().isEmpty()) {
COUNTRY = Byte.parseByte(s);
} else {
COUNTRY = Byte.MIN_VALUE;
}
}

protected final void initDUELPAY(String s) {
if (!s.trim().isEmpty()) {
DUELPAY = Byte.parseByte(s);
} else {
DUELPAY = Byte.MIN_VALUE;
}
}

protected final void initELECPAY(String s) {
if (!s.trim().isEmpty()) {
ELECPAY = Byte.parseByte(s);
} else {
ELECPAY = Byte.MIN_VALUE;
}
}

protected final void initENSZE1(String s) {
if (!s.trim().isEmpty()) {
ENSZE1 = Byte.parseByte(s);
} else {
ENSZE1 = Byte.MIN_VALUE;
}
}

protected final void initENSZE2(String s) {
if (!s.trim().isEmpty()) {
ENSZE2 = Byte.parseByte(s);
} else {
ENSZE2 = Byte.MIN_VALUE;
}
}

protected final void initENSZE3(String s) {
if (!s.trim().isEmpty()) {
ENSZE3 = Byte.parseByte(s);
} else {
ENSZE3 = Byte.MIN_VALUE;
}
}

protected final void initENSZE4(String s) {
if (!s.trim().isEmpty()) {
ENSZE4 = Byte.parseByte(s);
} else {
ENSZE4 = Byte.MIN_VALUE;
}
}

protected final void initENSZE5(String s) {
if (!s.trim().isEmpty()) {
ENSZE5 = Byte.parseByte(s);
} else {
ENSZE5 = Byte.MIN_VALUE;
}
}

protected final void initFBORN(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == 1) {
FBORN = false;
} else {
FBORN = true;
}
}
}

protected final void initFF_HSBEDS(String s) {
if (!s.trim().isEmpty()) {
FF_HSBEDS = Byte.parseByte(s);
} else {
FF_HSBEDS = Byte.MIN_VALUE;
}
}

protected final void initFF_HSOWND(String s) {
if (!s.trim().isEmpty()) {
FF_HSOWND = Byte.parseByte(s);
} else {
FF_HSOWND = Byte.MIN_VALUE;
}
}

protected final void initFF_HSROOMS(String s) {
if (!s.trim().isEmpty()) {
FF_HSROOMS = Byte.parseByte(s);
} else {
FF_HSROOMS = Byte.MIN_VALUE;
}
}

protected final void initFIHHMNGRS1_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNGRS1_DV = Double.parseDouble(s);
} else {
FIHHMNGRS1_DV = Double.NaN;
}
}

protected final void initFIHHMNGRS_IF(String s) {
if (!s.trim().isEmpty()) {
FIHHMNGRS_IF = Double.parseDouble(s);
} else {
FIHHMNGRS_IF = Double.NaN;
}
}

protected final void initFIHHMNGRS_TC(String s) {
if (!s.trim().isEmpty()) {
FIHHMNGRS_TC = Byte.parseByte(s);
} else {
FIHHMNGRS_TC = Byte.MIN_VALUE;
}
}

protected final void initFIHHMNINV_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNINV_DV = Double.parseDouble(s);
} else {
FIHHMNINV_DV = Double.NaN;
}
}

protected final void initFIHHMNLABGRS_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNLABGRS_DV = Double.parseDouble(s);
} else {
FIHHMNLABGRS_DV = Double.NaN;
}
}

protected final void initFIHHMNLABGRS_TC(String s) {
if (!s.trim().isEmpty()) {
FIHHMNLABGRS_TC = Byte.parseByte(s);
} else {
FIHHMNLABGRS_TC = Byte.MIN_VALUE;
}
}

protected final void initFIHHMNLABNET_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNLABNET_DV = Double.parseDouble(s);
} else {
FIHHMNLABNET_DV = Double.NaN;
}
}

protected final void initFIHHMNMISC_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNMISC_DV = Double.parseDouble(s);
} else {
FIHHMNMISC_DV = Double.NaN;
}
}

protected final void initFIHHMNNET1_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNNET1_DV = Double.parseDouble(s);
} else {
FIHHMNNET1_DV = Double.NaN;
}
}

protected final void initFIHHMNPEN_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNPEN_DV = Double.parseDouble(s);
} else {
FIHHMNPEN_DV = Double.NaN;
}
}

protected final void initFIHHMNPRBEN_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNPRBEN_DV = Double.parseDouble(s);
} else {
FIHHMNPRBEN_DV = Double.NaN;
}
}

protected final void initFIHHMNSBEN_DV(String s) {
if (!s.trim().isEmpty()) {
FIHHMNSBEN_DV = Double.parseDouble(s);
} else {
FIHHMNSBEN_DV = Double.NaN;
}
}

protected final void initFIHHNEGSEI_IF(String s) {
if (!s.trim().isEmpty()) {
FIHHNEGSEI_IF = Byte.parseByte(s);
} else {
FIHHNEGSEI_IF = Byte.MIN_VALUE;
}
}

protected final void initFUELDUEL(String s) {
if (!s.trim().isEmpty()) {
FUELDUEL = Byte.parseByte(s);
} else {
FUELDUEL = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE1(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE1 = Byte.parseByte(s);
} else {
FUELHAVE1 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE2(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE2 = Byte.parseByte(s);
} else {
FUELHAVE2 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE3(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE3 = Byte.parseByte(s);
} else {
FUELHAVE3 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE4(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE4 = Byte.parseByte(s);
} else {
FUELHAVE4 = Byte.MIN_VALUE;
}
}

protected final void initFUELHAVE96(String s) {
if (!s.trim().isEmpty()) {
FUELHAVE96 = Byte.parseByte(s);
} else {
FUELHAVE96 = Byte.MIN_VALUE;
}
}

protected final void initGASPAY(String s) {
if (!s.trim().isEmpty()) {
GASPAY = Byte.parseByte(s);
} else {
GASPAY = Byte.MIN_VALUE;
}
}

protected final void initHBADJUST_DV(String s) {
if (!s.trim().isEmpty()) {
HBADJUST_DV = Double.parseDouble(s);
} else {
HBADJUST_DV = Double.NaN;
}
}

protected final void initHGENDDATD(String s) {
if (!s.trim().isEmpty()) {
HGENDDATD = Byte.parseByte(s);
} else {
HGENDDATD = Byte.MIN_VALUE;
}
}

protected final void initHGENDDATHH(String s) {
if (!s.trim().isEmpty()) {
HGENDDATHH = Byte.parseByte(s);
} else {
HGENDDATHH = Byte.MIN_VALUE;
}
}

protected final void initHGENDDATM(String s) {
if (!s.trim().isEmpty()) {
HGENDDATM = Byte.parseByte(s);
} else {
HGENDDATM = Byte.MIN_VALUE;
}
}

protected final void initHGENDDATMM(String s) {
if (!s.trim().isEmpty()) {
HGENDDATMM = Byte.parseByte(s);
} else {
HGENDDATMM = Byte.MIN_VALUE;
}
}

protected final void initHGENDDATSS(String s) {
if (!s.trim().isEmpty()) {
HGENDDATSS = Byte.parseByte(s);
} else {
HGENDDATSS = Byte.MIN_VALUE;
}
}

protected final void initHGENDDATY(String s) {
if (!s.trim().isEmpty()) {
HGENDDATY = Short.parseShort(s);
} else {
HGENDDATY = Short.MIN_VALUE;
}
}

protected final void initHGLIENG(String s) {
if (!s.trim().isEmpty()) {
HGLIENG = Byte.parseByte(s);
} else {
HGLIENG = Byte.MIN_VALUE;
}
}

protected final void initHGLITRANS(String s) {
if (!s.trim().isEmpty()) {
HGLITRANS = Byte.parseByte(s);
} else {
HGLITRANS = Byte.MIN_VALUE;
}
}

protected final void initHGSTRTDATD(String s) {
if (!s.trim().isEmpty()) {
HGSTRTDATD = Byte.parseByte(s);
} else {
HGSTRTDATD = Byte.MIN_VALUE;
}
}

protected final void initHGSTRTDATHH(String s) {
if (!s.trim().isEmpty()) {
HGSTRTDATHH = Byte.parseByte(s);
} else {
HGSTRTDATHH = Byte.MIN_VALUE;
}
}

protected final void initHGSTRTDATM(String s) {
if (!s.trim().isEmpty()) {
HGSTRTDATM = Byte.parseByte(s);
} else {
HGSTRTDATM = Byte.MIN_VALUE;
}
}

protected final void initHGSTRTDATMM(String s) {
if (!s.trim().isEmpty()) {
HGSTRTDATMM = Byte.parseByte(s);
} else {
HGSTRTDATMM = Byte.MIN_VALUE;
}
}

protected final void initHGSTRTDATSS(String s) {
if (!s.trim().isEmpty()) {
HGSTRTDATSS = Byte.parseByte(s);
} else {
HGSTRTDATSS = Byte.MIN_VALUE;
}
}

protected final void initHGSTRTDATY(String s) {
if (!s.trim().isEmpty()) {
HGSTRTDATY = Short.parseShort(s);
} else {
HGSTRTDATY = Short.MIN_VALUE;
}
}

protected final void initHHDENUB_XW(String s) {
if (!s.trim().isEmpty()) {
HHDENUB_XW = Double.parseDouble(s);
} else {
HHDENUB_XW = Double.NaN;
}
}

protected final void initHHDENUI_XW(String s) {
if (!s.trim().isEmpty()) {
HHDENUI_XW = Double.parseDouble(s);
} else {
HHDENUI_XW = Double.NaN;
}
}

protected final void initHHINTLANG(String s) {
if (!s.trim().isEmpty()) {
HHINTLANG = Byte.parseByte(s);
} else {
HHINTLANG = Byte.MIN_VALUE;
}
}

protected final void initHHLANG(String s) {
if (!s.trim().isEmpty()) {
HHLANG = Byte.parseByte(s);
} else {
HHLANG = Byte.MIN_VALUE;
}
}

protected final void initHHOLDMODEDV(String s) {
if (!s.trim().isEmpty()) {
HHOLDMODEDV = Byte.parseByte(s);
} else {
HHOLDMODEDV = Byte.MIN_VALUE;
}
}

protected final void initHHORIG(String s) {
if (!s.trim().isEmpty()) {
HHORIG = Byte.parseByte(s);
} else {
HHORIG = Byte.MIN_VALUE;
}
}

protected final void initHHQREF1(String s) {
if (!s.trim().isEmpty()) {
HHQREF1 = Byte.parseByte(s);
} else {
HHQREF1 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF10(String s) {
if (!s.trim().isEmpty()) {
HHQREF10 = Byte.parseByte(s);
} else {
HHQREF10 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF11(String s) {
if (!s.trim().isEmpty()) {
HHQREF11 = Byte.parseByte(s);
} else {
HHQREF11 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF12(String s) {
if (!s.trim().isEmpty()) {
HHQREF12 = Byte.parseByte(s);
} else {
HHQREF12 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF13(String s) {
if (!s.trim().isEmpty()) {
HHQREF13 = Byte.parseByte(s);
} else {
HHQREF13 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF14(String s) {
if (!s.trim().isEmpty()) {
HHQREF14 = Byte.parseByte(s);
} else {
HHQREF14 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF15(String s) {
if (!s.trim().isEmpty()) {
HHQREF15 = Byte.parseByte(s);
} else {
HHQREF15 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF16(String s) {
if (!s.trim().isEmpty()) {
HHQREF16 = Byte.parseByte(s);
} else {
HHQREF16 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF17(String s) {
if (!s.trim().isEmpty()) {
HHQREF17 = Byte.parseByte(s);
} else {
HHQREF17 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF18(String s) {
if (!s.trim().isEmpty()) {
HHQREF18 = Byte.parseByte(s);
} else {
HHQREF18 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF19(String s) {
if (!s.trim().isEmpty()) {
HHQREF19 = Byte.parseByte(s);
} else {
HHQREF19 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF2(String s) {
if (!s.trim().isEmpty()) {
HHQREF2 = Byte.parseByte(s);
} else {
HHQREF2 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF20(String s) {
if (!s.trim().isEmpty()) {
HHQREF20 = Byte.parseByte(s);
} else {
HHQREF20 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF21(String s) {
if (!s.trim().isEmpty()) {
HHQREF21 = Byte.parseByte(s);
} else {
HHQREF21 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF22(String s) {
if (!s.trim().isEmpty()) {
HHQREF22 = Byte.parseByte(s);
} else {
HHQREF22 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF23(String s) {
if (!s.trim().isEmpty()) {
HHQREF23 = Byte.parseByte(s);
} else {
HHQREF23 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF24(String s) {
if (!s.trim().isEmpty()) {
HHQREF24 = Byte.parseByte(s);
} else {
HHQREF24 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF25(String s) {
if (!s.trim().isEmpty()) {
HHQREF25 = Byte.parseByte(s);
} else {
HHQREF25 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF26(String s) {
if (!s.trim().isEmpty()) {
HHQREF26 = Byte.parseByte(s);
} else {
HHQREF26 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF27(String s) {
if (!s.trim().isEmpty()) {
HHQREF27 = Byte.parseByte(s);
} else {
HHQREF27 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF28(String s) {
if (!s.trim().isEmpty()) {
HHQREF28 = Byte.parseByte(s);
} else {
HHQREF28 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF29(String s) {
if (!s.trim().isEmpty()) {
HHQREF29 = Byte.parseByte(s);
} else {
HHQREF29 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF3(String s) {
if (!s.trim().isEmpty()) {
HHQREF3 = Byte.parseByte(s);
} else {
HHQREF3 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF30(String s) {
if (!s.trim().isEmpty()) {
HHQREF30 = Byte.parseByte(s);
} else {
HHQREF30 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF31(String s) {
if (!s.trim().isEmpty()) {
HHQREF31 = Byte.parseByte(s);
} else {
HHQREF31 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF32(String s) {
if (!s.trim().isEmpty()) {
HHQREF32 = Byte.parseByte(s);
} else {
HHQREF32 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF4(String s) {
if (!s.trim().isEmpty()) {
HHQREF4 = Byte.parseByte(s);
} else {
HHQREF4 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF5(String s) {
if (!s.trim().isEmpty()) {
HHQREF5 = Byte.parseByte(s);
} else {
HHQREF5 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF6(String s) {
if (!s.trim().isEmpty()) {
HHQREF6 = Byte.parseByte(s);
} else {
HHQREF6 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF7(String s) {
if (!s.trim().isEmpty()) {
HHQREF7 = Byte.parseByte(s);
} else {
HHQREF7 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF8(String s) {
if (!s.trim().isEmpty()) {
HHQREF8 = Byte.parseByte(s);
} else {
HHQREF8 = Byte.MIN_VALUE;
}
}

protected final void initHHQREF9(String s) {
if (!s.trim().isEmpty()) {
HHQREF9 = Byte.parseByte(s);
} else {
HHQREF9 = Byte.MIN_VALUE;
}
}

protected final void initHHQURECOMPLETE(String s) {
if (!s.trim().isEmpty()) {
HHQURECOMPLETE = Byte.parseByte(s);
} else {
HHQURECOMPLETE = Byte.MIN_VALUE;
}
}

protected final void initHHRESP_DV(String s) {
if (!s.trim().isEmpty()) {
HHRESP_DV = Byte.parseByte(s);
} else {
HHRESP_DV = Byte.MIN_VALUE;
}
}

protected final void initHHTYPE_DV(String s) {
if (!s.trim().isEmpty()) {
HHTYPE_DV = Byte.parseByte(s);
} else {
HHTYPE_DV = Byte.MIN_VALUE;
}
}

protected final void initHIENDDATD(String s) {
if (!s.trim().isEmpty()) {
HIENDDATD = Byte.parseByte(s);
} else {
HIENDDATD = Byte.MIN_VALUE;
}
}

protected final void initHIENDDATHH(String s) {
if (!s.trim().isEmpty()) {
HIENDDATHH = Byte.parseByte(s);
} else {
HIENDDATHH = Byte.MIN_VALUE;
}
}

protected final void initHIENDDATM(String s) {
if (!s.trim().isEmpty()) {
HIENDDATM = Byte.parseByte(s);
} else {
HIENDDATM = Byte.MIN_VALUE;
}
}

protected final void initHIENDDATMM(String s) {
if (!s.trim().isEmpty()) {
HIENDDATMM = Byte.parseByte(s);
} else {
HIENDDATMM = Byte.MIN_VALUE;
}
}

protected final void initHIENDDATSS(String s) {
if (!s.trim().isEmpty()) {
HIENDDATSS = Byte.parseByte(s);
} else {
HIENDDATSS = Byte.MIN_VALUE;
}
}

protected final void initHIENDDATY(String s) {
if (!s.trim().isEmpty()) {
HIENDDATY = Short.parseShort(s);
} else {
HIENDDATY = Short.MIN_VALUE;
}
}

protected final void initHISTRTDATD(String s) {
if (!s.trim().isEmpty()) {
HISTRTDATD = Byte.parseByte(s);
} else {
HISTRTDATD = Byte.MIN_VALUE;
}
}

protected final void initHISTRTDATHH(String s) {
if (!s.trim().isEmpty()) {
HISTRTDATHH = Byte.parseByte(s);
} else {
HISTRTDATHH = Byte.MIN_VALUE;
}
}

protected final void initHISTRTDATM(String s) {
if (!s.trim().isEmpty()) {
HISTRTDATM = Byte.parseByte(s);
} else {
HISTRTDATM = Byte.MIN_VALUE;
}
}

protected final void initHISTRTDATMM(String s) {
if (!s.trim().isEmpty()) {
HISTRTDATMM = Byte.parseByte(s);
} else {
HISTRTDATMM = Byte.MIN_VALUE;
}
}

protected final void initHISTRTDATY(String s) {
if (!s.trim().isEmpty()) {
HISTRTDATY = Short.parseShort(s);
} else {
HISTRTDATY = Short.MIN_VALUE;
}
}

protected final void initHLIENG(String s) {
if (!s.trim().isEmpty()) {
HLIENG = Byte.parseByte(s);
} else {
HLIENG = Byte.MIN_VALUE;
}
}

protected final void initHLITRANS(String s) {
if (!s.trim().isEmpty()) {
HLITRANS = Byte.parseByte(s);
} else {
HLITRANS = Byte.MIN_VALUE;
}
}

protected final void initHLIWHO(String s) {
if (!s.trim().isEmpty()) {
HLIWHO = Byte.parseByte(s);
} else {
HLIWHO = Byte.MIN_VALUE;
}
}

protected final void initHOUSCOST1_DV(String s) {
if (!s.trim().isEmpty()) {
HOUSCOST1_DV = Double.parseDouble(s);
} else {
HOUSCOST1_DV = Double.NaN;
}
}

protected final void initHOUSCOST2_DV(String s) {
if (!s.trim().isEmpty()) {
HOUSCOST2_DV = Double.parseDouble(s);
} else {
HOUSCOST2_DV = Double.NaN;
}
}

protected final void initHRPID(String s) {
if (!s.trim().isEmpty()) {
HRPID = Integer.parseInt(s);
} else {
HRPID = Integer.MIN_VALUE;
}
}

protected final void initHRPNO(String s) {
if (!s.trim().isEmpty()) {
HRPNO = Byte.parseByte(s);
} else {
HRPNO = Byte.MIN_VALUE;
}
}

protected final void initHSBEDS(String s) {
if (!s.trim().isEmpty()) {
HSBEDS = Byte.parseByte(s);
} else {
HSBEDS = Byte.MIN_VALUE;
}
}

protected final void initHSCTAX(String s) {
if (!s.trim().isEmpty()) {
HSCTAX = Short.parseShort(s);
} else {
HSCTAX = Short.MIN_VALUE;
}
}

protected final void initHSOWND(String s) {
if (!s.trim().isEmpty()) {
HSOWND = Byte.parseByte(s);
} else {
HSOWND = Byte.MIN_VALUE;
}
}

protected final void initHSOWNDCHK(String s) {
if (!s.trim().isEmpty()) {
HSOWNDCHK = Byte.parseByte(s);
} else {
HSOWNDCHK = Byte.MIN_VALUE;
}
}

protected final void initHSOWR111(String s) {
if (!s.trim().isEmpty()) {
HSOWR111 = Short.parseShort(s);
} else {
HSOWR111 = Short.MIN_VALUE;
}
}

protected final void initHSOWR112(String s) {
if (!s.trim().isEmpty()) {
HSOWR112 = Short.parseShort(s);
} else {
HSOWR112 = Short.MIN_VALUE;
}
}

protected final void initHSOWR113(String s) {
if (!s.trim().isEmpty()) {
HSOWR113 = Byte.parseByte(s);
} else {
HSOWR113 = Byte.MIN_VALUE;
}
}

protected final void initHSOWR114(String s) {
if (!s.trim().isEmpty()) {
HSOWR114 = Byte.parseByte(s);
} else {
HSOWR114 = Byte.MIN_VALUE;
}
}

protected final void initHSOWR115(String s) {
if (!s.trim().isEmpty()) {
HSOWR115 = Byte.parseByte(s);
} else {
HSOWR115 = Byte.MIN_VALUE;
}
}

protected final void initHSOWR116(String s) {
if (!s.trim().isEmpty()) {
HSOWR116 = Byte.parseByte(s);
} else {
HSOWR116 = Byte.MIN_VALUE;
}
}

protected final void initHSROOMCHK(String s) {
if (!s.trim().isEmpty()) {
HSROOMCHK = Byte.parseByte(s);
} else {
HSROOMCHK = Byte.MIN_VALUE;
}
}

protected final void initHSROOMS(String s) {
if (!s.trim().isEmpty()) {
HSROOMS = Byte.parseByte(s);
} else {
HSROOMS = Byte.MIN_VALUE;
}
}

protected final void initHSTOTMG(String s) {
if (!s.trim().isEmpty()) {
HSTOTMG = Integer.parseInt(s);
} else {
HSTOTMG = Integer.MIN_VALUE;
}
}

protected final void initIEMB(String s) {
if (!s.trim().isEmpty()) {
IEMB = Byte.parseByte(s);
} else {
IEMB = Byte.MIN_VALUE;
}
}

protected final void initIEQMOECD_DV(String s) {
if (!s.trim().isEmpty()) {
IEQMOECD_DV = Double.parseDouble(s);
} else {
IEQMOECD_DV = Double.NaN;
}
}

protected final void initINTDATEY(String s) {
if (!s.trim().isEmpty()) {
INTDATEY = Short.parseShort(s);
} else {
INTDATEY = Short.MIN_VALUE;
}
}

protected final void initINTNUM(String s) {
if (!s.trim().isEmpty()) {
INTNUM = Integer.parseInt(s);
} else {
INTNUM = Integer.MIN_VALUE;
}
}

protected final void initIVFHO(String s) {
if (!s.trim().isEmpty()) {
IVFHO = Short.parseShort(s);
} else {
IVFHO = Short.MIN_VALUE;
}
}

protected final void initIVH0(String s) {
if (!s.trim().isEmpty()) {
IVH0 = Short.parseShort(s);
} else {
IVH0 = Short.MIN_VALUE;
}
}

protected final void initIVH11(String s) {
if (!s.trim().isEmpty()) {
IVH11 = Short.parseShort(s);
} else {
IVH11 = Short.MIN_VALUE;
}
}

protected final void initIVH12(String s) {
if (!s.trim().isEmpty()) {
IVH12 = Short.parseShort(s);
} else {
IVH12 = Short.MIN_VALUE;
}
}

protected final void initIVH13(String s) {
if (!s.trim().isEmpty()) {
IVH13 = Byte.parseByte(s);
} else {
IVH13 = Byte.MIN_VALUE;
}
}

protected final void initIVH14(String s) {
if (!s.trim().isEmpty()) {
IVH14 = Byte.parseByte(s);
} else {
IVH14 = Byte.MIN_VALUE;
}
}

protected final void initIVH15(String s) {
if (!s.trim().isEmpty()) {
IVH15 = Byte.parseByte(s);
} else {
IVH15 = Byte.MIN_VALUE;
}
}

protected final void initIVH16(String s) {
if (!s.trim().isEmpty()) {
IVH16 = Byte.parseByte(s);
} else {
IVH16 = Byte.MIN_VALUE;
}
}

protected final void initMGEXTRA(String s) {
if (!s.trim().isEmpty()) {
MGEXTRA = Short.parseShort(s);
} else {
MGEXTRA = Short.MIN_VALUE;
}
}

protected final void initMGNEW(String s) {
if (!s.trim().isEmpty()) {
MGNEW = Integer.parseInt(s);
} else {
MGNEW = Integer.MIN_VALUE;
}
}

protected final void initMGOLD(String s) {
if (!s.trim().isEmpty()) {
MGOLD = Integer.parseInt(s);
} else {
MGOLD = Integer.MIN_VALUE;
}
}

protected final void initMGTYPE(String s) {
if (!s.trim().isEmpty()) {
MGTYPE = Byte.parseByte(s);
} else {
MGTYPE = Byte.MIN_VALUE;
}
}

protected final void initMGXTY1(String s) {
if (!s.trim().isEmpty()) {
MGXTY1 = Short.parseShort(s);
} else {
MGXTY1 = Short.MIN_VALUE;
}
}

protected final void initMGXTY2(String s) {
if (!s.trim().isEmpty()) {
MGXTY2 = Short.parseShort(s);
} else {
MGXTY2 = Short.MIN_VALUE;
}
}

protected final void initMGXTY3(String s) {
if (!s.trim().isEmpty()) {
MGXTY3 = Short.parseShort(s);
} else {
MGXTY3 = Short.MIN_VALUE;
}
}

protected final void initMGXTY4(String s) {
if (!s.trim().isEmpty()) {
MGXTY4 = Short.parseShort(s);
} else {
MGXTY4 = Short.MIN_VALUE;
}
}

protected final void initMGXTY5(String s) {
if (!s.trim().isEmpty()) {
MGXTY5 = Byte.parseByte(s);
} else {
MGXTY5 = Byte.MIN_VALUE;
}
}

protected final void initMGXTY6(String s) {
if (!s.trim().isEmpty()) {
MGXTY6 = Byte.parseByte(s);
} else {
MGXTY6 = Byte.MIN_VALUE;
}
}

protected final void initMGXTY97(String s) {
if (!s.trim().isEmpty()) {
MGXTY97 = Byte.parseByte(s);
} else {
MGXTY97 = Byte.MIN_VALUE;
}
}

protected final void initMGYNOT(String s) {
if (!s.trim().isEmpty()) {
MGYNOT = Byte.parseByte(s);
} else {
MGYNOT = Byte.MIN_VALUE;
}
}

protected final void initMONTH(String s) {
if (!s.trim().isEmpty()) {
MONTH = Byte.parseByte(s);
} else {
MONTH = Byte.MIN_VALUE;
}
}

protected final void initMORES(String s) {
if (!s.trim().isEmpty()) {
MORES = Byte.parseByte(s);
} else {
MORES = Byte.MIN_VALUE;
}
}

protected final void initN10TO15(String s) {
if (!s.trim().isEmpty()) {
N10TO15 = Byte.parseByte(s);
} else {
N10TO15 = Byte.MIN_VALUE;
}
}

protected final void initNADOECD_DV(String s) {
if (!s.trim().isEmpty()) {
NADOECD_DV = Byte.parseByte(s);
} else {
NADOECD_DV = Byte.MIN_VALUE;
}
}

protected final void initNCARS(String s) {
if (!s.trim().isEmpty()) {
NCARS = Byte.parseByte(s);
} else {
NCARS = Byte.MIN_VALUE;
}
}

protected final void initNCHOECD_DV(String s) {
if (!s.trim().isEmpty()) {
NCHOECD_DV = Byte.parseByte(s);
} else {
NCHOECD_DV = Byte.MIN_VALUE;
}
}

protected final void initNCOUPLE_DV(String s) {
if (!s.trim().isEmpty()) {
NCOUPLE_DV = Short.parseShort(s);
} else {
NCOUPLE_DV = Short.MIN_VALUE;
}
}

protected final void initNKIDS015(String s) {
if (!s.trim().isEmpty()) {
NKIDS015 = Byte.parseByte(s);
} else {
NKIDS015 = Byte.MIN_VALUE;
}
}

protected final void initNKIDS05(String s) {
if (!s.trim().isEmpty()) {
NKIDS05 = Byte.parseByte(s);
} else {
NKIDS05 = Byte.MIN_VALUE;
}
}

protected final void initNKIDS615(String s) {
if (!s.trim().isEmpty()) {
NKIDS615 = Byte.parseByte(s);
} else {
NKIDS615 = Byte.MIN_VALUE;
}
}

protected final void initNPENSIONER(String s) {
if (!s.trim().isEmpty()) {
NPENSIONER = Byte.parseByte(s);
} else {
NPENSIONER = Byte.MIN_VALUE;
}
}

protected final void initNPENSIONER_DV(String s) {
if (!s.trim().isEmpty()) {
NPENSIONER_DV = Byte.parseByte(s);
} else {
NPENSIONER_DV = Byte.MIN_VALUE;
}
}

protected final void initNUE_DV(String s) {
if (!s.trim().isEmpty()) {
NUE_DV = Byte.parseByte(s);
} else {
NUE_DV = Byte.MIN_VALUE;
}
}

protected final void initNWAGE_DV(String s) {
if (!s.trim().isEmpty()) {
NWAGE_DV = Short.parseShort(s);
} else {
NWAGE_DV = Short.MIN_VALUE;
}
}

protected final void initORIGADD(String s) {
if (!s.trim().isEmpty()) {
ORIGADD = Byte.parseByte(s);
} else {
ORIGADD = Byte.MIN_VALUE;
}
}

protected final void initOUTCOME(String s) {
if (!s.trim().isEmpty()) {
OUTCOME = Short.parseShort(s);
} else {
OUTCOME = Short.MIN_VALUE;
}
}

protected final void initPCBROAD(String s) {
if (!s.trim().isEmpty()) {
PCBROAD = Byte.parseByte(s);
} else {
PCBROAD = Byte.MIN_VALUE;
}
}

protected final void initPCHAS(String s) {
if (!s.trim().isEmpty()) {
PCHAS = Byte.parseByte(s);
} else {
PCHAS = Byte.MIN_VALUE;
}
}

protected final void initPCNET(String s) {
if (!s.trim().isEmpty()) {
PCNET = Short.parseShort(s);
} else {
PCNET = Short.MIN_VALUE;
}
}

protected final void initPSU(String s) {
if (!s.trim().isEmpty()) {
PSU = Integer.parseInt(s);
} else {
PSU = Integer.MIN_VALUE;
}
}

protected final void initQUARTER(String s) {
if (!s.trim().isEmpty()) {
QUARTER = Byte.parseByte(s);
} else {
QUARTER = Byte.MIN_VALUE;
}
}

protected final void initRENTG(String s) {
if (!s.trim().isEmpty()) {
RENTG = Short.parseShort(s);
} else {
RENTG = Short.MIN_VALUE;
}
}

protected final void initRENTGRS_DV(String s) {
if (!s.trim().isEmpty()) {
RENTGRS_DV = Double.parseDouble(s);
} else {
RENTGRS_DV = Double.NaN;
}
}

protected final void initRENTGRS_IF(String s) {
if (!s.trim().isEmpty()) {
RENTGRS_IF = Byte.parseByte(s);
} else {
RENTGRS_IF = Byte.MIN_VALUE;
}
}

protected final void initRENTHB(String s) {
if (!s.trim().isEmpty()) {
RENTHB = Byte.parseByte(s);
} else {
RENTHB = Byte.MIN_VALUE;
}
}

protected final void initRENTINC1(String s) {
if (!s.trim().isEmpty()) {
RENTINC1 = Byte.parseByte(s);
} else {
RENTINC1 = Byte.MIN_VALUE;
}
}

protected final void initRENTINC2(String s) {
if (!s.trim().isEmpty()) {
RENTINC2 = Byte.parseByte(s);
} else {
RENTINC2 = Byte.MIN_VALUE;
}
}

protected final void initRENTINC3(String s) {
if (!s.trim().isEmpty()) {
RENTINC3 = Byte.parseByte(s);
} else {
RENTINC3 = Byte.MIN_VALUE;
}
}

protected final void initRENTINC96(String s) {
if (!s.trim().isEmpty()) {
RENTINC96 = Byte.parseByte(s);
} else {
RENTINC96 = Byte.MIN_VALUE;
}
}

protected final void initRENTP11(String s) {
if (!s.trim().isEmpty()) {
RENTP11 = Short.parseShort(s);
} else {
RENTP11 = Short.MIN_VALUE;
}
}

protected final void initRENTP12(String s) {
if (!s.trim().isEmpty()) {
RENTP12 = Short.parseShort(s);
} else {
RENTP12 = Short.MIN_VALUE;
}
}

protected final void initRENTP13(String s) {
if (!s.trim().isEmpty()) {
RENTP13 = Byte.parseByte(s);
} else {
RENTP13 = Byte.MIN_VALUE;
}
}

protected final void initRENTP14(String s) {
if (!s.trim().isEmpty()) {
RENTP14 = Byte.parseByte(s);
} else {
RENTP14 = Byte.MIN_VALUE;
}
}

protected final void initRENTP15(String s) {
if (!s.trim().isEmpty()) {
RENTP15 = Byte.parseByte(s);
} else {
RENTP15 = Byte.MIN_VALUE;
}
}

protected final void initRENTP16(String s) {
if (!s.trim().isEmpty()) {
RENTP16 = Byte.parseByte(s);
} else {
RENTP16 = Byte.MIN_VALUE;
}
}

protected final void initRENTWC(String s) {
if (!s.trim().isEmpty()) {
RENTWC = Byte.parseByte(s);
} else {
RENTWC = Byte.MIN_VALUE;
}
}

protected final void initRENT_DV(String s) {
if (!s.trim().isEmpty()) {
RENT_DV = Double.parseDouble(s);
} else {
RENT_DV = Double.NaN;
}
}

protected final void initRINGFENCE(String s) {
if (!s.trim().isEmpty()) {
byte b = Byte.parseByte(s);
if (b == 0) {
RINGFENCE = false;
} else {
RINGFENCE = true;
}
}
}

protected final void initSTRATA(String s) {
if (!s.trim().isEmpty()) {
STRATA = Short.parseShort(s);
} else {
STRATA = Short.MIN_VALUE;
}
}

protected final void initTENURE_DV(String s) {
if (!s.trim().isEmpty()) {
TENURE_DV = Short.parseShort(s);
} else {
TENURE_DV = Short.MIN_VALUE;
}
}

protected final void initURBAN_DV(String s) {
if (!s.trim().isEmpty()) {
URBAN_DV = Byte.parseByte(s);
} else {
URBAN_DV = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE1(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE1 = Byte.parseByte(s);
} else {
WHODRIVE1 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE2(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE2 = Byte.parseByte(s);
} else {
WHODRIVE2 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE3(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE3 = Byte.parseByte(s);
} else {
WHODRIVE3 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE4(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE4 = Byte.parseByte(s);
} else {
WHODRIVE4 = Byte.MIN_VALUE;
}
}

protected final void initWHODRIVE5(String s) {
if (!s.trim().isEmpty()) {
WHODRIVE5 = Byte.parseByte(s);
} else {
WHODRIVE5 = Byte.MIN_VALUE;
}
}

protected final void initXPALTOB_G3(String s) {
if (!s.trim().isEmpty()) {
XPALTOB_G3 = Short.parseShort(s);
} else {
XPALTOB_G3 = Short.MIN_VALUE;
}
}

protected final void initXPDUELY(String s) {
if (!s.trim().isEmpty()) {
XPDUELY = Short.parseShort(s);
} else {
XPDUELY = Short.MIN_VALUE;
}
}

protected final void initXPELECY(String s) {
if (!s.trim().isEmpty()) {
XPELECY = Short.parseShort(s);
} else {
XPELECY = Short.MIN_VALUE;
}
}

protected final void initXPFDOUT_G3(String s) {
if (!s.trim().isEmpty()) {
XPFDOUT_G3 = Short.parseShort(s);
} else {
XPFDOUT_G3 = Short.MIN_VALUE;
}
}

protected final void initXPFOOD1_G3(String s) {
if (!s.trim().isEmpty()) {
XPFOOD1_G3 = Short.parseShort(s);
} else {
XPFOOD1_G3 = Short.MIN_VALUE;
}
}

protected final void initXPGASY(String s) {
if (!s.trim().isEmpty()) {
XPGASY = Short.parseShort(s);
} else {
XPGASY = Short.MIN_VALUE;
}
}

protected final void initXPHSDBA(String s) {
if (!s.trim().isEmpty()) {
XPHSDBA = Byte.parseByte(s);
} else {
XPHSDBA = Byte.MIN_VALUE;
}
}

protected final void initXPHSDCT(String s) {
if (!s.trim().isEmpty()) {
XPHSDCT = Byte.parseByte(s);
} else {
XPHSDCT = Byte.MIN_VALUE;
}
}

protected final void initXPMDV(String s) {
if (!s.trim().isEmpty()) {
XPMDV = Double.parseDouble(s);
} else {
XPMDV = Double.NaN;
}
}

protected final void initXPMGINT_DV(String s) {
if (!s.trim().isEmpty()) {
XPMGINT_DV = Double.parseDouble(s);
} else {
XPMGINT_DV = Double.NaN;
}
}

protected final void initXPMIF(String s) {
if (!s.trim().isEmpty()) {
XPMIF = Byte.parseByte(s);
} else {
XPMIF = Byte.MIN_VALUE;
}
}

protected final void initXPOILY(String s) {
if (!s.trim().isEmpty()) {
XPOILY = Short.parseShort(s);
} else {
XPOILY = Short.MIN_VALUE;
}
}

protected final void initXPSFLY(String s) {
if (!s.trim().isEmpty()) {
XPSFLY = Short.parseShort(s);
} else {
XPSFLY = Short.MIN_VALUE;
}
}

public byte getADDRCHCK() {
return ADDRCHCK;
}

public byte getCARAGE1() {
return CARAGE1;
}

public byte getCARAGE2() {
return CARAGE2;
}

public byte getCARAGE3() {
return CARAGE3;
}

public byte getCARAGE4() {
return CARAGE4;
}

public byte getCARAGE5() {
return CARAGE5;
}

public byte getCARFUEL1() {
return CARFUEL1;
}

public byte getCARFUEL2() {
return CARFUEL2;
}

public byte getCARFUEL3() {
return CARFUEL3;
}

public byte getCARFUEL4() {
return CARFUEL4;
}

public byte getCARFUEL5() {
return CARFUEL5;
}

public byte getCARN2H1() {
return CARN2H1;
}

public byte getCARN2H2() {
return CARN2H2;
}

public byte getCARN2H3() {
return CARN2H3;
}

public byte getCARN2H4() {
return CARN2H4;
}

public byte getCARN2H5() {
return CARN2H5;
}

public int getCARVAL() {
return CARVAL;
}

public short getCDUSE10() {
return CDUSE10;
}

public short getCDUSE11() {
return CDUSE11;
}

public short getCDUSE12() {
return CDUSE12;
}

public byte getCDUSE13() {
return CDUSE13;
}

public short getCDUSE3() {
return CDUSE3;
}

public short getCDUSE4() {
return CDUSE4;
}

public byte getCDUSE5() {
return CDUSE5;
}

public byte getCDUSE7() {
return CDUSE7;
}

public byte getCORDET1() {
return CORDET1;
}

public byte getCORDET10() {
return CORDET10;
}

public byte getCORDET11() {
return CORDET11;
}

public byte getCORDET12() {
return CORDET12;
}

public byte getCORDET13() {
return CORDET13;
}

public byte getCORDET14() {
return CORDET14;
}

public byte getCORDET15() {
return CORDET15;
}

public byte getCORDET16() {
return CORDET16;
}

public byte getCORDET17() {
return CORDET17;
}

public byte getCORDET18() {
return CORDET18;
}

public byte getCORDET19() {
return CORDET19;
}

public byte getCORDET2() {
return CORDET2;
}

public byte getCORDET20() {
return CORDET20;
}

public byte getCORDET21() {
return CORDET21;
}

public byte getCORDET22() {
return CORDET22;
}

public byte getCORDET23() {
return CORDET23;
}

public byte getCORDET24() {
return CORDET24;
}

public byte getCORDET25() {
return CORDET25;
}

public byte getCORDET26() {
return CORDET26;
}

public byte getCORDET27() {
return CORDET27;
}

public byte getCORDET28() {
return CORDET28;
}

public byte getCORDET29() {
return CORDET29;
}

public byte getCORDET3() {
return CORDET3;
}

public byte getCORDET30() {
return CORDET30;
}

public byte getCORDET31() {
return CORDET31;
}

public byte getCORDET32() {
return CORDET32;
}

public byte getCORDET4() {
return CORDET4;
}

public byte getCORDET5() {
return CORDET5;
}

public byte getCORDET6() {
return CORDET6;
}

public byte getCORDET7() {
return CORDET7;
}

public byte getCORDET8() {
return CORDET8;
}

public byte getCORDET9() {
return CORDET9;
}

public byte getCORDET96() {
return CORDET96;
}

public byte getCORESWHO1() {
return CORESWHO1;
}

public byte getCORESWHO10() {
return CORESWHO10;
}

public byte getCORESWHO11() {
return CORESWHO11;
}

public byte getCORESWHO12() {
return CORESWHO12;
}

public byte getCORESWHO13() {
return CORESWHO13;
}

public byte getCORESWHO14() {
return CORESWHO14;
}

public byte getCORESWHO15() {
return CORESWHO15;
}

public byte getCORESWHO16() {
return CORESWHO16;
}

public byte getCORESWHO2() {
return CORESWHO2;
}

public byte getCORESWHO3() {
return CORESWHO3;
}

public byte getCORESWHO4() {
return CORESWHO4;
}

public byte getCORESWHO5() {
return CORESWHO5;
}

public byte getCORESWHO6() {
return CORESWHO6;
}

public byte getCORESWHO7() {
return CORESWHO7;
}

public byte getCORESWHO8() {
return CORESWHO8;
}

public byte getCORESWHO9() {
return CORESWHO9;
}

public byte getCORESWHO96() {
return CORESWHO96;
}

public byte getCOUNTRY() {
return COUNTRY;
}

public byte getDUELPAY() {
return DUELPAY;
}

public byte getELECPAY() {
return ELECPAY;
}

public byte getENSZE1() {
return ENSZE1;
}

public byte getENSZE2() {
return ENSZE2;
}

public byte getENSZE3() {
return ENSZE3;
}

public byte getENSZE4() {
return ENSZE4;
}

public byte getENSZE5() {
return ENSZE5;
}

public boolean getFBORN() {
return FBORN;
}

public byte getFF_HSBEDS() {
return FF_HSBEDS;
}

public byte getFF_HSOWND() {
return FF_HSOWND;
}

public byte getFF_HSROOMS() {
return FF_HSROOMS;
}

protected double FIHHMNGRS1_DV() {
return FIHHMNGRS1_DV;
}

protected double FIHHMNGRS_IF() {
return FIHHMNGRS_IF;
}

public byte getFIHHMNGRS_TC() {
return FIHHMNGRS_TC;
}

protected double FIHHMNINV_DV() {
return FIHHMNINV_DV;
}

protected double FIHHMNLABGRS_DV() {
return FIHHMNLABGRS_DV;
}

public byte getFIHHMNLABGRS_TC() {
return FIHHMNLABGRS_TC;
}

protected double FIHHMNLABNET_DV() {
return FIHHMNLABNET_DV;
}

protected double FIHHMNMISC_DV() {
return FIHHMNMISC_DV;
}

protected double FIHHMNNET1_DV() {
return FIHHMNNET1_DV;
}

protected double FIHHMNPEN_DV() {
return FIHHMNPEN_DV;
}

protected double FIHHMNPRBEN_DV() {
return FIHHMNPRBEN_DV;
}

protected double FIHHMNSBEN_DV() {
return FIHHMNSBEN_DV;
}

public byte getFIHHNEGSEI_IF() {
return FIHHNEGSEI_IF;
}

public byte getFUELDUEL() {
return FUELDUEL;
}

public byte getFUELHAVE1() {
return FUELHAVE1;
}

public byte getFUELHAVE2() {
return FUELHAVE2;
}

public byte getFUELHAVE3() {
return FUELHAVE3;
}

public byte getFUELHAVE4() {
return FUELHAVE4;
}

public byte getFUELHAVE96() {
return FUELHAVE96;
}

public byte getGASPAY() {
return GASPAY;
}

protected double HBADJUST_DV() {
return HBADJUST_DV;
}

public byte getHGENDDATD() {
return HGENDDATD;
}

public byte getHGENDDATHH() {
return HGENDDATHH;
}

public byte getHGENDDATM() {
return HGENDDATM;
}

public byte getHGENDDATMM() {
return HGENDDATMM;
}

public byte getHGENDDATSS() {
return HGENDDATSS;
}

public short getHGENDDATY() {
return HGENDDATY;
}

public byte getHGLIENG() {
return HGLIENG;
}

public byte getHGLITRANS() {
return HGLITRANS;
}

public byte getHGSTRTDATD() {
return HGSTRTDATD;
}

public byte getHGSTRTDATHH() {
return HGSTRTDATHH;
}

public byte getHGSTRTDATM() {
return HGSTRTDATM;
}

public byte getHGSTRTDATMM() {
return HGSTRTDATMM;
}

public byte getHGSTRTDATSS() {
return HGSTRTDATSS;
}

public short getHGSTRTDATY() {
return HGSTRTDATY;
}

protected double HHDENUB_XW() {
return HHDENUB_XW;
}

protected double HHDENUI_XW() {
return HHDENUI_XW;
}

public byte getHHINTLANG() {
return HHINTLANG;
}

public byte getHHLANG() {
return HHLANG;
}

public byte getHHOLDMODEDV() {
return HHOLDMODEDV;
}

public byte getHHORIG() {
return HHORIG;
}

public byte getHHQREF1() {
return HHQREF1;
}

public byte getHHQREF10() {
return HHQREF10;
}

public byte getHHQREF11() {
return HHQREF11;
}

public byte getHHQREF12() {
return HHQREF12;
}

public byte getHHQREF13() {
return HHQREF13;
}

public byte getHHQREF14() {
return HHQREF14;
}

public byte getHHQREF15() {
return HHQREF15;
}

public byte getHHQREF16() {
return HHQREF16;
}

public byte getHHQREF17() {
return HHQREF17;
}

public byte getHHQREF18() {
return HHQREF18;
}

public byte getHHQREF19() {
return HHQREF19;
}

public byte getHHQREF2() {
return HHQREF2;
}

public byte getHHQREF20() {
return HHQREF20;
}

public byte getHHQREF21() {
return HHQREF21;
}

public byte getHHQREF22() {
return HHQREF22;
}

public byte getHHQREF23() {
return HHQREF23;
}

public byte getHHQREF24() {
return HHQREF24;
}

public byte getHHQREF25() {
return HHQREF25;
}

public byte getHHQREF26() {
return HHQREF26;
}

public byte getHHQREF27() {
return HHQREF27;
}

public byte getHHQREF28() {
return HHQREF28;
}

public byte getHHQREF29() {
return HHQREF29;
}

public byte getHHQREF3() {
return HHQREF3;
}

public byte getHHQREF30() {
return HHQREF30;
}

public byte getHHQREF31() {
return HHQREF31;
}

public byte getHHQREF32() {
return HHQREF32;
}

public byte getHHQREF4() {
return HHQREF4;
}

public byte getHHQREF5() {
return HHQREF5;
}

public byte getHHQREF6() {
return HHQREF6;
}

public byte getHHQREF7() {
return HHQREF7;
}

public byte getHHQREF8() {
return HHQREF8;
}

public byte getHHQREF9() {
return HHQREF9;
}

public byte getHHQURECOMPLETE() {
return HHQURECOMPLETE;
}

public byte getHHRESP_DV() {
return HHRESP_DV;
}

public byte getHHTYPE_DV() {
return HHTYPE_DV;
}

public byte getHIENDDATD() {
return HIENDDATD;
}

public byte getHIENDDATHH() {
return HIENDDATHH;
}

public byte getHIENDDATM() {
return HIENDDATM;
}

public byte getHIENDDATMM() {
return HIENDDATMM;
}

public byte getHIENDDATSS() {
return HIENDDATSS;
}

public short getHIENDDATY() {
return HIENDDATY;
}

public byte getHISTRTDATD() {
return HISTRTDATD;
}

public byte getHISTRTDATHH() {
return HISTRTDATHH;
}

public byte getHISTRTDATM() {
return HISTRTDATM;
}

public byte getHISTRTDATMM() {
return HISTRTDATMM;
}

public short getHISTRTDATY() {
return HISTRTDATY;
}

public byte getHLIENG() {
return HLIENG;
}

public byte getHLITRANS() {
return HLITRANS;
}

public byte getHLIWHO() {
return HLIWHO;
}

protected double HOUSCOST1_DV() {
return HOUSCOST1_DV;
}

protected double HOUSCOST2_DV() {
return HOUSCOST2_DV;
}

public int getHRPID() {
return HRPID;
}

public byte getHRPNO() {
return HRPNO;
}

public byte getHSBEDS() {
return HSBEDS;
}

public short getHSCTAX() {
return HSCTAX;
}

public byte getHSOWND() {
return HSOWND;
}

public byte getHSOWNDCHK() {
return HSOWNDCHK;
}

public short getHSOWR111() {
return HSOWR111;
}

public short getHSOWR112() {
return HSOWR112;
}

public byte getHSOWR113() {
return HSOWR113;
}

public byte getHSOWR114() {
return HSOWR114;
}

public byte getHSOWR115() {
return HSOWR115;
}

public byte getHSOWR116() {
return HSOWR116;
}

public byte getHSROOMCHK() {
return HSROOMCHK;
}

public byte getHSROOMS() {
return HSROOMS;
}

public int getHSTOTMG() {
return HSTOTMG;
}

public byte getIEMB() {
return IEMB;
}

protected double IEQMOECD_DV() {
return IEQMOECD_DV;
}

public short getINTDATEY() {
return INTDATEY;
}

public int getINTNUM() {
return INTNUM;
}

public short getIVFHO() {
return IVFHO;
}

public short getIVH0() {
return IVH0;
}

public short getIVH11() {
return IVH11;
}

public short getIVH12() {
return IVH12;
}

public byte getIVH13() {
return IVH13;
}

public byte getIVH14() {
return IVH14;
}

public byte getIVH15() {
return IVH15;
}

public byte getIVH16() {
return IVH16;
}

public short getMGEXTRA() {
return MGEXTRA;
}

public int getMGNEW() {
return MGNEW;
}

public int getMGOLD() {
return MGOLD;
}

public byte getMGTYPE() {
return MGTYPE;
}

public short getMGXTY1() {
return MGXTY1;
}

public short getMGXTY2() {
return MGXTY2;
}

public short getMGXTY3() {
return MGXTY3;
}

public short getMGXTY4() {
return MGXTY4;
}

public byte getMGXTY5() {
return MGXTY5;
}

public byte getMGXTY6() {
return MGXTY6;
}

public byte getMGXTY97() {
return MGXTY97;
}

public byte getMGYNOT() {
return MGYNOT;
}

public byte getMONTH() {
return MONTH;
}

public byte getMORES() {
return MORES;
}

public byte getN10TO15() {
return N10TO15;
}

public byte getNADOECD_DV() {
return NADOECD_DV;
}

public byte getNCARS() {
return NCARS;
}

public byte getNCHOECD_DV() {
return NCHOECD_DV;
}

public short getNCOUPLE_DV() {
return NCOUPLE_DV;
}

public byte getNKIDS015() {
return NKIDS015;
}

public byte getNKIDS05() {
return NKIDS05;
}

public byte getNKIDS615() {
return NKIDS615;
}

public byte getNPENSIONER() {
return NPENSIONER;
}

public byte getNPENSIONER_DV() {
return NPENSIONER_DV;
}

public byte getNUE_DV() {
return NUE_DV;
}

public short getNWAGE_DV() {
return NWAGE_DV;
}

public byte getORIGADD() {
return ORIGADD;
}

public short getOUTCOME() {
return OUTCOME;
}

public byte getPCBROAD() {
return PCBROAD;
}

public byte getPCHAS() {
return PCHAS;
}

public short getPCNET() {
return PCNET;
}

public int getPSU() {
return PSU;
}

public byte getQUARTER() {
return QUARTER;
}

public short getRENTG() {
return RENTG;
}

protected double RENTGRS_DV() {
return RENTGRS_DV;
}

public byte getRENTGRS_IF() {
return RENTGRS_IF;
}

public byte getRENTHB() {
return RENTHB;
}

public byte getRENTINC1() {
return RENTINC1;
}

public byte getRENTINC2() {
return RENTINC2;
}

public byte getRENTINC3() {
return RENTINC3;
}

public byte getRENTINC96() {
return RENTINC96;
}

public short getRENTP11() {
return RENTP11;
}

public short getRENTP12() {
return RENTP12;
}

public byte getRENTP13() {
return RENTP13;
}

public byte getRENTP14() {
return RENTP14;
}

public byte getRENTP15() {
return RENTP15;
}

public byte getRENTP16() {
return RENTP16;
}

public byte getRENTWC() {
return RENTWC;
}

protected double RENT_DV() {
return RENT_DV;
}

public boolean getRINGFENCE() {
return RINGFENCE;
}

public short getSTRATA() {
return STRATA;
}

public short getTENURE_DV() {
return TENURE_DV;
}

public byte getURBAN_DV() {
return URBAN_DV;
}

public byte getWHODRIVE1() {
return WHODRIVE1;
}

public byte getWHODRIVE2() {
return WHODRIVE2;
}

public byte getWHODRIVE3() {
return WHODRIVE3;
}

public byte getWHODRIVE4() {
return WHODRIVE4;
}

public byte getWHODRIVE5() {
return WHODRIVE5;
}

public short getXPALTOB_G3() {
return XPALTOB_G3;
}

public short getXPDUELY() {
return XPDUELY;
}

public short getXPELECY() {
return XPELECY;
}

public short getXPFDOUT_G3() {
return XPFDOUT_G3;
}

public short getXPFOOD1_G3() {
return XPFOOD1_G3;
}

public short getXPGASY() {
return XPGASY;
}

public byte getXPHSDBA() {
return XPHSDBA;
}

public byte getXPHSDCT() {
return XPHSDCT;
}

protected double XPMDV() {
return XPMDV;
}

protected double XPMGINT_DV() {
return XPMGINT_DV;
}

public byte getXPMIF() {
return XPMIF;
}

public short getXPOILY() {
return XPOILY;
}

public short getXPSFLY() {
return XPSFLY;
}

public US_Wave25_hhresp_Record(String line) {
s = line.split("\t");
initHIDP(s[0]);
initINTNUM(s[1]);
initHHORIG(s[2]);
initPSU(s[3]);
initSTRATA(s[4]);
initMONTH(s[5]);
initQUARTER(s[6]);
initIVFHO(s[7]);
initHGLIENG(s[8]);
initHGLITRANS(s[9]);
initADDRCHCK(s[10]);
initORIGADD(s[11]);
initCORESWHO1(s[12]);
initCORESWHO2(s[13]);
initCORESWHO3(s[14]);
initCORESWHO4(s[15]);
initCORESWHO5(s[16]);
initCORESWHO6(s[17]);
initCORESWHO7(s[18]);
initCORESWHO8(s[19]);
initCORESWHO9(s[20]);
initCORESWHO10(s[21]);
initCORESWHO11(s[22]);
initCORESWHO12(s[23]);
initCORESWHO13(s[24]);
initCORESWHO14(s[25]);
initCORESWHO15(s[26]);
initCORESWHO16(s[27]);
initCORESWHO96(s[28]);
initMORES(s[29]);
initCORDET1(s[30]);
initCORDET2(s[31]);
initCORDET3(s[32]);
initCORDET4(s[33]);
initCORDET5(s[34]);
initCORDET6(s[35]);
initCORDET7(s[36]);
initCORDET8(s[37]);
initCORDET9(s[38]);
initCORDET10(s[39]);
initCORDET11(s[40]);
initCORDET12(s[41]);
initCORDET13(s[42]);
initCORDET14(s[43]);
initCORDET15(s[44]);
initCORDET16(s[45]);
initCORDET17(s[46]);
initCORDET18(s[47]);
initCORDET19(s[48]);
initCORDET20(s[49]);
initCORDET21(s[50]);
initCORDET22(s[51]);
initCORDET23(s[52]);
initCORDET24(s[53]);
initCORDET25(s[54]);
initCORDET26(s[55]);
initCORDET27(s[56]);
initCORDET28(s[57]);
initCORDET29(s[58]);
initCORDET30(s[59]);
initCORDET31(s[60]);
initCORDET32(s[61]);
initCORDET96(s[62]);
initHHSIZE(s[63]);
initHHLANG(s[64]);
initHHQREF1(s[65]);
initHHQREF2(s[66]);
initHHQREF3(s[67]);
initHHQREF4(s[68]);
initHHQREF5(s[69]);
initHHQREF6(s[70]);
initHHQREF7(s[71]);
initHHQREF8(s[72]);
initHHQREF9(s[73]);
initHHQREF10(s[74]);
initHHQREF11(s[75]);
initHHQREF12(s[76]);
initHHQREF13(s[77]);
initHHQREF14(s[78]);
initHHQREF15(s[79]);
initHHQREF16(s[80]);
initHHQREF17(s[81]);
initHHQREF18(s[82]);
initHHQREF19(s[83]);
initHHQREF20(s[84]);
initHHQREF21(s[85]);
initHHQREF22(s[86]);
initHHQREF23(s[87]);
initHHQREF24(s[88]);
initHHQREF25(s[89]);
initHHQREF26(s[90]);
initHHQREF27(s[91]);
initHHQREF28(s[92]);
initHHQREF29(s[93]);
initHHQREF30(s[94]);
initHHQREF31(s[95]);
initHHQREF32(s[96]);
initIEMB(s[97]);
initFBORN(s[98]);
initNKIDS05(s[99]);
initNKIDS015(s[100]);
initN10TO15(s[101]);
initNKIDS615(s[102]);
initNPENSIONER(s[103]);
initHGSTRTDATY(s[104]);
initHGSTRTDATM(s[105]);
initHGSTRTDATD(s[106]);
initHGSTRTDATHH(s[107]);
initHGSTRTDATMM(s[108]);
initHGSTRTDATSS(s[109]);
initHGENDDATY(s[110]);
initHGENDDATM(s[111]);
initHGENDDATD(s[112]);
initHGENDDATHH(s[113]);
initHGENDDATMM(s[114]);
initHGENDDATSS(s[115]);
initHLIENG(s[116]);
initHLITRANS(s[117]);
initHLIWHO(s[118]);
initIVH0(s[119]);
initIVH1(s[120]);
initIVH2(s[121]);
initIVH3(s[122]);
initIVH4(s[123]);
initIVH5(s[124]);
initIVH6(s[125]);
initIVH7(s[126]);
initIVH8(s[127]);
initIVH9(s[128]);
initIVH10(s[129]);
initIVH11(s[130]);
initIVH12(s[131]);
initIVH13(s[132]);
initIVH14(s[133]);
initIVH15(s[134]);
initIVH16(s[135]);
initHISTRTDATY(s[136]);
initHISTRTDATM(s[137]);
initHISTRTDATD(s[138]);
initHISTRTDATHH(s[139]);
initHISTRTDATMM(s[140]);
initHSROOMCHK(s[141]);
initHSBEDS(s[142]);
initHSROOMS(s[143]);
initHSOWNDCHK(s[144]);
initHSOWND(s[145]);
initHSOWR10(s[146]);
initHSOWR11(s[147]);
initHSOWR12(s[148]);
initHSOWR13(s[149]);
initHSOWR14(s[150]);
initHSOWR15(s[151]);
initHSOWR16(s[152]);
initHSOWR17(s[153]);
initHSOWR18(s[154]);
initHSOWR19(s[155]);
initHSOWR110(s[156]);
initHSOWR111(s[157]);
initHSOWR112(s[158]);
initHSOWR113(s[159]);
initHSOWR114(s[160]);
initHSOWR115(s[161]);
initHSOWR116(s[162]);
initHSVAL(s[163]);
initMGYNOT(s[164]);
initHSYRBUY(s[165]);
initHSCOST(s[166]);
initHSYR04(s[167]);
initMGOLD(s[168]);
initMGLIFE(s[169]);
initMGTYPE(s[170]);
initMGEXTRA(s[171]);
initMGNEW(s[172]);
initMGXTY1(s[173]);
initMGXTY2(s[174]);
initMGXTY3(s[175]);
initMGXTY4(s[176]);
initMGXTY5(s[177]);
initMGXTY6(s[178]);
initMGXTY97(s[179]);
initHSTOTMG(s[180]);
initXPMG(s[181]);
initHSJB(s[182]);
initRENTP0(s[183]);
initRENTP1(s[184]);
initRENTP2(s[185]);
initRENTP3(s[186]);
initRENTP4(s[187]);
initRENTP5(s[188]);
initRENTP6(s[189]);
initRENTP7(s[190]);
initRENTP8(s[191]);
initRENTP9(s[192]);
initRENTP10(s[193]);
initRENTP11(s[194]);
initRENTP12(s[195]);
initRENTP13(s[196]);
initRENTP14(s[197]);
initRENTP15(s[198]);
initRENTP16(s[199]);
initRENTLL(s[200]);
initRENTF(s[201]);
initRENT(s[202]);
initRENTWC(s[203]);
initRENTINC1(s[204]);
initRENTINC2(s[205]);
initRENTINC3(s[206]);
initRENTINC96(s[207]);
initRENTHB(s[208]);
initRENTG(s[209]);
initFUELHAVE1(s[210]);
initFUELHAVE2(s[211]);
initFUELHAVE3(s[212]);
initFUELHAVE4(s[213]);
initFUELHAVE96(s[214]);
initFUELDUEL(s[215]);
initXPDUELY(s[216]);
initDUELPAY(s[217]);
initXPELECY(s[218]);
initELECPAY(s[219]);
initXPGASY(s[220]);
initGASPAY(s[221]);
initXPOILY(s[222]);
initXPSFLY(s[223]);
initHEATCH(s[224]);
initHSCTAX(s[225]);
initXPHSDB(s[226]);
initXPHSDCT(s[227]);
initXPHSDBA(s[228]);
initCDUSE1(s[229]);
initCDUSE2(s[230]);
initCDUSE3(s[231]);
initCDUSE4(s[232]);
initCDUSE5(s[233]);
initCDUSE6(s[234]);
initCDUSE7(s[235]);
initCDUSE8(s[236]);
initCDUSE9(s[237]);
initCDUSE10(s[238]);
initCDUSE11(s[239]);
initCDUSE12(s[240]);
initCDUSE13(s[241]);
initCDUSE96(s[242]);
initPCHAS(s[243]);
initPCNET(s[244]);
initPCBROAD(s[245]);
initXPFOOD1_G3(s[246]);
initXPFDOUT_G3(s[247]);
initXPALTOB_G3(s[248]);
initNCARS(s[249]);
initCARVAL(s[250]);
initHHQURECOMPLETE(s[251]);
initHIENDDATY(s[252]);
initHIENDDATM(s[253]);
initHIENDDATD(s[254]);
initHIENDDATHH(s[255]);
initHIENDDATMM(s[256]);
initHIENDDATSS(s[257]);
initINTDATEY(s[258]);
initINTDATEM(s[259]);
initINTDATED(s[260]);
initHHINTLANG(s[261]);
initOUTCOME(s[262]);
initHHOLDMODEDV(s[263]);
initRINGFENCE(s[264]);
initENSZE1(s[265]);
initWHODRIVE1(s[266]);
initCARN2H1(s[267]);
initCARFUEL1(s[268]);
initCARAGE1(s[269]);
initENSZE2(s[270]);
initWHODRIVE2(s[271]);
initCARN2H2(s[272]);
initCARFUEL2(s[273]);
initCARAGE2(s[274]);
initENSZE3(s[275]);
initWHODRIVE3(s[276]);
initCARN2H3(s[277]);
initCARFUEL3(s[278]);
initCARAGE3(s[279]);
initENSZE4(s[280]);
initWHODRIVE4(s[281]);
initCARN2H4(s[282]);
initCARFUEL4(s[283]);
initCARAGE4(s[284]);
initENSZE5(s[285]);
initWHODRIVE5(s[286]);
initCARN2H5(s[287]);
initCARFUEL5(s[288]);
initCARAGE5(s[289]);
initFIHHMNGRS_DV(s[290]);
initFIHHMNGRS_TC(s[291]);
initFIHHMNLABGRS_DV(s[292]);
initFIHHMNLABGRS_TC(s[293]);
initRENTGRS_IF(s[294]);
initXPMIF(s[295]);
initFF_HSBEDS(s[296]);
initFF_HSROOMS(s[297]);
initFF_HSOWND(s[298]);
initNPENSIONER_DV(s[299]);
initFIHHMNNET1_DV(s[300]);
initFIHHMNLABNET_DV(s[301]);
initFIHHMNMISC_DV(s[302]);
initFIHHMNPRBEN_DV(s[303]);
initFIHHMNINV_DV(s[304]);
initFIHHMNPEN_DV(s[305]);
initFIHHMNSBEN_DV(s[306]);
initRENT_DV(s[307]);
initRENTGRS_DV(s[308]);
initHBADJUST_DV(s[309]);
initXPMDV(s[310]);
initXPMGINT_DV(s[311]);
initHOUSCOST1_DV(s[312]);
initHOUSCOST2_DV(s[313]);
initFIHHMNGRS1_DV(s[314]);
initCOUNTRY(s[315]);
initGOR_DV(s[316]);
initURBAN_DV(s[317]);
initHHRESP_DV(s[318]);
initHHTYPE_DV(s[319]);
initHRPID(s[320]);
initHRPNO(s[321]);
initNCOUPLE_DV(s[322]);
initNONEPAR_DV(s[323]);
initNKIDS_DV(s[324]);
initNCH02_DV(s[325]);
initNCH34_DV(s[326]);
initNCH511_DV(s[327]);
initNCH1215_DV(s[328]);
initAGECHY_DV(s[329]);
initNPENS_DV(s[330]);
initNEMP_DV(s[331]);
initNUE_DV(s[332]);
initNWAGE_DV(s[333]);
initNCHOECD_DV(s[334]);
initNADOECD_DV(s[335]);
initIEQMOECD_DV(s[336]);
initTENURE_DV(s[337]);
initFIHHNEGSEI_IF(s[338]);
initFIHHMNGRS_IF(s[339]);
initHHDENUB_XW(s[340]);
initHHDENUI_XW(s[341]);
}
}
