/**
 * Source code generated by uk.ac.leeds.ccg.andyt.generic.data.us.process.US_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.andyt.generic.data.us.data.hhold;
public class US_Wave3Or4Or5_HHOLD_Record extends US_Wave1Or2Or3Or4Or5_HHOLD_Record {
protected int PID;
protected final void initPID(String s) {
if (!s.trim().isEmpty()) {
PID = Integer.parseInt(s);
} else {
PID = Integer.MIN_VALUE;
}
}

public int getPID() {
return PID;
}

}
