/**
 * Source code generated by uk.ac.leeds.ccg.andyt.generic.data.us.process.US_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.andyt.generic.data.us.data.hhold;
import java.io.Serializable;
public class US_Wave1Or2Or3Or4Or5_HHOLD_Record implements Serializable {
protected String[] s;
protected int PIDP;
protected final void initPIDP(String s) {
if (!s.trim().isEmpty()) {
PIDP = Integer.parseInt(s);
} else {
PIDP = Integer.MIN_VALUE;
}
}

public int getPIDP() {
return PIDP;
}

}
